sudo dpkg --remove account-plugin-aim
sudo dpkg --remove account-plugin-facebook
sudo dpkg --remove account-plugin-flickr
sudo dpkg --remove account-plugin-google
sudo dpkg --remove account-plugin-jabber
sudo dpkg --remove account-plugin-salut
sudo dpkg --remove account-plugin-twitter
sudo dpkg --remove account-plugin-ubuntuone
sudo dpkg --remove account-plugin-windows-live
sudo dpkg --remove account-plugin-yahoo
sudo dpkg --remove accountsservice
sudo dpkg --remove accountsservice-ubuntu-schemas
sudo dpkg --remove accountsservice-ubuntu-touch-schemas
sudo dpkg --remove acl
sudo dpkg --remove acpi-support
sudo dpkg --remove acpid
sudo dpkg --remove activity-log-manager
sudo dpkg --remove activity-log-manager-control-center
sudo dpkg --remove adium-theme-ubuntu
sudo dpkg --remove aisleriot
sudo dpkg --remove alsa-base
sudo dpkg --remove alsa-utils
sudo dpkg --remove anacron
sudo dpkg --remove apg
sudo dpkg --remove app-install-data
sudo dpkg --remove app-install-data-partner
sudo dpkg --remove apparmor
sudo dpkg --remove apparmor-easyprof
sudo dpkg --remove apparmor-easyprof-ubuntu
sudo dpkg --remove appmenu-qt
sudo dpkg --remove appmenu-qt5
sudo dpkg --remove apport
sudo dpkg --remove apport-gtk
sudo dpkg --remove apport-symptoms
sudo dpkg --remove apt-transport-https
sudo dpkg --remove apt-xapian-index
sudo dpkg --remove aptdaemon
sudo dpkg --remove aptdaemon-data
sudo dpkg --remove apturl
sudo dpkg --remove apturl-common
sudo dpkg --remove aspell
sudo dpkg --remove aspell-en
sudo dpkg --remove at-spi2-core
sudo dpkg --remove attr
sudo dpkg --remove avahi-autoipd
sudo dpkg --remove avahi-daemon
sudo dpkg --remove avahi-utils
sudo dpkg --remove b43-fwcutter
sudo dpkg --remove bamfdaemon
sudo dpkg --remove baobab
sudo dpkg --remove bash-completion
sudo dpkg --remove bc
sudo dpkg --remove bind9-host
sudo dpkg --remove binfmt-support
sudo dpkg --remove bluez
sudo dpkg --remove bluez-alsa:amd64
sudo dpkg --remove bluez-cups
sudo dpkg --remove branding-ubuntu
sudo dpkg --remove brasero
sudo dpkg --remove brasero-cdrkit
sudo dpkg --remove brasero-common
sudo dpkg --remove brltty
sudo dpkg --remove bsdmainutils
sudo dpkg --remove build-essential
sudo dpkg --remove busybox-static
sudo dpkg --remove bzip2
sudo dpkg --remove cabextract
sudo dpkg --remove checkbox-gui
sudo dpkg --remove checkbox-ng
sudo dpkg --remove checkbox-ng-service
sudo dpkg --remove cheese
sudo dpkg --remove cheese-common
sudo dpkg --remove click
sudo dpkg --remove click-apparmor
sudo dpkg --remove colord
sudo dpkg --remove command-not-found
sudo dpkg --remove command-not-found-data
sudo dpkg --remove compiz
sudo dpkg --remove compiz-core
sudo dpkg --remove compiz-gnome
sudo dpkg --remove compiz-plugins-default
sudo dpkg --remove console-setup
sudo dpkg --remove cpp
sudo dpkg --remove cpp-4.8
sudo dpkg --remove cracklib-runtime
sudo dpkg --remove crda
sudo dpkg --remove cryptsetup-bin
sudo dpkg --remove cups
sudo dpkg --remove cups-browsed
sudo dpkg --remove cups-bsd
sudo dpkg --remove cups-client
sudo dpkg --remove cups-common
sudo dpkg --remove cups-core-drivers
sudo dpkg --remove cups-daemon
sudo dpkg --remove cups-filters
sudo dpkg --remove cups-filters-core-drivers
sudo dpkg --remove cups-pk-helper
sudo dpkg --remove cups-ppdc
sudo dpkg --remove cups-server-common
sudo dpkg --remove curl
sudo dpkg --remove dbus
sudo dpkg --remove dbus-x11
sudo dpkg --remove dc
sudo dpkg --remove dconf-cli
sudo dpkg --remove dconf-editor
sudo dpkg --remove dconf-gsettings-backend:amd64
sudo dpkg --remove dconf-service
sudo dpkg --remove dconf-tools
sudo dpkg --remove deja-dup
sudo dpkg --remove deja-dup-backend-gvfs
sudo dpkg --remove desktop-file-utils
sudo dpkg --remove dialog
sudo dpkg --remove dictionaries-common
sudo dpkg --remove diffstat
sudo dpkg --remove dmidecode
sudo dpkg --remove dmsetup
sudo dpkg --remove dmz-cursor-theme
sudo dpkg --remove dnsmasq-base
sudo dpkg --remove dnsutils
sudo dpkg --remove doc-base
sudo dpkg --remove dosfstools
sudo dpkg --remove dpkg-dev
sudo dpkg --remove duplicity
sudo dpkg --remove dvd+rw-tools
sudo dpkg --remove e2fslibs:amd64
sudo dpkg --remove ed
sudo dpkg --remove efibootmgr
sudo dpkg --remove eject
sudo dpkg --remove empathy
sudo dpkg --remove empathy-common
sudo dpkg --remove enchant
sudo dpkg --remove eog
sudo dpkg --remove espeak-data:amd64
sudo dpkg --remove ethtool
sudo dpkg --remove evince
sudo dpkg --remove evince-common
sudo dpkg --remove evolution-data-server
sudo dpkg --remove evolution-data-server-common
sudo dpkg --remove evolution-data-server-online-accounts
sudo dpkg --remove example-content
sudo dpkg --remove fakeroot
sudo dpkg --remove file-roller
sudo dpkg --remove firefox
sudo dpkg --remove firefox-locale-en
sudo dpkg --remove firmware-b43-installer
sudo dpkg --remove folks-common
sudo dpkg --remove fonts-droid
sudo dpkg --remove fonts-freefont-ttf
sudo dpkg --remove fonts-horai-umefont
sudo dpkg --remove fonts-kacst
sudo dpkg --remove fonts-kacst-one
sudo dpkg --remove fonts-khmeros-core
sudo dpkg --remove fonts-lao
sudo dpkg --remove fonts-liberation
sudo dpkg --remove fonts-lklug-sinhala
sudo dpkg --remove fonts-nanum
sudo dpkg --remove fonts-opensymbol
sudo dpkg --remove fonts-sil-abyssinica
sudo dpkg --remove fonts-sil-padauk
sudo dpkg --remove fonts-takao-pgothic
sudo dpkg --remove fonts-thai-tlwg
sudo dpkg --remove fonts-tibetan-machine
sudo dpkg --remove fonts-tlwg-garuda
sudo dpkg --remove fonts-tlwg-kinnari
sudo dpkg --remove fonts-tlwg-loma
sudo dpkg --remove fonts-tlwg-mono
sudo dpkg --remove fonts-tlwg-norasi
sudo dpkg --remove fonts-tlwg-purisa
sudo dpkg --remove fonts-tlwg-sawasdee
sudo dpkg --remove fonts-tlwg-typewriter
sudo dpkg --remove fonts-tlwg-typist
sudo dpkg --remove fonts-tlwg-typo
sudo dpkg --remove fonts-tlwg-umpush
sudo dpkg --remove fonts-tlwg-waree
sudo dpkg --remove fonts-unfonts-core
sudo dpkg --remove fonts-wqy-microhei
sudo dpkg --remove foomatic-db-compressed-ppds
sudo dpkg --remove friendly-recovery
sudo dpkg --remove friends
sudo dpkg --remove friends-dispatcher
sudo dpkg --remove friends-facebook
sudo dpkg --remove friends-twitter
sudo dpkg --remove ftp
sudo dpkg --remove fuse
sudo dpkg --remove g++
sudo dpkg --remove g++-4.8
sudo dpkg --remove gawk
sudo dpkg --remove gcc
sudo dpkg --remove gcc-4.8
sudo dpkg --remove gcc-4.8-base:amd64
sudo dpkg --remove gcc-4.8-base:i386
sudo dpkg --remove gcc-4.9-base:amd64
sudo dpkg --remove gcc-4.9-base:i386
sudo dpkg --remove gconf-service
sudo dpkg --remove gconf-service-backend
sudo dpkg --remove gconf2
sudo dpkg --remove gconf2-common
sudo dpkg --remove gcr
sudo dpkg --remove gdb
sudo dpkg --remove gdisk
sudo dpkg --remove gedit
sudo dpkg --remove gedit-common
sudo dpkg --remove genisoimage
sudo dpkg --remove geoclue
sudo dpkg --remove geoclue-ubuntu-geoip
sudo dpkg --remove geoip-database
sudo dpkg --remove gettext
sudo dpkg --remove gettext-base
sudo dpkg --remove ghostscript
sudo dpkg --remove ghostscript-x
sudo dpkg --remove gir1.2-accounts-1.0
sudo dpkg --remove gir1.2-appindicator3-0.1
sudo dpkg --remove gir1.2-atk-1.0
sudo dpkg --remove gir1.2-atspi-2.0
sudo dpkg --remove gir1.2-click-0.4
sudo dpkg --remove gir1.2-dbusmenu-glib-0.4
sudo dpkg --remove gir1.2-dee-1.0
sudo dpkg --remove gir1.2-ebook-1.2
sudo dpkg --remove gir1.2-ebookcontacts-1.2
sudo dpkg --remove gir1.2-edataserver-1.2
sudo dpkg --remove gir1.2-freedesktop
sudo dpkg --remove gir1.2-gdata-0.0
sudo dpkg --remove gir1.2-gdkpixbuf-2.0
sudo dpkg --remove gir1.2-gee-0.8
sudo dpkg --remove gir1.2-glib-2.0
sudo dpkg --remove gir1.2-gmenu-3.0
sudo dpkg --remove gir1.2-gnomebluetooth-1.0
sudo dpkg --remove gir1.2-gnomekeyring-1.0
sudo dpkg --remove gir1.2-goa-1.0
sudo dpkg --remove gir1.2-gst-plugins-base-1.0
sudo dpkg --remove gir1.2-gstreamer-1.0
sudo dpkg --remove gir1.2-gtk-3.0
sudo dpkg --remove gir1.2-gtksource-3.0
sudo dpkg --remove gir1.2-gudev-1.0
sudo dpkg --remove gir1.2-ibus-1.0
sudo dpkg --remove gir1.2-javascriptcoregtk-3.0
sudo dpkg --remove gir1.2-json-1.0
sudo dpkg --remove gir1.2-messagingmenu-1.0
sudo dpkg --remove gir1.2-networkmanager-1.0
sudo dpkg --remove gir1.2-notify-0.7
sudo dpkg --remove gir1.2-packagekitglib-1.0
sudo dpkg --remove gir1.2-pango-1.0
sudo dpkg --remove gir1.2-peas-1.0
sudo dpkg --remove gir1.2-rb-3.0
sudo dpkg --remove gir1.2-secret-1
sudo dpkg --remove gir1.2-signon-1.0
sudo dpkg --remove gir1.2-soup-2.4
sudo dpkg --remove gir1.2-totem-1.0
sudo dpkg --remove gir1.2-totem-plparser-1.0
sudo dpkg --remove gir1.2-udisks-2.0
sudo dpkg --remove gir1.2-unity-5.0:amd64
sudo dpkg --remove gir1.2-vte-2.90
sudo dpkg --remove gir1.2-webkit-3.0
sudo dpkg --remove gir1.2-wnck-3.0
sudo dpkg --remove git
sudo dpkg --remove git-man
sudo dpkg --remove gkbd-capplet
sudo dpkg --remove gksu
sudo dpkg --remove glib-networking:amd64
sudo dpkg --remove glib-networking-common
sudo dpkg --remove glib-networking-services
sudo dpkg --remove gnome-accessibility-themes
sudo dpkg --remove gnome-bluetooth
sudo dpkg --remove gnome-calculator
sudo dpkg --remove gnome-contacts
sudo dpkg --remove gnome-control-center-shared-data
sudo dpkg --remove gnome-desktop3-data
sudo dpkg --remove gnome-disk-utility
sudo dpkg --remove gnome-exe-thumbnailer
sudo dpkg --remove gnome-font-viewer
sudo dpkg --remove gnome-icon-theme
sudo dpkg --remove gnome-icon-theme-symbolic
sudo dpkg --remove gnome-keyring
sudo dpkg --remove gnome-mahjongg
sudo dpkg --remove gnome-menus
sudo dpkg --remove gnome-mines
sudo dpkg --remove gnome-orca
sudo dpkg --remove gnome-power-manager
sudo dpkg --remove gnome-screensaver
sudo dpkg --remove gnome-screenshot
sudo dpkg --remove gnome-session-bin
sudo dpkg --remove gnome-session-canberra
sudo dpkg --remove gnome-session-common
sudo dpkg --remove gnome-settings-daemon-schemas
sudo dpkg --remove gnome-sudoku
sudo dpkg --remove gnome-system-log
sudo dpkg --remove gnome-system-monitor
sudo dpkg --remove gnome-terminal
sudo dpkg --remove gnome-terminal-data
sudo dpkg --remove gnome-user-guide
sudo dpkg --remove gnome-user-share
sudo dpkg --remove gnome-video-effects
sudo dpkg --remove gnomine
sudo dpkg --remove google-chrome-stable
sudo dpkg --remove groff-base
sudo dpkg --remove growisofs
sudo dpkg --remove grub-common
sudo dpkg --remove grub-efi-amd64
sudo dpkg --remove grub-efi-amd64-bin
sudo dpkg --remove grub-efi-amd64-signed
sudo dpkg --remove grub2-common
sudo dpkg --remove gsettings-desktop-schemas
sudo dpkg --remove gsettings-ubuntu-schemas
sudo dpkg --remove gsettings-ubuntu-touch-schemas
sudo dpkg --remove gsfonts
sudo dpkg --remove gstreamer0.10-alsa:amd64
sudo dpkg --remove gstreamer0.10-nice:amd64
sudo dpkg --remove gstreamer0.10-plugins-base:amd64
sudo dpkg --remove gstreamer0.10-plugins-base-apps
sudo dpkg --remove gstreamer0.10-plugins-good:amd64
sudo dpkg --remove gstreamer0.10-pulseaudio:amd64
sudo dpkg --remove gstreamer0.10-tools
sudo dpkg --remove gstreamer0.10-x:amd64
sudo dpkg --remove gstreamer1.0-alsa:amd64
sudo dpkg --remove gstreamer1.0-clutter
sudo dpkg --remove gstreamer1.0-nice:amd64
sudo dpkg --remove gstreamer1.0-plugins-base:amd64
sudo dpkg --remove gstreamer1.0-plugins-base-apps
sudo dpkg --remove gstreamer1.0-plugins-good:amd64
sudo dpkg --remove gstreamer1.0-pulseaudio:amd64
sudo dpkg --remove gstreamer1.0-tools
sudo dpkg --remove gstreamer1.0-x:amd64
sudo dpkg --remove gtk2-engines-murrine:amd64
sudo dpkg --remove gtk3-engines-unico:amd64
sudo dpkg --remove gucharmap
sudo dpkg --remove guile-2.0-libs
sudo dpkg --remove gvfs:amd64
sudo dpkg --remove gvfs-backends
sudo dpkg --remove gvfs-bin
sudo dpkg --remove gvfs-common
sudo dpkg --remove gvfs-daemons
sudo dpkg --remove gvfs-fuse
sudo dpkg --remove gvfs-libs:amd64
sudo dpkg --remove gyp
sudo dpkg --remove hardening-includes
sudo dpkg --remove hdparm
sudo dpkg --remove hicolor-icon-theme
sudo dpkg --remove hplip
sudo dpkg --remove hplip-data
sudo dpkg --remove hud
sudo dpkg --remove humanity-icon-theme
sudo dpkg --remove hunspell-en-us
sudo dpkg --remove hwdata
sudo dpkg --remove ibus
sudo dpkg --remove ibus-gtk:amd64
sudo dpkg --remove ibus-gtk3:amd64
sudo dpkg --remove ibus-pinyin
sudo dpkg --remove ibus-table
sudo dpkg --remove icoutils
sudo dpkg --remove im-config
sudo dpkg --remove imagemagick
sudo dpkg --remove imagemagick-common
sudo dpkg --remove indicator-applet
sudo dpkg --remove indicator-application
sudo dpkg --remove indicator-appmenu
sudo dpkg --remove indicator-bluetooth
sudo dpkg --remove indicator-datetime
sudo dpkg --remove indicator-keyboard
sudo dpkg --remove indicator-messages
sudo dpkg --remove indicator-network
sudo dpkg --remove indicator-power
sudo dpkg --remove indicator-printers
sudo dpkg --remove indicator-session
sudo dpkg --remove indicator-sound
sudo dpkg --remove info
sudo dpkg --remove inkscape
sudo dpkg --remove inputattach
sudo dpkg --remove install-info
sudo dpkg --remove intel-gpu-tools
sudo dpkg --remove intltool-debian
sudo dpkg --remove iproute
sudo dpkg --remove iptables
sudo dpkg --remove iputils-arping
sudo dpkg --remove iputils-tracepath
sudo dpkg --remove irqbalance
sudo dpkg --remove iso-codes
sudo dpkg --remove iw
sudo dpkg --remove javascript-common
sudo dpkg --remove kbd
sudo dpkg --remove kerneloops-daemon
sudo dpkg --remove keyboard-configuration
sudo dpkg --remove krb5-locales
sudo dpkg --remove landscape-client-ui-install
sudo dpkg --remove language-pack-en
sudo dpkg --remove language-pack-en-base
sudo dpkg --remove language-pack-gnome-en
sudo dpkg --remove language-pack-gnome-en-base
sudo dpkg --remove language-selector-common
sudo dpkg --remove language-selector-gnome
sudo dpkg --remove laptop-detect
sudo dpkg --remove less
sudo dpkg --remove libaa1:amd64
sudo dpkg --remove libaccount-plugin-1.0-0
sudo dpkg --remove libaccount-plugin-generic-oauth
sudo dpkg --remove libaccount-plugin-google
sudo dpkg --remove libaccounts-glib0:amd64
sudo dpkg --remove libaccounts-qt5-1
sudo dpkg --remove libaccountsservice0:amd64
sudo dpkg --remove libacl1:amd64
sudo dpkg --remove libaio1:amd64
sudo dpkg --remove libandroid-properties1
sudo dpkg --remove libapparmor-perl
sudo dpkg --remove libapparmor1:amd64
sudo dpkg --remove libappindicator1
sudo dpkg --remove libappindicator3-1
sudo dpkg --remove libapt-inst1.5:amd64
sudo dpkg --remove libapt-pkg-perl
sudo dpkg --remove libapt-pkg4.12:amd64
sudo dpkg --remove libarchive-zip-perl
sudo dpkg --remove libarchive13:amd64
sudo dpkg --remove libart-2.0-2:amd64
sudo dpkg --remove libasan0:amd64
sudo dpkg --remove libasn1-8-heimdal:amd64
sudo dpkg --remove libasn1-8-heimdal:i386
sudo dpkg --remove libasound2:amd64
sudo dpkg --remove libasound2:i386
sudo dpkg --remove libasound2-plugins:amd64
sudo dpkg --remove libasound2-plugins:i386
sudo dpkg --remove libaspell15
sudo dpkg --remove libasprintf-dev:amd64
sudo dpkg --remove libasprintf0c2:amd64
sudo dpkg --remove libassuan0:amd64
sudo dpkg --remove libasyncns0:amd64
sudo dpkg --remove libasyncns0:i386
sudo dpkg --remove libatasmart4:amd64
sudo dpkg --remove libatk-adaptor:amd64
sudo dpkg --remove libatk-bridge2.0-0:amd64
sudo dpkg --remove libatk-bridge2.0-0:i386
sudo dpkg --remove libatk1.0-0:amd64
sudo dpkg --remove libatk1.0-0:i386
sudo dpkg --remove libatkmm-1.6-1:amd64
sudo dpkg --remove libatomic1:amd64
sudo dpkg --remove libatspi2.0-0:amd64
sudo dpkg --remove libatspi2.0-0:i386
sudo dpkg --remove libattr1:amd64
sudo dpkg --remove libaudio2:amd64
sudo dpkg --remove libaudit1:amd64
sudo dpkg --remove libauthen-sasl-perl
sudo dpkg --remove libautodie-perl
sudo dpkg --remove libavahi-client3:amd64
sudo dpkg --remove libavahi-client3:i386
sudo dpkg --remove libavahi-common-data:amd64
sudo dpkg --remove libavahi-common-data:i386
sudo dpkg --remove libavahi-common3:amd64
sudo dpkg --remove libavahi-common3:i386
sudo dpkg --remove libavahi-core7:amd64
sudo dpkg --remove libavahi-glib1:amd64
sudo dpkg --remove libavahi-gobject0:amd64
sudo dpkg --remove libavc1394-0:amd64
sudo dpkg --remove libbamf3-2:amd64
sudo dpkg --remove libbind9-90
sudo dpkg --remove libblkid1:amd64
sudo dpkg --remove libbluetooth3:amd64
sudo dpkg --remove libboost-date-time1.54.0:amd64
sudo dpkg --remove libboost-iostreams1.54.0:amd64
sudo dpkg --remove libboost-program-options1.54.0:amd64
sudo dpkg --remove libboost-serialization1.54.0:amd64
sudo dpkg --remove libboost-system1.54.0:amd64
sudo dpkg --remove libbrasero-media3-1
sudo dpkg --remove libbrlapi0.6:amd64
sudo dpkg --remove libbsd0:amd64
sudo dpkg --remove libburn4
sudo dpkg --remove libbz2-1.0:amd64
sudo dpkg --remove libc-ares-dev:amd64
sudo dpkg --remove libc-ares2:amd64
sudo dpkg --remove libc6:amd64
sudo dpkg --remove libc6:i386
sudo dpkg --remove libc6-dbg:amd64
sudo dpkg --remove libc6-dev:amd64
sudo dpkg --remove libcaca0:amd64
sudo dpkg --remove libcairo-gobject2:amd64
sudo dpkg --remove libcairo-gobject2:i386
sudo dpkg --remove libcairo2:amd64
sudo dpkg --remove libcairo2:i386
sudo dpkg --remove libcairomm-1.0-1:amd64
sudo dpkg --remove libcamel-1.2-45
sudo dpkg --remove libcanberra-gtk-module:amd64
sudo dpkg --remove libcanberra-gtk0:amd64
sudo dpkg --remove libcanberra-gtk3-0:amd64
sudo dpkg --remove libcanberra-gtk3-module:amd64
sudo dpkg --remove libcanberra-pulse:amd64
sudo dpkg --remove libcanberra0:amd64
sudo dpkg --remove libcap-ng0
sudo dpkg --remove libcap2:amd64
sudo dpkg --remove libcapi20-3:amd64
sudo dpkg --remove libcapi20-3:i386
sudo dpkg --remove libcapnp-0.4.0:amd64
sudo dpkg --remove libcdio-cdda1
sudo dpkg --remove libcdio-paranoia1
sudo dpkg --remove libcdio13
sudo dpkg --remove libcdparanoia0:amd64
sudo dpkg --remove libcdr-0.0-0
sudo dpkg --remove libcgmanager0:amd64
sudo dpkg --remove libcgmanager0:i386
sudo dpkg --remove libcheese-gtk23:amd64
sudo dpkg --remove libcheese7:amd64
sudo dpkg --remove libck-connector0:amd64
sudo dpkg --remove libclass-accessor-perl
sudo dpkg --remove libclick-0.4-0:amd64
sudo dpkg --remove libclone-perl
sudo dpkg --remove libcloog-isl4:amd64
sudo dpkg --remove libclucene-contribs1:amd64
sudo dpkg --remove libclucene-core1:amd64
sudo dpkg --remove libclutter-1.0-0:amd64
sudo dpkg --remove libclutter-1.0-common
sudo dpkg --remove libclutter-gst-2.0-0:amd64
sudo dpkg --remove libclutter-gtk-1.0-0:amd64
sudo dpkg --remove libcmis-0.4-4
sudo dpkg --remove libcogl-common
sudo dpkg --remove libcogl-pango15:amd64
sudo dpkg --remove libcogl15:amd64
sudo dpkg --remove libcolamd2.8.0:amd64
sudo dpkg --remove libcolord1:amd64
sudo dpkg --remove libcolord1:i386
sudo dpkg --remove libcolorhug1:amd64
sudo dpkg --remove libcolumbus1:amd64
sudo dpkg --remove libcolumbus1-common
sudo dpkg --remove libcomerr2:amd64
sudo dpkg --remove libcomerr2:i386
sudo dpkg --remove libcompizconfig0
sudo dpkg --remove libcontent-hub0:amd64
sudo dpkg --remove libcrack2:amd64
sudo dpkg --remove libcroco3:amd64
sudo dpkg --remove libcrypt-passwdmd5-perl
sudo dpkg --remove libcryptsetup4
sudo dpkg --remove libcups2:amd64
sudo dpkg --remove libcups2:i386
sudo dpkg --remove libcupscgi1:amd64
sudo dpkg --remove libcupsfilters1:amd64
sudo dpkg --remove libcupsimage2:amd64
sudo dpkg --remove libcupsmime1:amd64
sudo dpkg --remove libcupsppdc1:amd64
sudo dpkg --remove libcurl3:amd64
sudo dpkg --remove libcurl3:i386
sudo dpkg --remove libcurl3-gnutls:amd64
sudo dpkg --remove libdaemon0
sudo dpkg --remove libdatrie1:amd64
sudo dpkg --remove libdatrie1:i386
sudo dpkg --remove libdb5.3:amd64
sudo dpkg --remove libdb5.3:i386
sudo dpkg --remove libdbus-1-3:amd64
sudo dpkg --remove libdbus-1-3:i386
sudo dpkg --remove libdbus-cpp2:amd64
sudo dpkg --remove libdbus-glib-1-2:amd64
sudo dpkg --remove libdbus-glib-1-2:i386
sudo dpkg --remove libdbusmenu-glib4:amd64
sudo dpkg --remove libdbusmenu-glib4:i386
sudo dpkg --remove libdbusmenu-gtk3-4:amd64
sudo dpkg --remove libdbusmenu-gtk3-4:i386
sudo dpkg --remove libdbusmenu-gtk4:amd64
sudo dpkg --remove libdbusmenu-gtk4:i386
sudo dpkg --remove libdbusmenu-qt2:amd64
sudo dpkg --remove libdbusmenu-qt5:amd64
sudo dpkg --remove libdconf1:amd64
sudo dpkg --remove libdebconfclient0:amd64
sudo dpkg --remove libdecoration0
sudo dpkg --remove libdee-1.0-4:amd64
sudo dpkg --remove libdee-qt5-3:amd64
sudo dpkg --remove libdevmapper-event1.02.1:amd64
sudo dpkg --remove libdevmapper1.02.1:amd64
sudo dpkg --remove libdigest-hmac-perl
sudo dpkg --remove libdjvulibre-text
sudo dpkg --remove libdjvulibre21:amd64
sudo dpkg --remove libdmapsharing-3.0-2
sudo dpkg --remove libdns100
sudo dpkg --remove libdotconf0:amd64
sudo dpkg --remove libdrm-intel1:amd64
sudo dpkg --remove libdrm-intel1:i386
sudo dpkg --remove libdrm-nouveau2:amd64
sudo dpkg --remove libdrm-nouveau2:i386
sudo dpkg --remove libdrm-radeon1:amd64
sudo dpkg --remove libdrm-radeon1:i386
sudo dpkg --remove libdrm2:amd64
sudo dpkg --remove libdrm2:i386
sudo dpkg --remove libdv4:amd64
sudo dpkg --remove libebackend-1.2-7
sudo dpkg --remove libebook-1.2-14
sudo dpkg --remove libebook-contacts-1.2-0
sudo dpkg --remove libecal-1.2-16
sudo dpkg --remove libedata-book-1.2-20
sudo dpkg --remove libedata-cal-1.2-23
sudo dpkg --remove libedataserver-1.2-18
sudo dpkg --remove libedit2:amd64
sudo dpkg --remove libedit2:i386
sudo dpkg --remove libegl1-mesa-drivers-lts-utopic:amd64
sudo dpkg --remove libegl1-mesa-lts-utopic:amd64
sudo dpkg --remove libelf1:amd64
sudo dpkg --remove libelf1:i386
sudo dpkg --remove libelfg0:amd64
sudo dpkg --remove libemail-valid-perl
sudo dpkg --remove libenchant1c2a:amd64
sudo dpkg --remove libencode-locale-perl
sudo dpkg --remove libepoxy0
sudo dpkg --remove liberror-perl
sudo dpkg --remove libespeak1:amd64
sudo dpkg --remove libevdev2
sudo dpkg --remove libevdocument3-4
sudo dpkg --remove libevent-2.0-5:amd64
sudo dpkg --remove libevview3-3
sudo dpkg --remove libexempi3:amd64
sudo dpkg --remove libexif12:amd64
sudo dpkg --remove libexif12:i386
sudo dpkg --remove libexiv2-12
sudo dpkg --remove libexpat1:amd64
sudo dpkg --remove libexpat1:i386
sudo dpkg --remove libexttextcat-2.0-0
sudo dpkg --remove libexttextcat-data
sudo dpkg --remove libfakeroot:amd64
sudo dpkg --remove libfarstream-0.1-0:amd64
sudo dpkg --remove libfarstream-0.2-2:amd64
sudo dpkg --remove libffi6:amd64
sudo dpkg --remove libffi6:i386
sudo dpkg --remove libfftw3-double3:amd64
sudo dpkg --remove libfftw3-single3:amd64
sudo dpkg --remove libfile-basedir-perl
sudo dpkg --remove libfile-copy-recursive-perl
sudo dpkg --remove libfile-desktopentry-perl
sudo dpkg --remove libfile-listing-perl
sudo dpkg --remove libfile-mimeinfo-perl
sudo dpkg --remove libflac8:amd64
sudo dpkg --remove libflac8:i386
sudo dpkg --remove libfolks-eds25:amd64
sudo dpkg --remove libfolks-telepathy25:amd64
sudo dpkg --remove libfolks25:amd64
sudo dpkg --remove libfont-afm-perl
sudo dpkg --remove libfontconfig1:amd64
sudo dpkg --remove libfontconfig1:i386
sudo dpkg --remove libfontembed1:amd64
sudo dpkg --remove libfontenc1:amd64
sudo dpkg --remove libframe6:amd64
sudo dpkg --remove libfreerdp-plugins-standard:amd64
sudo dpkg --remove libfreerdp1:amd64
sudo dpkg --remove libfreetype6:amd64
sudo dpkg --remove libfreetype6:i386
sudo dpkg --remove libfribidi0:amd64
sudo dpkg --remove libfriends0:amd64
sudo dpkg --remove libfs6:amd64
sudo dpkg --remove libfuse2:amd64
sudo dpkg --remove libgail-3-0:amd64
sudo dpkg --remove libgail-common:amd64
sudo dpkg --remove libgail18:amd64
sudo dpkg --remove libgbm1:amd64
sudo dpkg --remove libgbm1-lts-utopic:amd64
sudo dpkg --remove libgc1c2:amd64
sudo dpkg --remove libgcc-4.8-dev:amd64
sudo dpkg --remove libgcc1:amd64
sudo dpkg --remove libgcc1:i386
sudo dpkg --remove libgck-1-0:amd64
sudo dpkg --remove libgconf-2-4:amd64
sudo dpkg --remove libgconf-2-4:i386
sudo dpkg --remove libgcr-3-common
sudo dpkg --remove libgcr-base-3-1:amd64
sudo dpkg --remove libgcr-ui-3-1:amd64
sudo dpkg --remove libgcrypt11:amd64
sudo dpkg --remove libgcrypt11:i386
sudo dpkg --remove libgd3:amd64
sudo dpkg --remove libgd3:i386
sudo dpkg --remove libgdata-common
sudo dpkg --remove libgdata13
sudo dpkg --remove libgdbm3:amd64
sudo dpkg --remove libgdk-pixbuf2.0-0:amd64
sudo dpkg --remove libgdk-pixbuf2.0-0:i386
sudo dpkg --remove libgee-0.8-2:amd64
sudo dpkg --remove libgee2:amd64
sudo dpkg --remove libgeis1:amd64
sudo dpkg --remove libgeoclue0:amd64
sudo dpkg --remove libgeoip1:amd64
sudo dpkg --remove libgettextpo-dev:amd64
sudo dpkg --remove libgettextpo0:amd64
sudo dpkg --remove libgexiv2-2:amd64
sudo dpkg --remove libgflags2
sudo dpkg --remove libgfortran3:amd64
sudo dpkg --remove libgif4:amd64
sudo dpkg --remove libgif4:i386
sudo dpkg --remove libgksu2-0
sudo dpkg --remove libgl1-mesa-dri-lts-utopic:amd64
sudo dpkg --remove libgl1-mesa-dri-lts-utopic:i386
sudo dpkg --remove libgl1-mesa-glx-lts-utopic:amd64
sudo dpkg --remove libgl1-mesa-glx-lts-utopic:i386
sudo dpkg --remove libglade2-0:amd64
sudo dpkg --remove libglapi-mesa-lts-utopic:amd64
sudo dpkg --remove libglapi-mesa-lts-utopic:i386
sudo dpkg --remove libgles1-mesa-lts-utopic:amd64
sudo dpkg --remove libgles2-mesa-lts-utopic:amd64
sudo dpkg --remove libglew1.10:amd64
sudo dpkg --remove libglewmx1.10:amd64
sudo dpkg --remove libglib2.0-0:amd64
sudo dpkg --remove libglib2.0-0:i386
sudo dpkg --remove libglibmm-2.4-1c2a:amd64
sudo dpkg --remove libglu1-mesa:amd64
sudo dpkg --remove libglu1-mesa:i386
sudo dpkg --remove libgmime-2.6-0:amd64
sudo dpkg --remove libgmp10:amd64
sudo dpkg --remove libgnome-bluetooth11
sudo dpkg --remove libgnome-control-center1
sudo dpkg --remove libgnome-desktop-3-7
sudo dpkg --remove libgnome-keyring-common
sudo dpkg --remove libgnome-keyring0:amd64
sudo dpkg --remove libgnome-menu-3-0
sudo dpkg --remove libgnomekbd-common
sudo dpkg --remove libgnomekbd8
sudo dpkg --remove libgnomevfs2-0:amd64
sudo dpkg --remove libgnomevfs2-common
sudo dpkg --remove libgnomevfs2-extra:amd64
sudo dpkg --remove libgnutls-openssl27:amd64
sudo dpkg --remove libgnutls26:amd64
sudo dpkg --remove libgnutls26:i386
sudo dpkg --remove libgoa-1.0-0b:amd64
sudo dpkg --remove libgoa-1.0-common
sudo dpkg --remove libgomp1:amd64
sudo dpkg --remove libgoogle-glog0
sudo dpkg --remove libgpg-error0:amd64
sudo dpkg --remove libgpg-error0:i386
sudo dpkg --remove libgpgme11:amd64
sudo dpkg --remove libgphoto2-6:amd64
sudo dpkg --remove libgphoto2-6:i386
sudo dpkg --remove libgphoto2-l10n
sudo dpkg --remove libgphoto2-port10:amd64
sudo dpkg --remove libgphoto2-port10:i386
sudo dpkg --remove libgpm2:amd64
sudo dpkg --remove libgpm2:i386
sudo dpkg --remove libgpod-common
sudo dpkg --remove libgpod4:amd64
sudo dpkg --remove libgrail6
sudo dpkg --remove libgraphite2-3:amd64
sudo dpkg --remove libgraphite2-3:i386
sudo dpkg --remove libgrip0
sudo dpkg --remove libgs9
sudo dpkg --remove libgs9-common
sudo dpkg --remove libgsettings-qt1:amd64
sudo dpkg --remove libgsl0ldbl
sudo dpkg --remove libgssapi-krb5-2:amd64
sudo dpkg --remove libgssapi-krb5-2:i386
sudo dpkg --remove libgssapi3-heimdal:amd64
sudo dpkg --remove libgssapi3-heimdal:i386
sudo dpkg --remove libgssdp-1.0-3
sudo dpkg --remove libgstreamer-plugins-base0.10-0:amd64
sudo dpkg --remove libgstreamer-plugins-base0.10-0:i386
sudo dpkg --remove libgstreamer-plugins-base1.0-0:amd64
sudo dpkg --remove libgstreamer-plugins-good1.0-0:amd64
sudo dpkg --remove libgstreamer0.10-0:amd64
sudo dpkg --remove libgstreamer0.10-0:i386
sudo dpkg --remove libgstreamer1.0-0:amd64
sudo dpkg --remove libgtk-3-0:amd64
sudo dpkg --remove libgtk-3-0:i386
sudo dpkg --remove libgtk-3-bin
sudo dpkg --remove libgtk-3-common
sudo dpkg --remove libgtk2.0-0:amd64
sudo dpkg --remove libgtk2.0-0:i386
sudo dpkg --remove libgtkmm-2.4-1c2a:amd64
sudo dpkg --remove libgtkmm-3.0-1:amd64
sudo dpkg --remove libgtksourceview-3.0-1:amd64
sudo dpkg --remove libgtksourceview-3.0-common
sudo dpkg --remove libgtkspell0
sudo dpkg --remove libgtop2-7
sudo dpkg --remove libgtop2-common
sudo dpkg --remove libgucharmap-2-90-7
sudo dpkg --remove libgudev-1.0-0:amd64
sudo dpkg --remove libgupnp-1.0-4
sudo dpkg --remove libgupnp-igd-1.0-4:amd64
sudo dpkg --remove libgusb2:amd64
sudo dpkg --remove libgutenprint2
sudo dpkg --remove libgweather-3-6
sudo dpkg --remove libgweather-common
sudo dpkg --remove libgxps2:amd64
sudo dpkg --remove libhardware2
sudo dpkg --remove libharfbuzz-icu0:amd64
sudo dpkg --remove libharfbuzz0b:amd64
sudo dpkg --remove libharfbuzz0b:i386
sudo dpkg --remove libhcrypto4-heimdal:amd64
sudo dpkg --remove libhcrypto4-heimdal:i386
sudo dpkg --remove libhdb9-heimdal:amd64
sudo dpkg --remove libheimbase1-heimdal:amd64
sudo dpkg --remove libheimbase1-heimdal:i386
sudo dpkg --remove libheimntlm0-heimdal:amd64
sudo dpkg --remove libheimntlm0-heimdal:i386
sudo dpkg --remove libhpmud0
sudo dpkg --remove libhtml-form-perl
sudo dpkg --remove libhtml-format-perl
sudo dpkg --remove libhtml-parser-perl
sudo dpkg --remove libhtml-tagset-perl
sudo dpkg --remove libhtml-tree-perl
sudo dpkg --remove libhttp-cookies-perl
sudo dpkg --remove libhttp-daemon-perl
sudo dpkg --remove libhttp-date-perl
sudo dpkg --remove libhttp-message-perl
sudo dpkg --remove libhttp-negotiate-perl
sudo dpkg --remove libhud-client2:amd64
sudo dpkg --remove libhud2:amd64
sudo dpkg --remove libhunspell-1.3-0:amd64
sudo dpkg --remove libhx509-5-heimdal:amd64
sudo dpkg --remove libhx509-5-heimdal:i386
sudo dpkg --remove libhybris
sudo dpkg --remove libhybris-common1
sudo dpkg --remove libhyphen0
sudo dpkg --remove libibus-1.0-5:amd64
sudo dpkg --remove libical1
sudo dpkg --remove libice6:amd64
sudo dpkg --remove libice6:i386
sudo dpkg --remove libicu52:amd64
sudo dpkg --remove libidn11:amd64
sudo dpkg --remove libidn11:i386
sudo dpkg --remove libido3-0.1-0:amd64
sudo dpkg --remove libiec61883-0:amd64
sudo dpkg --remove libieee1284-3:amd64
sudo dpkg --remove libieee1284-3:i386
sudo dpkg --remove libijs-0.35
sudo dpkg --remove libilmbase6:amd64
sudo dpkg --remove libimobiledevice4:amd64
sudo dpkg --remove libindicator3-7
sudo dpkg --remove libindicator7
sudo dpkg --remove libio-html-perl
sudo dpkg --remove libio-pty-perl
sudo dpkg --remove libio-socket-inet6-perl
sudo dpkg --remove libio-socket-ssl-perl
sudo dpkg --remove libio-string-perl
sudo dpkg --remove libipc-run-perl
sudo dpkg --remove libipc-system-simple-perl
sudo dpkg --remove libisc95
sudo dpkg --remove libisccc90
sudo dpkg --remove libisccfg90
sudo dpkg --remove libisl10:amd64
sudo dpkg --remove libisofs6
sudo dpkg --remove libitm1:amd64
sudo dpkg --remove libiw30:amd64
sudo dpkg --remove libjack-jackd2-0:amd64
sudo dpkg --remove libjack-jackd2-0:i386
sudo dpkg --remove libjasper1:amd64
sudo dpkg --remove libjasper1:i386
sudo dpkg --remove libjavascriptcoregtk-3.0-0:amd64
sudo dpkg --remove libjbig0:amd64
sudo dpkg --remove libjbig0:i386
sudo dpkg --remove libjbig2dec0
sudo dpkg --remove libjpeg-turbo8:amd64
sudo dpkg --remove libjpeg-turbo8:i386
sudo dpkg --remove libjpeg8:amd64
sudo dpkg --remove libjpeg8:i386
sudo dpkg --remove libjs-node-uuid
sudo dpkg --remove libjson-c2:amd64
sudo dpkg --remove libjson-c2:i386
sudo dpkg --remove libjson-glib-1.0-0:amd64
sudo dpkg --remove libjson-glib-1.0-common
sudo dpkg --remove libjson0:amd64
sudo dpkg --remove libjsoncpp0:amd64
sudo dpkg --remove libjte1
sudo dpkg --remove libk5crypto3:amd64
sudo dpkg --remove libk5crypto3:i386
sudo dpkg --remove libkdc2-heimdal:amd64
sudo dpkg --remove libkeyutils1:amd64
sudo dpkg --remove libkeyutils1:i386
sudo dpkg --remove libkmod2:amd64
sudo dpkg --remove libkpathsea6
sudo dpkg --remove libkrb5-26-heimdal:amd64
sudo dpkg --remove libkrb5-26-heimdal:i386
sudo dpkg --remove libkrb5-3:amd64
sudo dpkg --remove libkrb5-3:i386
sudo dpkg --remove libkrb5support0:amd64
sudo dpkg --remove libkrb5support0:i386
sudo dpkg --remove liblangtag-common
sudo dpkg --remove liblangtag1
sudo dpkg --remove liblcms2-2:amd64
sudo dpkg --remove liblcms2-2:i386
sudo dpkg --remove libldap-2.4-2:amd64
sudo dpkg --remove libldap-2.4-2:i386
sudo dpkg --remove libldb1:amd64
sudo dpkg --remove liblightdm-gobject-1-0
sudo dpkg --remove liblircclient0
sudo dpkg --remove liblist-moreutils-perl
sudo dpkg --remove libllvm3.5:amd64
sudo dpkg --remove libllvm3.5:i386
sudo dpkg --remove liblockfile1:amd64
sudo dpkg --remove liblouis-data
sudo dpkg --remove liblouis2:amd64
sudo dpkg --remove liblqr-1-0:amd64
sudo dpkg --remove libltdl7:amd64
sudo dpkg --remove libltdl7:i386
sudo dpkg --remove liblttng-ust-ctl2:amd64
sudo dpkg --remove liblttng-ust0:amd64
sudo dpkg --remove liblua5.2-0:amd64
sudo dpkg --remove liblvm2app2.2:amd64
sudo dpkg --remove liblwp-mediatypes-perl
sudo dpkg --remove liblwp-protocol-https-perl
sudo dpkg --remove liblwres90
sudo dpkg --remove liblzma5:amd64
sudo dpkg --remove liblzma5:i386
sudo dpkg --remove liblzo2-2:amd64
sudo dpkg --remove libmagic1:amd64
sudo dpkg --remove libmagick++5:amd64
sudo dpkg --remove libmagickcore5:amd64
sudo dpkg --remove libmagickcore5-extra:amd64
sudo dpkg --remove libmagickwand5:amd64
sudo dpkg --remove libmailtools-perl
sudo dpkg --remove libmbim-glib0:amd64
sudo dpkg --remove libmeanwhile1
sudo dpkg --remove libmedia1
sudo dpkg --remove libmediascanner-2.0-0:amd64
sudo dpkg --remove libmessaging-menu0
sudo dpkg --remove libmetacity-private0a
sudo dpkg --remove libmhash2:amd64
sudo dpkg --remove libminiupnpc8
sudo dpkg --remove libmirclient7:amd64
sudo dpkg --remove libmirclientplatform-mesa:amd64
sudo dpkg --remove libmirplatform:amd64
sudo dpkg --remove libmirplatformgraphics-mesa:amd64
sudo dpkg --remove libmirprotobuf0:amd64
sudo dpkg --remove libmirserver18:amd64
sudo dpkg --remove libmission-control-plugins0
sudo dpkg --remove libmm-glib0:amd64
sudo dpkg --remove libmnl0:amd64
sudo dpkg --remove libmount1:amd64
sudo dpkg --remove libmpc3:amd64
sudo dpkg --remove libmpdec2:amd64
sudo dpkg --remove libmpfr4:amd64
sudo dpkg --remove libmpg123-0:amd64
sudo dpkg --remove libmpg123-0:i386
sudo dpkg --remove libmspub-0.0-0
sudo dpkg --remove libmtdev1:amd64
sudo dpkg --remove libmtp-common
sudo dpkg --remove libmtp-runtime
sudo dpkg --remove libmtp9:amd64
sudo dpkg --remove libmuparser2:amd64
sudo dpkg --remove libmythes-1.2-0
sudo dpkg --remove libnatpmp1
sudo dpkg --remove libnautilus-extension1a
sudo dpkg --remove libncurses5:amd64
sudo dpkg --remove libncurses5:i386
sudo dpkg --remove libncursesw5:amd64
sudo dpkg --remove libneon27-gnutls
sudo dpkg --remove libnet-dns-perl
sudo dpkg --remove libnet-domain-tld-perl
sudo dpkg --remove libnet-http-perl
sudo dpkg --remove libnet-ip-perl
sudo dpkg --remove libnet-libidn-perl
sudo dpkg --remove libnet-smtp-ssl-perl
sudo dpkg --remove libnet-ssleay-perl
sudo dpkg --remove libnetfilter-conntrack3:amd64
sudo dpkg --remove libnetpbm10
sudo dpkg --remove libnettle4:amd64
sudo dpkg --remove libnewt0.52:amd64
sudo dpkg --remove libnfnetlink0:amd64
sudo dpkg --remove libnice10:amd64
sudo dpkg --remove libnih-dbus1:amd64
sudo dpkg --remove libnih-dbus1:i386
sudo dpkg --remove libnih1:amd64
sudo dpkg --remove libnih1:i386
sudo dpkg --remove libnl-3-200:amd64
sudo dpkg --remove libnl-genl-3-200:amd64
sudo dpkg --remove libnl-route-3-200:amd64
sudo dpkg --remove libnm-glib-vpn1
sudo dpkg --remove libnm-glib4
sudo dpkg --remove libnm-gtk-common
sudo dpkg --remove libnm-gtk0
sudo dpkg --remove libnm-util2
sudo dpkg --remove libnotify-bin
sudo dpkg --remove libnotify4:amd64
sudo dpkg --remove libnspr4:amd64
sudo dpkg --remove libnspr4:i386
sudo dpkg --remove libnss-mdns:amd64
sudo dpkg --remove libnss-winbind:amd64
sudo dpkg --remove libnss3:amd64
sudo dpkg --remove libnss3:i386
sudo dpkg --remove libnss3-nssdb
sudo dpkg --remove libntdb1:amd64
sudo dpkg --remove libnuma1:amd64
sudo dpkg --remove libnux-4.0-0
sudo dpkg --remove libnux-4.0-common
sudo dpkg --remove liboauth0:amd64
sudo dpkg --remove libodbc1:amd64
sudo dpkg --remove libofono-qt1
sudo dpkg --remove libogg0:amd64
sudo dpkg --remove libogg0:i386
sudo dpkg --remove libonline-accounts-client1:amd64
sudo dpkg --remove libopenal-data
sudo dpkg --remove libopenal1:amd64
sudo dpkg --remove libopenal1:i386
sudo dpkg --remove libopencc1:amd64
sudo dpkg --remove libopenexr6:amd64
sudo dpkg --remove libopenobex1
sudo dpkg --remove libopenvg1-mesa-lts-utopic:amd64
sudo dpkg --remove liborc-0.4-0:amd64
sudo dpkg --remove liborc-0.4-0:i386
sudo dpkg --remove liborcus-0.6-0
sudo dpkg --remove liboxideqt-qmlplugin:amd64
sudo dpkg --remove liboxideqtcore0:amd64
sudo dpkg --remove liboxideqtquick0:amd64
sudo dpkg --remove libp11-kit-gnome-keyring:amd64
sudo dpkg --remove libp11-kit-gnome-keyring:i386
sudo dpkg --remove libp11-kit0:amd64
sudo dpkg --remove libp11-kit0:i386
sudo dpkg --remove libpackagekit-glib2-16:amd64
sudo dpkg --remove libpam-cap:amd64
sudo dpkg --remove libpam-gnome-keyring:amd64
sudo dpkg --remove libpam-modules:amd64
sudo dpkg --remove libpam-systemd:amd64
sudo dpkg --remove libpam-winbind:amd64
sudo dpkg --remove libpam0g:amd64
sudo dpkg --remove libpanel-applet-4-0
sudo dpkg --remove libpango-1.0-0:amd64
sudo dpkg --remove libpango-1.0-0:i386
sudo dpkg --remove libpango1.0-0:amd64
sudo dpkg --remove libpango1.0-0:i386
sudo dpkg --remove libpangocairo-1.0-0:amd64
sudo dpkg --remove libpangocairo-1.0-0:i386
sudo dpkg --remove libpangoft2-1.0-0:amd64
sudo dpkg --remove libpangoft2-1.0-0:i386
sudo dpkg --remove libpangomm-1.4-1:amd64
sudo dpkg --remove libpangox-1.0-0:amd64
sudo dpkg --remove libpangox-1.0-0:i386
sudo dpkg --remove libpangoxft-1.0-0:amd64
sudo dpkg --remove libpangoxft-1.0-0:i386
sudo dpkg --remove libpaper-utils
sudo dpkg --remove libpaper1:amd64
sudo dpkg --remove libparse-debianchangelog-perl
sudo dpkg --remove libparted0debian1:amd64
sudo dpkg --remove libpcap0.8:amd64
sudo dpkg --remove libpcap0.8:i386
sudo dpkg --remove libpci3:amd64
sudo dpkg --remove libpciaccess0:amd64
sudo dpkg --remove libpciaccess0:i386
sudo dpkg --remove libpcre3:amd64
sudo dpkg --remove libpcre3:i386
sudo dpkg --remove libpcsclite1:amd64
sudo dpkg --remove libpeas-1.0-0
sudo dpkg --remove libpeas-common
sudo dpkg --remove libperl5.18
sudo dpkg --remove libperlio-gzip-perl
sudo dpkg --remove libpgm-5.1-0:amd64
sudo dpkg --remove libpipeline1:amd64
sudo dpkg --remove libpixman-1-0:amd64
sudo dpkg --remove libpixman-1-0:i386
sudo dpkg --remove libplist1:amd64
sudo dpkg --remove libplymouth2:amd64
sudo dpkg --remove libpng12-0:amd64
sudo dpkg --remove libpng12-0:i386
sudo dpkg --remove libpocketsphinx1
sudo dpkg --remove libpolkit-agent-1-0:amd64
sudo dpkg --remove libpolkit-backend-1-0:amd64
sudo dpkg --remove libpolkit-gobject-1-0:amd64
sudo dpkg --remove libpoppler-glib8:amd64
sudo dpkg --remove libpoppler44:amd64
sudo dpkg --remove libpopt0:amd64
sudo dpkg --remove libportaudio2:amd64
sudo dpkg --remove libprocess-cpp1:amd64
sudo dpkg --remove libprocps3:amd64
sudo dpkg --remove libprotobuf8:amd64
sudo dpkg --remove libproxy1:amd64
sudo dpkg --remove libproxy1-plugin-gsettings:amd64
sudo dpkg --remove libproxy1-plugin-networkmanager:amd64
sudo dpkg --remove libpulse-mainloop-glib0:amd64
sudo dpkg --remove libpulse0:amd64
sudo dpkg --remove libpulse0:i386
sudo dpkg --remove libpulsedsp:amd64
sudo dpkg --remove libpurple-bin
sudo dpkg --remove libpurple0
sudo dpkg --remove libpwquality-common
sudo dpkg --remove libpwquality1:amd64
sudo dpkg --remove libpython-stdlib:amd64
sudo dpkg --remove libpython2.7:amd64
sudo dpkg --remove libpython2.7-minimal:amd64
sudo dpkg --remove libpython2.7-stdlib:amd64
sudo dpkg --remove libpython3-stdlib:amd64
sudo dpkg --remove libpython3.4:amd64
sudo dpkg --remove libpython3.4-minimal:amd64
sudo dpkg --remove libpython3.4-stdlib:amd64
sudo dpkg --remove libpyzy-1.0-0
sudo dpkg --remove libqdjango-db0:amd64
sudo dpkg --remove libqgsttools-p1:amd64
sudo dpkg --remove libqmenumodel0
sudo dpkg --remove libqmi-glib0:amd64
sudo dpkg --remove libqpdf13:amd64
sudo dpkg --remove libqt4-dbus:amd64
sudo dpkg --remove libqt4-declarative:amd64
sudo dpkg --remove libqt4-designer:amd64
sudo dpkg --remove libqt4-help:amd64
sudo dpkg --remove libqt4-network:amd64
sudo dpkg --remove libqt4-opengl:amd64
sudo dpkg --remove libqt4-script:amd64
sudo dpkg --remove libqt4-scripttools:amd64
sudo dpkg --remove libqt4-sql:amd64
sudo dpkg --remove libqt4-sql-sqlite:amd64
sudo dpkg --remove libqt4-svg:amd64
sudo dpkg --remove libqt4-test:amd64
sudo dpkg --remove libqt4-xml:amd64
sudo dpkg --remove libqt4-xmlpatterns:amd64
sudo dpkg --remove libqt5core5a:amd64
sudo dpkg --remove libqt5dbus5:amd64
sudo dpkg --remove libqt5feedback5:amd64
sudo dpkg --remove libqt5gui5:amd64
sudo dpkg --remove libqt5multimedia5:amd64
sudo dpkg --remove libqt5multimedia5-plugins:amd64
sudo dpkg --remove libqt5multimediaquick-p5:amd64
sudo dpkg --remove libqt5multimediawidgets5:amd64
sudo dpkg --remove libqt5network5:amd64
sudo dpkg --remove libqt5opengl5:amd64
sudo dpkg --remove libqt5organizer5:amd64
sudo dpkg --remove libqt5positioning5:amd64
sudo dpkg --remove libqt5printsupport5:amd64
sudo dpkg --remove libqt5qml-graphicaleffects:amd64
sudo dpkg --remove libqt5qml5:amd64
sudo dpkg --remove libqt5quick5:amd64
sudo dpkg --remove libqt5sensors5:amd64
sudo dpkg --remove libqt5sql5:amd64
sudo dpkg --remove libqt5sql5-sqlite:amd64
sudo dpkg --remove libqt5svg5:amd64
sudo dpkg --remove libqt5systeminfo5:amd64
sudo dpkg --remove libqt5test5:amd64
sudo dpkg --remove libqt5webkit5:amd64
sudo dpkg --remove libqt5webkit5-qmlwebkitplugin:amd64
sudo dpkg --remove libqt5widgets5:amd64
sudo dpkg --remove libqt5xml5:amd64
sudo dpkg --remove libqt5xmlpatterns5:amd64
sudo dpkg --remove libqtassistantclient4:amd64
sudo dpkg --remove libqtcore4:amd64
sudo dpkg --remove libqtdbus4:amd64
sudo dpkg --remove libqtgui4:amd64
sudo dpkg --remove libqtwebkit4:amd64
sudo dpkg --remove libquadmath0:amd64
sudo dpkg --remove libraptor2-0:amd64
sudo dpkg --remove librasqal3:amd64
sudo dpkg --remove libraw1394-11:amd64
sudo dpkg --remove libraw9:amd64
sudo dpkg --remove librdf0:amd64
sudo dpkg --remove libreadline5:amd64
sudo dpkg --remove libreadline6:amd64
sudo dpkg --remove librecad
sudo dpkg --remove librecad-data
sudo dpkg --remove libreoffice-avmedia-backend-gstreamer
sudo dpkg --remove libreoffice-base-core
sudo dpkg --remove libreoffice-calc
sudo dpkg --remove libreoffice-common
sudo dpkg --remove libreoffice-core
sudo dpkg --remove libreoffice-draw
sudo dpkg --remove libreoffice-gnome
sudo dpkg --remove libreoffice-gtk
sudo dpkg --remove libreoffice-help-en-us
sudo dpkg --remove libreoffice-impress
sudo dpkg --remove libreoffice-math
sudo dpkg --remove libreoffice-ogltrans
sudo dpkg --remove libreoffice-pdfimport
sudo dpkg --remove libreoffice-presentation-minimizer
sudo dpkg --remove libreoffice-style-human
sudo dpkg --remove libreoffice-writer
sudo dpkg --remove librest-0.7-0:amd64
sudo dpkg --remove librhythmbox-core8
sudo dpkg --remove libroken18-heimdal:amd64
sudo dpkg --remove libroken18-heimdal:i386
sudo dpkg --remove librsvg2-2:amd64
sudo dpkg --remove librsvg2-common:amd64
sudo dpkg --remove librsync1:amd64
sudo dpkg --remove librtmp0:amd64
sudo dpkg --remove librtmp0:i386
sudo dpkg --remove libsamplerate0:amd64
sudo dpkg --remove libsamplerate0:i386
sudo dpkg --remove libsane:amd64
sudo dpkg --remove libsane:i386
sudo dpkg --remove libsane-common
sudo dpkg --remove libsane-hpaio
sudo dpkg --remove libsasl2-2:amd64
sudo dpkg --remove libsasl2-2:i386
sudo dpkg --remove libsasl2-modules:amd64
sudo dpkg --remove libsasl2-modules:i386
sudo dpkg --remove libsasl2-modules-db:amd64
sudo dpkg --remove libsasl2-modules-db:i386
sudo dpkg --remove libsbc1:amd64
sudo dpkg --remove libsecret-1-0:amd64
sudo dpkg --remove libsecret-common
sudo dpkg --remove libselinux1:amd64
sudo dpkg --remove libselinux1:i386
sudo dpkg --remove libsemanage1:amd64
sudo dpkg --remove libsensors4:amd64
sudo dpkg --remove libsepol1:amd64
sudo dpkg --remove libsgutils2-2
sudo dpkg --remove libshout3:amd64
sudo dpkg --remove libsigc++-2.0-0c2a:amd64
sudo dpkg --remove libsignon-extension1
sudo dpkg --remove libsignon-glib1
sudo dpkg --remove libsignon-plugins-common1
sudo dpkg --remove libsignon-qt5-1
sudo dpkg --remove libsigsegv2:amd64
sudo dpkg --remove libslang2:amd64
sudo dpkg --remove libsm6:amd64
sudo dpkg --remove libsm6:i386
sudo dpkg --remove libsmbclient:amd64
sudo dpkg --remove libsndfile1:amd64
sudo dpkg --remove libsndfile1:i386
sudo dpkg --remove libsnmp-base
sudo dpkg --remove libsnmp30:amd64
sudo dpkg --remove libsocket6-perl
sudo dpkg --remove libsonic0:amd64
sudo dpkg --remove libsoup-gnome2.4-1:amd64
sudo dpkg --remove libsoup2.4-1:amd64
sudo dpkg --remove libspectre1:amd64
sudo dpkg --remove libspeechd2:amd64
sudo dpkg --remove libspeex1:amd64
sudo dpkg --remove libspeexdsp1:amd64
sudo dpkg --remove libspeexdsp1:i386
sudo dpkg --remove libsphinxbase1
sudo dpkg --remove libsqlite3-0:amd64
sudo dpkg --remove libsqlite3-0:i386
sudo dpkg --remove libss2:amd64
sudo dpkg --remove libssh-4:amd64
sudo dpkg --remove libssl-dev:amd64
sudo dpkg --remove libssl-doc
sudo dpkg --remove libssl1.0.0:amd64
sudo dpkg --remove libssl1.0.0:i386
sudo dpkg --remove libstartup-notification0:amd64
sudo dpkg --remove libstdc++-4.8-dev:amd64
sudo dpkg --remove libstdc++6:amd64
sudo dpkg --remove libstdc++6:i386
sudo dpkg --remove libsub-identify-perl
sudo dpkg --remove libsub-name-perl
sudo dpkg --remove libsystemd-daemon0:amd64
sudo dpkg --remove libsystemd-journal0:amd64
sudo dpkg --remove libsystemd-login0:amd64
sudo dpkg --remove libsystemsettings1:amd64
sudo dpkg --remove libt1-5
sudo dpkg --remove libtag1-vanilla:amd64
sudo dpkg --remove libtag1c2a:amd64
sudo dpkg --remove libtalloc2:amd64
sudo dpkg --remove libtasn1-6:amd64
sudo dpkg --remove libtasn1-6:i386
sudo dpkg --remove libtcl8.6:amd64
sudo dpkg --remove libtdb1:amd64
sudo dpkg --remove libtelepathy-farstream3:amd64
sudo dpkg --remove libtelepathy-glib0:amd64
sudo dpkg --remove libtelepathy-logger3:amd64
sudo dpkg --remove libtevent0:amd64
sudo dpkg --remove libtext-levenshtein-perl
sudo dpkg --remove libthai0:amd64
sudo dpkg --remove libthai0:i386
sudo dpkg --remove libtheora0:amd64
sudo dpkg --remove libthumbnailer0:amd64
sudo dpkg --remove libtiff5:amd64
sudo dpkg --remove libtiff5:i386
sudo dpkg --remove libtimezonemap1
sudo dpkg --remove libtinfo5:amd64
sudo dpkg --remove libtinfo5:i386
sudo dpkg --remove libtk8.6:amd64
sudo dpkg --remove libtotem-plparser18
sudo dpkg --remove libtotem0
sudo dpkg --remove libtsan0:amd64
sudo dpkg --remove libtxc-dxtn-s2tc0:amd64
sudo dpkg --remove libtxc-dxtn-s2tc0:i386
sudo dpkg --remove libubuntu-application-api-mirserver1:amd64
sudo dpkg --remove libubuntu-application-api1:amd64
sudo dpkg --remove libubuntu-download-manager-client0
sudo dpkg --remove libubuntu-download-manager-common0
sudo dpkg --remove libubuntu-download-manager-priv0
sudo dpkg --remove libubuntu-location-service0:amd64
sudo dpkg --remove libubuntu-platform-hardware-api1:amd64
sudo dpkg --remove libubuntuoneauth-2.0-0:amd64
sudo dpkg --remove libudev1:amd64
sudo dpkg --remove libudev1:i386
sudo dpkg --remove libudisks2-0:amd64
sudo dpkg --remove libufe-xidgetter0
sudo dpkg --remove libunistring0:amd64
sudo dpkg --remove libunity-action-qt1:amd64
sudo dpkg --remove libunity-api0:amd64
sudo dpkg --remove libunity-control-center1
sudo dpkg --remove libunity-core-6.0-9
sudo dpkg --remove libunity-gtk2-parser0:amd64
sudo dpkg --remove libunity-gtk3-parser0:amd64
sudo dpkg --remove libunity-mir1:amd64
sudo dpkg --remove libunity-misc4
sudo dpkg --remove libunity-protocol-private0:amd64
sudo dpkg --remove libunity-scopes-json-def-desktop
sudo dpkg --remove libunity-scopes1:amd64
sudo dpkg --remove libunity-webapps0
sudo dpkg --remove libunity9:amd64
sudo dpkg --remove libunityvoice1:amd64
sudo dpkg --remove libunwind8
sudo dpkg --remove libupower-glib1:amd64
sudo dpkg --remove libupstart-app-launch2:amd64
sudo dpkg --remove libupstart1:amd64
sudo dpkg --remove liburcu1
sudo dpkg --remove liburi-perl
sudo dpkg --remove liburl-dispatcher1:amd64
sudo dpkg --remove libusb-0.1-4:amd64
sudo dpkg --remove libusb-1.0-0:amd64
sudo dpkg --remove libusb-1.0-0:i386
sudo dpkg --remove libusbmuxd2
sudo dpkg --remove libusermetricsoutput1:amd64
sudo dpkg --remove libustr-1.0-1:amd64
sudo dpkg --remove libutempter0
sudo dpkg --remove libuuid-perl
sudo dpkg --remove libuuid1:amd64
sudo dpkg --remove libuuid1:i386
sudo dpkg --remove libv4l-0:amd64
sudo dpkg --remove libv4l-0:i386
sudo dpkg --remove libv4lconvert0:amd64
sudo dpkg --remove libv4lconvert0:i386
sudo dpkg --remove libv8-3.14-dev
sudo dpkg --remove libv8-3.14.5
sudo dpkg --remove libvisio-0.0-0
sudo dpkg --remove libvisual-0.4-0:amd64
sudo dpkg --remove libvisual-0.4-plugins:amd64
sudo dpkg --remove libvncserver0:amd64
sudo dpkg --remove libvorbis0a:amd64
sudo dpkg --remove libvorbis0a:i386
sudo dpkg --remove libvorbisenc2:amd64
sudo dpkg --remove libvorbisenc2:i386
sudo dpkg --remove libvorbisfile3:amd64
sudo dpkg --remove libvpx1:amd64
sudo dpkg --remove libvpx1:i386
sudo dpkg --remove libvte-2.90-9
sudo dpkg --remove libvte-2.90-common
sudo dpkg --remove libwacom-common
sudo dpkg --remove libwacom2:amd64
sudo dpkg --remove libwavpack1:amd64
sudo dpkg --remove libwayland-client0:amd64
sudo dpkg --remove libwayland-client0:i386
sudo dpkg --remove libwayland-cursor0:amd64
sudo dpkg --remove libwayland-cursor0:i386
sudo dpkg --remove libwayland-egl1-mesa-lts-utopic:amd64
sudo dpkg --remove libwayland-server0:amd64
sudo dpkg --remove libwbclient0:amd64
sudo dpkg --remove libwebkitgtk-3.0-0:amd64
sudo dpkg --remove libwebkitgtk-3.0-common
sudo dpkg --remove libwebp5:amd64
sudo dpkg --remove libwebpmux1:amd64
sudo dpkg --remove libwhoopsie-preferences0
sudo dpkg --remove libwhoopsie0
sudo dpkg --remove libwind0-heimdal:amd64
sudo dpkg --remove libwind0-heimdal:i386
sudo dpkg --remove libwmf-bin
sudo dpkg --remove libwmf0.2-7:amd64
sudo dpkg --remove libwmf0.2-7-gtk
sudo dpkg --remove libwnck-3-0:amd64
sudo dpkg --remove libwnck-3-common
sudo dpkg --remove libwnck-common
sudo dpkg --remove libwnck22
sudo dpkg --remove libwpd-0.9-9
sudo dpkg --remove libwpg-0.2-2
sudo dpkg --remove libwps-0.2-2
sudo dpkg --remove libwrap0:amd64
sudo dpkg --remove libwrap0:i386
sudo dpkg --remove libwww-perl
sudo dpkg --remove libwww-robotrules-perl
sudo dpkg --remove libx11-6:amd64
sudo dpkg --remove libx11-6:i386
sudo dpkg --remove libx11-xcb1:amd64
sudo dpkg --remove libx11-xcb1:i386
sudo dpkg --remove libx86-1:amd64
sudo dpkg --remove libxapian22
sudo dpkg --remove libxatracker2-lts-utopic:amd64
sudo dpkg --remove libxau6:amd64
sudo dpkg --remove libxau6:i386
sudo dpkg --remove libxaw7:amd64
sudo dpkg --remove libxcb-dri2-0:amd64
sudo dpkg --remove libxcb-dri2-0:i386
sudo dpkg --remove libxcb-dri3-0:amd64
sudo dpkg --remove libxcb-dri3-0:i386
sudo dpkg --remove libxcb-glx0:amd64
sudo dpkg --remove libxcb-glx0:i386
sudo dpkg --remove libxcb-icccm4:amd64
sudo dpkg --remove libxcb-image0:amd64
sudo dpkg --remove libxcb-keysyms1:amd64
sudo dpkg --remove libxcb-present0:amd64
sudo dpkg --remove libxcb-present0:i386
sudo dpkg --remove libxcb-randr0:amd64
sudo dpkg --remove libxcb-render-util0:amd64
sudo dpkg --remove libxcb-render0:amd64
sudo dpkg --remove libxcb-render0:i386
sudo dpkg --remove libxcb-shape0:amd64
sudo dpkg --remove libxcb-shm0:amd64
sudo dpkg --remove libxcb-shm0:i386
sudo dpkg --remove libxcb-sync1:amd64
sudo dpkg --remove libxcb-sync1:i386
sudo dpkg --remove libxcb-util0:amd64
sudo dpkg --remove libxcb-xfixes0:amd64
sudo dpkg --remove libxcb-xkb1:amd64
sudo dpkg --remove libxcb1:amd64
sudo dpkg --remove libxcb1:i386
sudo dpkg --remove libxcomposite1:amd64
sudo dpkg --remove libxcomposite1:i386
sudo dpkg --remove libxcursor1:amd64
sudo dpkg --remove libxcursor1:i386
sudo dpkg --remove libxdamage1:amd64
sudo dpkg --remove libxdamage1:i386
sudo dpkg --remove libxdmcp6:amd64
sudo dpkg --remove libxdmcp6:i386
sudo dpkg --remove libxext6:amd64
sudo dpkg --remove libxext6:i386
sudo dpkg --remove libxfixes3:amd64
sudo dpkg --remove libxfixes3:i386
sudo dpkg --remove libxfont1:amd64
sudo dpkg --remove libxft2:amd64
sudo dpkg --remove libxft2:i386
sudo dpkg --remove libxi6:amd64
sudo dpkg --remove libxi6:i386
sudo dpkg --remove libxinerama1:amd64
sudo dpkg --remove libxinerama1:i386
sudo dpkg --remove libxkbcommon-x11-0:amd64
sudo dpkg --remove libxkbcommon0:amd64
sudo dpkg --remove libxkbcommon0:i386
sudo dpkg --remove libxkbfile1:amd64
sudo dpkg --remove libxklavier16
sudo dpkg --remove libxml2:amd64
sudo dpkg --remove libxml2:i386
sudo dpkg --remove libxmu6:amd64
sudo dpkg --remove libxmuu1:amd64
sudo dpkg --remove libxp6:amd64
sudo dpkg --remove libxpm4:amd64
sudo dpkg --remove libxpm4:i386
sudo dpkg --remove libxrandr2:amd64
sudo dpkg --remove libxrandr2:i386
sudo dpkg --remove libxrender1:amd64
sudo dpkg --remove libxrender1:i386
sudo dpkg --remove libxres1:amd64
sudo dpkg --remove libxshmfence1:amd64
sudo dpkg --remove libxshmfence1:i386
sudo dpkg --remove libxslt1.1:amd64
sudo dpkg --remove libxslt1.1:i386
sudo dpkg --remove libxss1:amd64
sudo dpkg --remove libxss1:i386
sudo dpkg --remove libxt6:amd64
sudo dpkg --remove libxt6:i386
sudo dpkg --remove libxtables10
sudo dpkg --remove libxtst6:amd64
sudo dpkg --remove libxtst6:i386
sudo dpkg --remove libxv1:amd64
sudo dpkg --remove libxvmc1:amd64
sudo dpkg --remove libxxf86dga1:amd64
sudo dpkg --remove libxxf86vm1:amd64
sudo dpkg --remove libxxf86vm1:i386
sudo dpkg --remove libyajl2:amd64
sudo dpkg --remove libyaml-tiny-perl
sudo dpkg --remove libyelp0
sudo dpkg --remove libzeitgeist-1.0-1
sudo dpkg --remove libzeitgeist-2.0-0:amd64
sudo dpkg --remove libzephyr4:amd64
sudo dpkg --remove libzmq3:amd64
sudo dpkg --remove libzmqpp3:amd64
sudo dpkg --remove light-themes
sudo dpkg --remove lightdm
sudo dpkg --remove lintian
sudo dpkg --remove linux-generic-lts-utopic
sudo dpkg --remove linux-headers-3.16.0-30
sudo dpkg --remove linux-headers-3.16.0-30-generic
sudo dpkg --remove linux-headers-3.16.0-49
sudo dpkg --remove linux-headers-3.16.0-49-generic
sudo dpkg --remove linux-headers-3.16.0-51
sudo dpkg --remove linux-headers-3.16.0-51-generic
sudo dpkg --remove linux-headers-generic-lts-utopic
sudo dpkg --remove linux-image-3.16.0-30-generic
sudo dpkg --remove linux-image-3.16.0-49-generic
sudo dpkg --remove linux-image-3.16.0-51-generic
sudo dpkg --remove linux-image-extra-3.16.0-30-generic
sudo dpkg --remove linux-image-extra-3.16.0-49-generic
sudo dpkg --remove linux-image-extra-3.16.0-51-generic
sudo dpkg --remove linux-image-generic-lts-utopic
sudo dpkg --remove linux-libc-dev:amd64
sudo dpkg --remove linux-signed-generic-lts-utopic
sudo dpkg --remove linux-signed-image-3.16.0-30-generic
sudo dpkg --remove linux-signed-image-3.16.0-49-generic
sudo dpkg --remove linux-signed-image-3.16.0-51-generic
sudo dpkg --remove linux-signed-image-generic-lts-utopic
sudo dpkg --remove linux-sound-base
sudo dpkg --remove locales
sudo dpkg --remove lockfile-progs
sudo dpkg --remove logrotate
sudo dpkg --remove lp-solve
sudo dpkg --remove lsb-release
sudo dpkg --remove lshw
sudo dpkg --remove lsof
sudo dpkg --remove ltrace
sudo dpkg --remove macfanctld
sudo dpkg --remove make
sudo dpkg --remove man-db
sudo dpkg --remove manpages
sudo dpkg --remove manpages-dev
sudo dpkg --remove mawk
sudo dpkg --remove mcp-account-manager-uoa
sudo dpkg --remove media-player-info
sudo dpkg --remove mediascanner2.0
sudo dpkg --remove memtest86+
sudo dpkg --remove metacity-common
sudo dpkg --remove mlocate
sudo dpkg --remove mobile-broadband-provider-info
sudo dpkg --remove mongodb-org
sudo dpkg --remove mongodb-org-mongos
sudo dpkg --remove mongodb-org-server
sudo dpkg --remove mongodb-org-shell
sudo dpkg --remove mongodb-org-tools
sudo dpkg --remove mousetweaks
sudo dpkg --remove mscompress
sudo dpkg --remove mtools
sudo dpkg --remove mtr-tiny
sudo dpkg --remove nano
sudo dpkg --remove nautilus
sudo dpkg --remove nautilus-data
sudo dpkg --remove nautilus-sendto
sudo dpkg --remove nautilus-sendto-empathy
sudo dpkg --remove nautilus-share
sudo dpkg --remove netpbm
sudo dpkg --remove network-manager
sudo dpkg --remove network-manager-gnome
sudo dpkg --remove network-manager-pptp
sudo dpkg --remove network-manager-pptp-gnome
sudo dpkg --remove node-abbrev
sudo dpkg --remove node-ansi
sudo dpkg --remove node-archy
sudo dpkg --remove node-async
sudo dpkg --remove node-block-stream
sudo dpkg --remove node-combined-stream
sudo dpkg --remove node-cookie-jar
sudo dpkg --remove node-delayed-stream
sudo dpkg --remove node-forever-agent
sudo dpkg --remove node-form-data
sudo dpkg --remove node-fstream
sudo dpkg --remove node-fstream-ignore
sudo dpkg --remove node-github-url-from-git
sudo dpkg --remove node-glob
sudo dpkg --remove node-graceful-fs
sudo dpkg --remove node-gyp
sudo dpkg --remove node-inherits
sudo dpkg --remove node-ini
sudo dpkg --remove node-json-stringify-safe
sudo dpkg --remove node-lockfile
sudo dpkg --remove node-lru-cache
sudo dpkg --remove node-mime
sudo dpkg --remove node-minimatch
sudo dpkg --remove node-mkdirp
sudo dpkg --remove node-mute-stream
sudo dpkg --remove node-node-uuid
sudo dpkg --remove node-nopt
sudo dpkg --remove node-normalize-package-data
sudo dpkg --remove node-npmlog
sudo dpkg --remove node-once
sudo dpkg --remove node-osenv
sudo dpkg --remove node-qs
sudo dpkg --remove node-read
sudo dpkg --remove node-read-package-json
sudo dpkg --remove node-request
sudo dpkg --remove node-retry
sudo dpkg --remove node-rimraf
sudo dpkg --remove node-semver
sudo dpkg --remove node-sha
sudo dpkg --remove node-sigmund
sudo dpkg --remove node-slide
sudo dpkg --remove node-tar
sudo dpkg --remove node-tunnel-agent
sudo dpkg --remove node-which
sudo dpkg --remove nodejs
sudo dpkg --remove nodejs-dev
sudo dpkg --remove notify-osd
sudo dpkg --remove notify-osd-icons
sudo dpkg --remove npm
sudo dpkg --remove ntfs-3g
sudo dpkg --remove nux-tools
sudo dpkg --remove obex-data-server
sudo dpkg --remove obexd-client
sudo dpkg --remove ocl-icd-libopencl1:amd64
sudo dpkg --remove ocl-icd-libopencl1:i386
sudo dpkg --remove odbcinst
sudo dpkg --remove odbcinst1debian2:amd64
sudo dpkg --remove ofono
sudo dpkg --remove onboard
sudo dpkg --remove onboard-data
sudo dpkg --remove oneconf
sudo dpkg --remove oneconf-common
sudo dpkg --remove openprinting-ppds
sudo dpkg --remove os-prober
sudo dpkg --remove overlay-scrollbar
sudo dpkg --remove overlay-scrollbar-gtk2:amd64
sudo dpkg --remove overlay-scrollbar-gtk3:amd64
sudo dpkg --remove oxideqt-codecs:amd64
sudo dpkg --remove p11-kit
sudo dpkg --remove p11-kit-modules:amd64
sudo dpkg --remove p11-kit-modules:i386
sudo dpkg --remove p7zip
sudo dpkg --remove packagekit-tools
sudo dpkg --remove parted
sudo dpkg --remove patch
sudo dpkg --remove patchutils
sudo dpkg --remove pciutils
sudo dpkg --remove pcmciautils
sudo dpkg --remove perlmagick
sudo dpkg --remove pkg-config
sudo dpkg --remove plainbox-provider-checkbox
sudo dpkg --remove plainbox-provider-resource-generic
sudo dpkg --remove plainbox-secure-policy
sudo dpkg --remove plymouth-label
sudo dpkg --remove plymouth-theme-ubuntu-logo
sudo dpkg --remove plymouth-theme-ubuntu-text
sudo dpkg --remove pm-utils
sudo dpkg --remove policykit-1
sudo dpkg --remove policykit-1-gnome
sudo dpkg --remove policykit-desktop-privileges
sudo dpkg --remove poppler-data
sudo dpkg --remove poppler-utils
sudo dpkg --remove popularity-contest
sudo dpkg --remove powerd
sudo dpkg --remove powermgmt-base
sudo dpkg --remove ppp
sudo dpkg --remove pppconfig
sudo dpkg --remove pppoeconf
sudo dpkg --remove pptp-linux
sudo dpkg --remove printer-driver-c2esp
sudo dpkg --remove printer-driver-foo2zjs
sudo dpkg --remove printer-driver-foo2zjs-common
sudo dpkg --remove printer-driver-gutenprint
sudo dpkg --remove printer-driver-hpcups
sudo dpkg --remove printer-driver-min12xxw
sudo dpkg --remove printer-driver-pnm2ppa
sudo dpkg --remove printer-driver-postscript-hp
sudo dpkg --remove printer-driver-ptouch
sudo dpkg --remove printer-driver-pxljr
sudo dpkg --remove printer-driver-sag-gdi
sudo dpkg --remove printer-driver-splix
sudo dpkg --remove psmisc
sudo dpkg --remove pulseaudio
sudo dpkg --remove pulseaudio-module-bluetooth
sudo dpkg --remove pulseaudio-module-x11
sudo dpkg --remove pulseaudio-utils
sudo dpkg --remove putty
sudo dpkg --remove putty-tools
sudo dpkg --remove python-apt
sudo dpkg --remove python-apt-common
sudo dpkg --remove python-aptdaemon
sudo dpkg --remove python-aptdaemon.gtk3widgets
sudo dpkg --remove python-cairo
sudo dpkg --remove python-commandnotfound
sudo dpkg --remove python-crypto
sudo dpkg --remove python-cups
sudo dpkg --remove python-cupshelpers
sudo dpkg --remove python-dbus
sudo dpkg --remove python-dbus-dev
sudo dpkg --remove python-debian
sudo dpkg --remove python-debtagshw
sudo dpkg --remove python-defer
sudo dpkg --remove python-dirspec
sudo dpkg --remove python-dnspython
sudo dpkg --remove python-gconf
sudo dpkg --remove python-gdbm
sudo dpkg --remove python-gi
sudo dpkg --remove python-gi-cairo
sudo dpkg --remove python-glade2
sudo dpkg --remove python-gnomekeyring
sudo dpkg --remove python-gobject
sudo dpkg --remove python-gobject-2
sudo dpkg --remove python-gtk2
sudo dpkg --remove python-httplib2
sudo dpkg --remove python-ibus
sudo dpkg --remove python-imaging
sudo dpkg --remove python-ldb
sudo dpkg --remove python-libxml2
sudo dpkg --remove python-lockfile
sudo dpkg --remove python-lxml
sudo dpkg --remove python-notify
sudo dpkg --remove python-ntdb
sudo dpkg --remove python-oauthlib
sudo dpkg --remove python-oneconf
sudo dpkg --remove python-openssl
sudo dpkg --remove python-pam
sudo dpkg --remove python-pexpect
sudo dpkg --remove python-pil
sudo dpkg --remove python-piston-mini-client
sudo dpkg --remove python-qt4
sudo dpkg --remove python-qt4-dbus
sudo dpkg --remove python-renderpm
sudo dpkg --remove python-reportlab
sudo dpkg --remove python-reportlab-accel
sudo dpkg --remove python-samba
sudo dpkg --remove python-serial
sudo dpkg --remove python-sip
sudo dpkg --remove python-smbc
sudo dpkg --remove python-talloc
sudo dpkg --remove python-tdb
sudo dpkg --remove python-twisted-bin
sudo dpkg --remove python-twisted-core
sudo dpkg --remove python-twisted-web
sudo dpkg --remove python-ubuntu-sso-client
sudo dpkg --remove python-virtualenv
sudo dpkg --remove python-wicd
sudo dpkg --remove python-xapian
sudo dpkg --remove python-xdg
sudo dpkg --remove python-zeitgeist
sudo dpkg --remove python-zope.interface
sudo dpkg --remove python3-apparmor
sudo dpkg --remove python3-apparmor-click
sudo dpkg --remove python3-apport
sudo dpkg --remove python3-apt
sudo dpkg --remove python3-aptdaemon
sudo dpkg --remove python3-aptdaemon.gtk3widgets
sudo dpkg --remove python3-aptdaemon.pkcompat
sudo dpkg --remove python3-brlapi
sudo dpkg --remove python3-cairo
sudo dpkg --remove python3-chardet
sudo dpkg --remove python3-checkbox-ng
sudo dpkg --remove python3-checkbox-support
sudo dpkg --remove python3-click
sudo dpkg --remove python3-commandnotfound
sudo dpkg --remove python3-crypto
sudo dpkg --remove python3-dbus
sudo dpkg --remove python3-debian
sudo dpkg --remove python3-defer
sudo dpkg --remove python3-distupgrade
sudo dpkg --remove python3-feedparser
sudo dpkg --remove python3-gdbm:amd64
sudo dpkg --remove python3-gi
sudo dpkg --remove python3-gi-cairo
sudo dpkg --remove python3-gnupg
sudo dpkg --remove python3-httplib2
sudo dpkg --remove python3-libapparmor
sudo dpkg --remove python3-louis
sudo dpkg --remove python3-lxml
sudo dpkg --remove python3-mako
sudo dpkg --remove python3-markupsafe
sudo dpkg --remove python3-oauthlib
sudo dpkg --remove python3-oneconf
sudo dpkg --remove python3-piston-mini-client
sudo dpkg --remove python3-plainbox
sudo dpkg --remove python3-problem-report
sudo dpkg --remove python3-pyatspi
sudo dpkg --remove python3-pycurl
sudo dpkg --remove python3-pyparsing
sudo dpkg --remove python3-requests
sudo dpkg --remove python3-six
sudo dpkg --remove python3-software-properties
sudo dpkg --remove python3-speechd
sudo dpkg --remove python3-uno
sudo dpkg --remove python3-update-manager
sudo dpkg --remove python3-urllib3
sudo dpkg --remove python3-xdg
sudo dpkg --remove python3-xkit
sudo dpkg --remove qdbus
sudo dpkg --remove qemu-user-static
sudo dpkg --remove qmenumodel-qml
sudo dpkg --remove qpdf
sudo dpkg --remove qt-at-spi:amd64
sudo dpkg --remove qtchooser
sudo dpkg --remove qtcore4-l10n
sudo dpkg --remove qtdeclarative5-accounts-plugin
sudo dpkg --remove qtdeclarative5-dee-plugin
sudo dpkg --remove qtdeclarative5-dialogs-plugin:amd64
sudo dpkg --remove qtdeclarative5-folderlistmodel-plugin:amd64
sudo dpkg --remove qtdeclarative5-gsettings1.0
sudo dpkg --remove qtdeclarative5-localstorage-plugin:amd64
sudo dpkg --remove qtdeclarative5-privatewidgets-plugin:amd64
sudo dpkg --remove qtdeclarative5-qtfeedback-plugin:amd64
sudo dpkg --remove qtdeclarative5-qtmultimedia-plugin:amd64
sudo dpkg --remove qtdeclarative5-qtquick2-plugin:amd64
sudo dpkg --remove qtdeclarative5-systeminfo-plugin:amd64
sudo dpkg --remove qtdeclarative5-ubuntu-content0.1
sudo dpkg --remove qtdeclarative5-ubuntu-settings-components:amd64
sudo dpkg --remove qtdeclarative5-ubuntu-settings-components-assets
sudo dpkg --remove qtdeclarative5-ubuntu-thumbnailer0.1:amd64
sudo dpkg --remove qtdeclarative5-ubuntu-ui-extras-browser-plugin:amd64
sudo dpkg --remove qtdeclarative5-ubuntu-ui-extras-browser-plugin-assets
sudo dpkg --remove qtdeclarative5-ubuntu-ui-toolkit-plugin:amd64
sudo dpkg --remove qtdeclarative5-ubuntuone1.0:amd64
sudo dpkg --remove qtdeclarative5-unity-action-plugin:amd64
sudo dpkg --remove qtdeclarative5-unity-notifications-plugin:amd64
sudo dpkg --remove qtdeclarative5-window-plugin:amd64
sudo dpkg --remove qtdeclarative5-xmllistmodel-plugin:amd64
sudo dpkg --remove remmina
sudo dpkg --remove remmina-common
sudo dpkg --remove remmina-plugin-rdp
sudo dpkg --remove remmina-plugin-vnc
sudo dpkg --remove rfkill
sudo dpkg --remove rhythmbox
sudo dpkg --remove rhythmbox-data
sudo dpkg --remove rhythmbox-mozilla
sudo dpkg --remove rhythmbox-plugin-cdrecorder
sudo dpkg --remove rhythmbox-plugin-magnatune
sudo dpkg --remove rhythmbox-plugin-zeitgeist
sudo dpkg --remove rhythmbox-plugins
sudo dpkg --remove rsync
sudo dpkg --remove rtkit
sudo dpkg --remove samba
sudo dpkg --remove samba-common
sudo dpkg --remove samba-common-bin
sudo dpkg --remove samba-dsdb-modules
sudo dpkg --remove samba-libs:amd64
sudo dpkg --remove samba-vfs-modules
sudo dpkg --remove sane-utils
sudo dpkg --remove sbsigntool
sudo dpkg --remove seahorse
sudo dpkg --remove secureboot-db
sudo dpkg --remove session-migration
sudo dpkg --remove sessioninstaller
sudo dpkg --remove sgml-base
sudo dpkg --remove shim
sudo dpkg --remove shim-signed
sudo dpkg --remove shotwell
sudo dpkg --remove shotwell-common
sudo dpkg --remove signon-keyring-extension
sudo dpkg --remove signon-plugin-oauth2
sudo dpkg --remove signon-plugin-password
sudo dpkg --remove signon-ui
sudo dpkg --remove signond
sudo dpkg --remove simple-scan
sudo dpkg --remove smbclient
sudo dpkg --remove sni-qt:amd64
sudo dpkg --remove software-center
sudo dpkg --remove software-center-aptdaemon-plugins
sudo dpkg --remove software-properties-common
sudo dpkg --remove software-properties-gtk
sudo dpkg --remove sound-theme-freedesktop
sudo dpkg --remove speech-dispatcher
sudo dpkg --remove speech-dispatcher-audio-plugins:amd64
sudo dpkg --remove sphinx-voxforge-hmm-en
sudo dpkg --remove sphinx-voxforge-lm-en
sudo dpkg --remove sqlite3
sudo dpkg --remove ssh-askpass-gnome
sudo dpkg --remove ssl-cert
sudo dpkg --remove strace
sudo dpkg --remove sublime-text-installer
sudo dpkg --remove suru-icon-theme
sudo dpkg --remove syslinux
sudo dpkg --remove syslinux-common
sudo dpkg --remove syslinux-legacy
sudo dpkg --remove system-config-printer-common
sudo dpkg --remove system-config-printer-gnome
sudo dpkg --remove system-config-printer-udev
sudo dpkg --remove system-image-common
sudo dpkg --remove system-image-dbus
sudo dpkg --remove systemd-services
sudo dpkg --remove systemd-shim
sudo dpkg --remove t1utils
sudo dpkg --remove tcl
sudo dpkg --remove tcl8.6
sudo dpkg --remove tcpdump
sudo dpkg --remove tdb-tools
sudo dpkg --remove telepathy-gabble
sudo dpkg --remove telepathy-haze
sudo dpkg --remove telepathy-idle
sudo dpkg --remove telepathy-indicator
sudo dpkg --remove telepathy-logger
sudo dpkg --remove telepathy-mission-control-5
sudo dpkg --remove telepathy-salut
sudo dpkg --remove telnet
sudo dpkg --remove thumbnailer-service
sudo dpkg --remove thunderbird
sudo dpkg --remove thunderbird-gnome-support
sudo dpkg --remove time
sudo dpkg --remove tk
sudo dpkg --remove tk8.6
sudo dpkg --remove toshset
sudo dpkg --remove totem
sudo dpkg --remove totem-common
sudo dpkg --remove totem-mozilla
sudo dpkg --remove totem-plugins
sudo dpkg --remove transfig
sudo dpkg --remove transmission-common
sudo dpkg --remove transmission-gtk
sudo dpkg --remove ttf-indic-fonts-core
sudo dpkg --remove ttf-mscorefonts-installer
sudo dpkg --remove ttf-punjabi-fonts
sudo dpkg --remove ttf-ubuntu-font-family
sudo dpkg --remove ttf-wqy-microhei
sudo dpkg --remove ubuntu-artwork
sudo dpkg --remove ubuntu-desktop
sudo dpkg --remove ubuntu-docs
sudo dpkg --remove ubuntu-download-manager
sudo dpkg --remove ubuntu-drivers-common
sudo dpkg --remove ubuntu-extras-keyring
sudo dpkg --remove ubuntu-keyboard-data
sudo dpkg --remove ubuntu-minimal
sudo dpkg --remove ubuntu-mobile-icons
sudo dpkg --remove ubuntu-mono
sudo dpkg --remove ubuntu-purchase-service:amd64
sudo dpkg --remove ubuntu-release-upgrader-core
sudo dpkg --remove ubuntu-release-upgrader-gtk
sudo dpkg --remove ubuntu-session
sudo dpkg --remove ubuntu-settings
sudo dpkg --remove ubuntu-sounds
sudo dpkg --remove ubuntu-sso-client
sudo dpkg --remove ubuntu-sso-client-qt
sudo dpkg --remove ubuntu-standard
sudo dpkg --remove ubuntu-system-service
sudo dpkg --remove ubuntu-system-settings
sudo dpkg --remove ubuntu-system-settings-online-accounts
sudo dpkg --remove ubuntu-touch-sounds
sudo dpkg --remove ubuntu-ui-toolkit-theme
sudo dpkg --remove ubuntu-wallpapers
sudo dpkg --remove ubuntu-wallpapers-trusty
sudo dpkg --remove ubuntuone-client-data
sudo dpkg --remove ubuntuone-credentials-common
sudo dpkg --remove udisks
sudo dpkg --remove udisks2
sudo dpkg --remove ufw
sudo dpkg --remove unattended-upgrades
sudo dpkg --remove unity
sudo dpkg --remove unity-asset-pool
sudo dpkg --remove unity-control-center
sudo dpkg --remove unity-control-center-signon
sudo dpkg --remove unity-greeter
sudo dpkg --remove unity-gtk-module-common
sudo dpkg --remove unity-gtk2-module:amd64
sudo dpkg --remove unity-gtk3-module:amd64
sudo dpkg --remove unity-lens-applications
sudo dpkg --remove unity-lens-files
sudo dpkg --remove unity-lens-friends
sudo dpkg --remove unity-lens-music
sudo dpkg --remove unity-lens-photos
sudo dpkg --remove unity-lens-video
sudo dpkg --remove unity-plugin-scopes:amd64
sudo dpkg --remove unity-scope-audacious
sudo dpkg --remove unity-scope-calculator
sudo dpkg --remove unity-scope-chromiumbookmarks
sudo dpkg --remove unity-scope-clementine
sudo dpkg --remove unity-scope-click
sudo dpkg --remove unity-scope-colourlovers
sudo dpkg --remove unity-scope-devhelp
sudo dpkg --remove unity-scope-firefoxbookmarks
sudo dpkg --remove unity-scope-gdrive
sudo dpkg --remove unity-scope-gmusicbrowser
sudo dpkg --remove unity-scope-gourmet
sudo dpkg --remove unity-scope-guayadeque
sudo dpkg --remove unity-scope-home
sudo dpkg --remove unity-scope-manpages
sudo dpkg --remove unity-scope-mediascanner2
sudo dpkg --remove unity-scope-musicstores
sudo dpkg --remove unity-scope-musique
sudo dpkg --remove unity-scope-openclipart
sudo dpkg --remove unity-scope-scopes
sudo dpkg --remove unity-scope-texdoc
sudo dpkg --remove unity-scope-tomboy
sudo dpkg --remove unity-scope-video-remote
sudo dpkg --remove unity-scope-virtualbox
sudo dpkg --remove unity-scope-yelp
sudo dpkg --remove unity-scope-zotero
sudo dpkg --remove unity-scopes-master-default
sudo dpkg --remove unity-scopes-runner
sudo dpkg --remove unity-services
sudo dpkg --remove unity-settings-daemon
sudo dpkg --remove unity-voice-service:amd64
sudo dpkg --remove unity-webapps-common
sudo dpkg --remove unity-webapps-qml
sudo dpkg --remove unity-webapps-service
sudo dpkg --remove unity8
sudo dpkg --remove unity8-private:amd64
sudo dpkg --remove unixodbc
sudo dpkg --remove uno-libs3
sudo dpkg --remove unzip
sudo dpkg --remove update-inetd
sudo dpkg --remove update-manager
sudo dpkg --remove update-manager-core
sudo dpkg --remove update-notifier
sudo dpkg --remove update-notifier-common
sudo dpkg --remove upower
sudo dpkg --remove upstart-app-launch
sudo dpkg --remove upstart-app-launch-tools
sudo dpkg --remove ure
sudo dpkg --remove usb-creator-common
sudo dpkg --remove usb-creator-gtk
sudo dpkg --remove usb-modeswitch
sudo dpkg --remove usb-modeswitch-data
sudo dpkg --remove usbmuxd
sudo dpkg --remove usermetricsservice:amd64
sudo dpkg --remove uuid-runtime
sudo dpkg --remove vbetool
sudo dpkg --remove vim
sudo dpkg --remove vim-common
sudo dpkg --remove vim-runtime
sudo dpkg --remove vim-tiny
sudo dpkg --remove vino
sudo dpkg --remove wamerican
sudo dpkg --remove webaccounts-extension-common
sudo dpkg --remove webapp-container
sudo dpkg --remove webbrowser-app
sudo dpkg --remove whiptail
sudo dpkg --remove whoopsie
sudo dpkg --remove whoopsie-preferences
sudo dpkg --remove wicd-daemon
sudo dpkg --remove wicd-gtk
sudo dpkg --remove winbind
sudo dpkg --remove wine-gecko2.21:amd64
sudo dpkg --remove wine-gecko2.21:i386
sudo dpkg --remove wine-gecko2.34:amd64
sudo dpkg --remove wine-gecko2.34:i386
sudo dpkg --remove wine-mono0.0.8
sudo dpkg --remove wine-mono4.5.4
sudo dpkg --remove wine1.7
sudo dpkg --remove wine1.7-amd64
sudo dpkg --remove wine1.7-i386
sudo dpkg --remove winetricks
sudo dpkg --remove wireless-regdb
sudo dpkg --remove wireless-tools
sudo dpkg --remove wodim
sudo dpkg --remove x11-apps
sudo dpkg --remove x11-session-utils
sudo dpkg --remove x11-utils
sudo dpkg --remove x11-xfs-utils
sudo dpkg --remove x11-xkb-utils
sudo dpkg --remove x11-xserver-utils
sudo dpkg --remove xauth
sudo dpkg --remove xbitmaps
sudo dpkg --remove xclip
sudo dpkg --remove xcursor-themes
sudo dpkg --remove xdg-user-dirs
sudo dpkg --remove xdg-user-dirs-gtk
sudo dpkg --remove xdg-utils
sudo dpkg --remove xdiagnose
sudo dpkg --remove xfonts-base
sudo dpkg --remove xfonts-encodings
sudo dpkg --remove xfonts-mathml
sudo dpkg --remove xfonts-scalable
sudo dpkg --remove xfonts-utils
sudo dpkg --remove xinit
sudo dpkg --remove xinput
sudo dpkg --remove xkb-data
sudo dpkg --remove xml-core
sudo dpkg --remove xorg
sudo dpkg --remove xorg-docs-core
sudo dpkg --remove xserver-common
sudo dpkg --remove xserver-xorg-core-lts-utopic
sudo dpkg --remove xserver-xorg-input-all-lts-utopic
sudo dpkg --remove xserver-xorg-input-evdev-lts-utopic
sudo dpkg --remove xserver-xorg-input-mouse-lts-utopic
sudo dpkg --remove xserver-xorg-input-synaptics-lts-utopic
sudo dpkg --remove xserver-xorg-input-vmmouse-lts-utopic
sudo dpkg --remove xserver-xorg-input-wacom-lts-utopic
sudo dpkg --remove xserver-xorg-lts-utopic
sudo dpkg --remove xserver-xorg-video-all-lts-utopic
sudo dpkg --remove xserver-xorg-video-ati-lts-utopic
sudo dpkg --remove xserver-xorg-video-cirrus-lts-utopic
sudo dpkg --remove xserver-xorg-video-fbdev-lts-utopic
sudo dpkg --remove xserver-xorg-video-intel-lts-utopic
sudo dpkg --remove xserver-xorg-video-mach64-lts-utopic
sudo dpkg --remove xserver-xorg-video-mga-lts-utopic
sudo dpkg --remove xserver-xorg-video-modesetting-lts-utopic
sudo dpkg --remove xserver-xorg-video-neomagic-lts-utopic
sudo dpkg --remove xserver-xorg-video-nouveau-lts-utopic
sudo dpkg --remove xserver-xorg-video-openchrome-lts-utopic
sudo dpkg --remove xserver-xorg-video-r128-lts-utopic
sudo dpkg --remove xserver-xorg-video-radeon-lts-utopic
sudo dpkg --remove xserver-xorg-video-savage-lts-utopic
sudo dpkg --remove xserver-xorg-video-siliconmotion-lts-utopic
sudo dpkg --remove xserver-xorg-video-sisusb-lts-utopic
sudo dpkg --remove xserver-xorg-video-tdfx-lts-utopic
sudo dpkg --remove xserver-xorg-video-trident-lts-utopic
sudo dpkg --remove xserver-xorg-video-vesa-lts-utopic
sudo dpkg --remove xserver-xorg-video-vmware-lts-utopic
sudo dpkg --remove xterm
sudo dpkg --remove xul-ext-ubufox
sudo dpkg --remove xul-ext-unity
sudo dpkg --remove xul-ext-webaccounts
sudo dpkg --remove xul-ext-websites-integration
sudo dpkg --remove xz-utils
sudo dpkg --remove yelp
sudo dpkg --remove yelp-xsl
sudo dpkg --remove zeitgeist
sudo dpkg --remove zeitgeist-core
sudo dpkg --remove zeitgeist-datahub
sudo dpkg --remove zenity
sudo dpkg --remove zenity-common
sudo dpkg --remove zip
sudo dpkg --remove zlib1g:amd64
sudo dpkg --remove zlib1g:i386
sudo dpkg --remove zlib1g-dev:amd64
