// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.4
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#include "sandbox_Block_proc.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic sandbox_Block_proc::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic sandbox_Block_proc::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<4> sandbox_Block_proc::ap_ST_st1_fsm_0 = "1";
const sc_lv<4> sandbox_Block_proc::ap_ST_st2_fsm_1 = "10";
const sc_lv<4> sandbox_Block_proc::ap_ST_pp0_stg0_fsm_2 = "100";
const sc_lv<4> sandbox_Block_proc::ap_ST_st5_fsm_3 = "1000";
const sc_lv<32> sandbox_Block_proc::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> sandbox_Block_proc::ap_const_lv1_1 = "1";
const sc_lv<32> sandbox_Block_proc::ap_const_lv32_1 = "1";
const sc_lv<32> sandbox_Block_proc::ap_const_lv32_2 = "10";
const sc_lv<1> sandbox_Block_proc::ap_const_lv1_0 = "0";
const sc_lv<32> sandbox_Block_proc::ap_const_lv32_3 = "11";
const sc_lv<10> sandbox_Block_proc::ap_const_lv10_0 = "0000000000";
const sc_lv<9> sandbox_Block_proc::ap_const_lv9_0 = "000000000";
const sc_lv<2> sandbox_Block_proc::ap_const_lv2_3 = "11";
const sc_lv<2> sandbox_Block_proc::ap_const_lv2_0 = "00";
const sc_lv<10> sandbox_Block_proc::ap_const_lv10_280 = "1010000000";
const sc_lv<10> sandbox_Block_proc::ap_const_lv10_1 = "1";
const sc_lv<9> sandbox_Block_proc::ap_const_lv9_1E0 = "111100000";
const sc_lv<9> sandbox_Block_proc::ap_const_lv9_1 = "1";
const sc_lv<9> sandbox_Block_proc::ap_const_lv9_1DF = "111011111";
const sc_lv<8> sandbox_Block_proc::ap_const_lv8_0 = "00000000";

sandbox_Block_proc::sandbox_Block_proc(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_done_reg );
    sensitive << ( exitcond3_i_fu_177_p2 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( exitcond3_i_fu_177_p2 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_ap_sig_bdd_109);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_115);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );

    SC_METHOD(thread_ap_sig_bdd_23);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_49);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_60);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_79);
    sensitive << ( exitcond4_i_reg_251 );
    sensitive << ( img_data_stream_0_V_assign_empty_n );
    sensitive << ( img_data_stream_1_V_assign_empty_n );

    SC_METHOD(thread_ap_sig_cseq_ST_pp0_stg0_fsm_2);
    sensitive << ( ap_sig_bdd_60 );

    SC_METHOD(thread_ap_sig_cseq_ST_st1_fsm_0);
    sensitive << ( ap_sig_bdd_23 );

    SC_METHOD(thread_ap_sig_cseq_ST_st2_fsm_1);
    sensitive << ( ap_sig_bdd_49 );

    SC_METHOD(thread_ap_sig_cseq_ST_st5_fsm_3);
    sensitive << ( ap_sig_bdd_109 );

    SC_METHOD(thread_ap_sig_ioackin_video_out_TREADY);
    sensitive << ( video_out_TREADY );
    sensitive << ( ap_reg_ioackin_video_out_TREADY );

    SC_METHOD(thread_axi_last_V_fu_201_p2);
    sensitive << ( p_3_i_reg_160 );
    sensitive << ( exitcond4_i_fu_189_p2 );
    sensitive << ( exitcond4_i_reg_251 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_2 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_sig_bdd_79 );
    sensitive << ( ap_sig_ioackin_video_out_TREADY );
    sensitive << ( ap_reg_ppiten_pp0_it1 );

    SC_METHOD(thread_exitcond3_i_fu_177_p2);
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( p_i_reg_149 );

    SC_METHOD(thread_exitcond4_i_fu_189_p2);
    sensitive << ( p_3_i_reg_160 );
    sensitive << ( exitcond4_i_reg_251 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_2 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_sig_bdd_79 );
    sensitive << ( ap_sig_ioackin_video_out_TREADY );
    sensitive << ( ap_reg_ppiten_pp0_it1 );

    SC_METHOD(thread_i_V_fu_183_p2);
    sensitive << ( p_i_reg_149 );

    SC_METHOD(thread_img_data_stream_0_V_assign_dout);

    SC_METHOD(thread_img_data_stream_0_V_assign_empty_n);

    SC_METHOD(thread_img_data_stream_1_V_assign_dout);

    SC_METHOD(thread_img_data_stream_1_V_assign_empty_n);

    SC_METHOD(thread_j_V_fu_195_p2);
    sensitive << ( p_3_i_reg_160 );

    SC_METHOD(thread_video_out_TDATA);
    sensitive << ( exitcond4_i_reg_251 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_2 );
    sensitive << ( img_data_stream_0_V_assign_dout );
    sensitive << ( img_data_stream_1_V_assign_dout );
    sensitive << ( ap_sig_bdd_79 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );

    SC_METHOD(thread_video_out_TDEST);
    sensitive << ( exitcond4_i_reg_251 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_2 );
    sensitive << ( ap_sig_bdd_79 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );

    SC_METHOD(thread_video_out_TID);
    sensitive << ( exitcond4_i_reg_251 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_2 );
    sensitive << ( ap_sig_bdd_79 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );

    SC_METHOD(thread_video_out_TKEEP);
    sensitive << ( exitcond4_i_reg_251 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_2 );
    sensitive << ( ap_sig_bdd_79 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );

    SC_METHOD(thread_video_out_TLAST);
    sensitive << ( exitcond4_i_reg_251 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_2 );
    sensitive << ( ap_sig_bdd_79 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( axi_last_V_reg_260 );

    SC_METHOD(thread_video_out_TSTRB);
    sensitive << ( exitcond4_i_reg_251 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_2 );
    sensitive << ( ap_sig_bdd_79 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );

    SC_METHOD(thread_video_out_TUSER);
    sensitive << ( exitcond4_i_reg_251 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_2 );
    sensitive << ( ap_sig_bdd_79 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( tmp_user_V_fu_92 );

    SC_METHOD(thread_video_out_TVALID);
    sensitive << ( exitcond4_i_reg_251 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_2 );
    sensitive << ( ap_sig_bdd_79 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_reg_ioackin_video_out_TREADY );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_CS_fsm );
    sensitive << ( exitcond3_i_fu_177_p2 );
    sensitive << ( exitcond4_i_fu_189_p2 );
    sensitive << ( exitcond4_i_reg_251 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_sig_bdd_79 );
    sensitive << ( ap_sig_ioackin_video_out_TREADY );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_sig_bdd_115 );

    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "0001";
    ap_reg_ppiten_pp0_it0 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it1 = SC_LOGIC_0;
    ap_reg_ioackin_video_out_TREADY = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "sandbox_Block_proc_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, result, "(port)result");
    sc_trace(mVcdFile, video_out_TDATA, "(port)video_out_TDATA");
    sc_trace(mVcdFile, video_out_TVALID, "(port)video_out_TVALID");
    sc_trace(mVcdFile, video_out_TREADY, "(port)video_out_TREADY");
    sc_trace(mVcdFile, video_out_TKEEP, "(port)video_out_TKEEP");
    sc_trace(mVcdFile, video_out_TSTRB, "(port)video_out_TSTRB");
    sc_trace(mVcdFile, video_out_TUSER, "(port)video_out_TUSER");
    sc_trace(mVcdFile, video_out_TLAST, "(port)video_out_TLAST");
    sc_trace(mVcdFile, video_out_TID, "(port)video_out_TID");
    sc_trace(mVcdFile, video_out_TDEST, "(port)video_out_TDEST");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st1_fsm_0, "ap_sig_cseq_ST_st1_fsm_0");
    sc_trace(mVcdFile, ap_sig_bdd_23, "ap_sig_bdd_23");
    sc_trace(mVcdFile, p_3_i_reg_160, "p_3_i_reg_160");
    sc_trace(mVcdFile, exitcond3_i_fu_177_p2, "exitcond3_i_fu_177_p2");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st2_fsm_1, "ap_sig_cseq_ST_st2_fsm_1");
    sc_trace(mVcdFile, ap_sig_bdd_49, "ap_sig_bdd_49");
    sc_trace(mVcdFile, i_V_fu_183_p2, "i_V_fu_183_p2");
    sc_trace(mVcdFile, i_V_reg_246, "i_V_reg_246");
    sc_trace(mVcdFile, exitcond4_i_fu_189_p2, "exitcond4_i_fu_189_p2");
    sc_trace(mVcdFile, exitcond4_i_reg_251, "exitcond4_i_reg_251");
    sc_trace(mVcdFile, ap_sig_cseq_ST_pp0_stg0_fsm_2, "ap_sig_cseq_ST_pp0_stg0_fsm_2");
    sc_trace(mVcdFile, ap_sig_bdd_60, "ap_sig_bdd_60");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it0, "ap_reg_ppiten_pp0_it0");
    sc_trace(mVcdFile, img_data_stream_0_V_assign_dout, "img_data_stream_0_V_assign_dout");
    sc_trace(mVcdFile, img_data_stream_0_V_assign_empty_n, "img_data_stream_0_V_assign_empty_n");
    sc_trace(mVcdFile, img_data_stream_1_V_assign_dout, "img_data_stream_1_V_assign_dout");
    sc_trace(mVcdFile, img_data_stream_1_V_assign_empty_n, "img_data_stream_1_V_assign_empty_n");
    sc_trace(mVcdFile, ap_sig_bdd_79, "ap_sig_bdd_79");
    sc_trace(mVcdFile, ap_sig_ioackin_video_out_TREADY, "ap_sig_ioackin_video_out_TREADY");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it1, "ap_reg_ppiten_pp0_it1");
    sc_trace(mVcdFile, j_V_fu_195_p2, "j_V_fu_195_p2");
    sc_trace(mVcdFile, axi_last_V_fu_201_p2, "axi_last_V_fu_201_p2");
    sc_trace(mVcdFile, axi_last_V_reg_260, "axi_last_V_reg_260");
    sc_trace(mVcdFile, p_i_reg_149, "p_i_reg_149");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st5_fsm_3, "ap_sig_cseq_ST_st5_fsm_3");
    sc_trace(mVcdFile, ap_sig_bdd_109, "ap_sig_bdd_109");
    sc_trace(mVcdFile, ap_sig_bdd_115, "ap_sig_bdd_115");
    sc_trace(mVcdFile, tmp_user_V_fu_92, "tmp_user_V_fu_92");
    sc_trace(mVcdFile, ap_reg_ioackin_video_out_TREADY, "ap_reg_ioackin_video_out_TREADY");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

sandbox_Block_proc::~sandbox_Block_proc() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void sandbox_Block_proc::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_st1_fsm_0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
                    !esl_seteq<1,1,1>(exitcond3_i_fu_177_p2.read(), ap_const_lv1_0))) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ioackin_video_out_TREADY = ap_const_logic_0;
    } else {
        if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && 
              esl_seteq<1,1,1>(exitcond4_i_reg_251.read(), ap_const_lv1_0) && 
              esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
              !((ap_sig_bdd_79.read() || 
  (esl_seteq<1,1,1>(exitcond4_i_reg_251.read(), ap_const_lv1_0) && 
   esl_seteq<1,1,1>(ap_const_logic_0, ap_sig_ioackin_video_out_TREADY.read()))) && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()))))) {
            ap_reg_ioackin_video_out_TREADY = ap_const_logic_0;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && 
                     esl_seteq<1,1,1>(exitcond4_i_reg_251.read(), ap_const_lv1_0) && 
                     esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
                     !(ap_sig_bdd_79.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) && 
                     esl_seteq<1,1,1>(ap_const_logic_1, video_out_TREADY.read())))) {
            ap_reg_ioackin_video_out_TREADY = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && 
             !((ap_sig_bdd_79.read() || 
  (esl_seteq<1,1,1>(exitcond4_i_reg_251.read(), ap_const_lv1_0) && 
   esl_seteq<1,1,1>(ap_const_logic_0, ap_sig_ioackin_video_out_TREADY.read()))) && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) && 
             !esl_seteq<1,1,1>(exitcond4_i_fu_189_p2.read(), ap_const_lv1_0))) {
            ap_reg_ppiten_pp0_it0 = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
                    esl_seteq<1,1,1>(exitcond3_i_fu_177_p2.read(), ap_const_lv1_0))) {
            ap_reg_ppiten_pp0_it0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it1 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && 
             !((ap_sig_bdd_79.read() || 
  (esl_seteq<1,1,1>(exitcond4_i_reg_251.read(), ap_const_lv1_0) && 
   esl_seteq<1,1,1>(ap_const_logic_0, ap_sig_ioackin_video_out_TREADY.read()))) && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) && 
             esl_seteq<1,1,1>(exitcond4_i_fu_189_p2.read(), ap_const_lv1_0))) {
            ap_reg_ppiten_pp0_it1 = ap_const_logic_1;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
                     esl_seteq<1,1,1>(exitcond3_i_fu_177_p2.read(), ap_const_lv1_0)) || 
                    (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && 
                     !((ap_sig_bdd_79.read() || 
  (esl_seteq<1,1,1>(exitcond4_i_reg_251.read(), ap_const_lv1_0) && 
   esl_seteq<1,1,1>(ap_const_logic_0, ap_sig_ioackin_video_out_TREADY.read()))) && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) && 
                     !esl_seteq<1,1,1>(exitcond4_i_fu_189_p2.read(), ap_const_lv1_0)))) {
            ap_reg_ppiten_pp0_it1 = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
         !((ap_sig_bdd_79.read() || 
  (esl_seteq<1,1,1>(exitcond4_i_reg_251.read(), ap_const_lv1_0) && 
   esl_seteq<1,1,1>(ap_const_logic_0, ap_sig_ioackin_video_out_TREADY.read()))) && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) && 
         esl_seteq<1,1,1>(exitcond4_i_fu_189_p2.read(), ap_const_lv1_0))) {
        p_3_i_reg_160 = j_V_fu_195_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
                esl_seteq<1,1,1>(exitcond3_i_fu_177_p2.read(), ap_const_lv1_0))) {
        p_3_i_reg_160 = ap_const_lv9_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
         !ap_sig_bdd_115.read())) {
        p_i_reg_149 = ap_const_lv10_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_3.read())) {
        p_i_reg_149 = i_V_reg_246.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && 
         esl_seteq<1,1,1>(exitcond4_i_reg_251.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         !((ap_sig_bdd_79.read() || 
  (esl_seteq<1,1,1>(exitcond4_i_reg_251.read(), ap_const_lv1_0) && 
   esl_seteq<1,1,1>(ap_const_logic_0, ap_sig_ioackin_video_out_TREADY.read()))) && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
        tmp_user_V_fu_92 = ap_const_lv1_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                !ap_sig_bdd_115.read())) {
        tmp_user_V_fu_92 = ap_const_lv1_1;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && !((ap_sig_bdd_79.read() || 
  (esl_seteq<1,1,1>(exitcond4_i_reg_251.read(), ap_const_lv1_0) && 
   esl_seteq<1,1,1>(ap_const_logic_0, ap_sig_ioackin_video_out_TREADY.read()))) && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) && esl_seteq<1,1,1>(exitcond4_i_fu_189_p2.read(), ap_const_lv1_0))) {
        axi_last_V_reg_260 = axi_last_V_fu_201_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && !((ap_sig_bdd_79.read() || 
  (esl_seteq<1,1,1>(exitcond4_i_reg_251.read(), ap_const_lv1_0) && 
   esl_seteq<1,1,1>(ap_const_logic_0, ap_sig_ioackin_video_out_TREADY.read()))) && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
        exitcond4_i_reg_251 = exitcond4_i_fu_189_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        i_V_reg_246 = i_V_fu_183_p2.read();
    }
}

void sandbox_Block_proc::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_done_reg.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
          !esl_seteq<1,1,1>(exitcond3_i_fu_177_p2.read(), ap_const_lv1_0)))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void sandbox_Block_proc::thread_ap_idle() {
    if ((!esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void sandbox_Block_proc::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
         !esl_seteq<1,1,1>(exitcond3_i_fu_177_p2.read(), ap_const_lv1_0))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void sandbox_Block_proc::thread_ap_sig_bdd_109() {
    ap_sig_bdd_109 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(3, 3));
}

void sandbox_Block_proc::thread_ap_sig_bdd_115() {
    ap_sig_bdd_115 = (esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1));
}

void sandbox_Block_proc::thread_ap_sig_bdd_23() {
    ap_sig_bdd_23 = esl_seteq<1,1,1>(ap_CS_fsm.read().range(0, 0), ap_const_lv1_1);
}

void sandbox_Block_proc::thread_ap_sig_bdd_49() {
    ap_sig_bdd_49 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(1, 1));
}

void sandbox_Block_proc::thread_ap_sig_bdd_60() {
    ap_sig_bdd_60 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(2, 2));
}

void sandbox_Block_proc::thread_ap_sig_bdd_79() {
    ap_sig_bdd_79 = ((esl_seteq<1,1,1>(img_data_stream_0_V_assign_empty_n.read(), ap_const_logic_0) && 
  esl_seteq<1,1,1>(exitcond4_i_reg_251.read(), ap_const_lv1_0)) || (esl_seteq<1,1,1>(exitcond4_i_reg_251.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(img_data_stream_1_V_assign_empty_n.read(), ap_const_logic_0)));
}

void sandbox_Block_proc::thread_ap_sig_cseq_ST_pp0_stg0_fsm_2() {
    if (ap_sig_bdd_60.read()) {
        ap_sig_cseq_ST_pp0_stg0_fsm_2 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_pp0_stg0_fsm_2 = ap_const_logic_0;
    }
}

void sandbox_Block_proc::thread_ap_sig_cseq_ST_st1_fsm_0() {
    if (ap_sig_bdd_23.read()) {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    }
}

void sandbox_Block_proc::thread_ap_sig_cseq_ST_st2_fsm_1() {
    if (ap_sig_bdd_49.read()) {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_0;
    }
}

void sandbox_Block_proc::thread_ap_sig_cseq_ST_st5_fsm_3() {
    if (ap_sig_bdd_109.read()) {
        ap_sig_cseq_ST_st5_fsm_3 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st5_fsm_3 = ap_const_logic_0;
    }
}

void sandbox_Block_proc::thread_ap_sig_ioackin_video_out_TREADY() {
    if (esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ioackin_video_out_TREADY.read())) {
        ap_sig_ioackin_video_out_TREADY = video_out_TREADY.read();
    } else {
        ap_sig_ioackin_video_out_TREADY = ap_const_logic_1;
    }
}

void sandbox_Block_proc::thread_axi_last_V_fu_201_p2() {
    axi_last_V_fu_201_p2 = (!p_3_i_reg_160.read().is_01() || !ap_const_lv9_1DF.is_01())? sc_lv<1>(): sc_lv<1>(p_3_i_reg_160.read() == ap_const_lv9_1DF);
}

void sandbox_Block_proc::thread_exitcond3_i_fu_177_p2() {
    exitcond3_i_fu_177_p2 = (!p_i_reg_149.read().is_01() || !ap_const_lv10_280.is_01())? sc_lv<1>(): sc_lv<1>(p_i_reg_149.read() == ap_const_lv10_280);
}

void sandbox_Block_proc::thread_exitcond4_i_fu_189_p2() {
    exitcond4_i_fu_189_p2 = (!p_3_i_reg_160.read().is_01() || !ap_const_lv9_1E0.is_01())? sc_lv<1>(): sc_lv<1>(p_3_i_reg_160.read() == ap_const_lv9_1E0);
}

void sandbox_Block_proc::thread_i_V_fu_183_p2() {
    i_V_fu_183_p2 = (!p_i_reg_149.read().is_01() || !ap_const_lv10_1.is_01())? sc_lv<10>(): (sc_biguint<10>(p_i_reg_149.read()) + sc_biguint<10>(ap_const_lv10_1));
}

void sandbox_Block_proc::thread_img_data_stream_0_V_assign_dout() {
    img_data_stream_0_V_assign_dout = ap_const_lv8_0;
}

void sandbox_Block_proc::thread_img_data_stream_0_V_assign_empty_n() {
    img_data_stream_0_V_assign_empty_n = ap_const_logic_1;
}

void sandbox_Block_proc::thread_img_data_stream_1_V_assign_dout() {
    img_data_stream_1_V_assign_dout = ap_const_lv8_0;
}

void sandbox_Block_proc::thread_img_data_stream_1_V_assign_empty_n() {
    img_data_stream_1_V_assign_empty_n = ap_const_logic_1;
}

void sandbox_Block_proc::thread_j_V_fu_195_p2() {
    j_V_fu_195_p2 = (!p_3_i_reg_160.read().is_01() || !ap_const_lv9_1.is_01())? sc_lv<9>(): (sc_biguint<9>(p_3_i_reg_160.read()) + sc_biguint<9>(ap_const_lv9_1));
}

void sandbox_Block_proc::thread_video_out_TDATA() {
    video_out_TDATA = esl_concat<8,8>(img_data_stream_1_V_assign_dout.read(), img_data_stream_0_V_assign_dout.read());
}

void sandbox_Block_proc::thread_video_out_TDEST() {
    video_out_TDEST = ap_const_lv1_0;
}

void sandbox_Block_proc::thread_video_out_TID() {
    video_out_TID = ap_const_lv1_0;
}

void sandbox_Block_proc::thread_video_out_TKEEP() {
    video_out_TKEEP = ap_const_lv2_3;
}

void sandbox_Block_proc::thread_video_out_TLAST() {
    video_out_TLAST = axi_last_V_reg_260.read();
}

void sandbox_Block_proc::thread_video_out_TSTRB() {
    video_out_TSTRB = ap_const_lv2_0;
}

void sandbox_Block_proc::thread_video_out_TUSER() {
    video_out_TUSER = tmp_user_V_fu_92.read();
}

void sandbox_Block_proc::thread_video_out_TVALID() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && 
          esl_seteq<1,1,1>(exitcond4_i_reg_251.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
          !(ap_sig_bdd_79.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) && 
          esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ioackin_video_out_TREADY.read())))) {
        video_out_TVALID = ap_const_logic_1;
    } else {
        video_out_TVALID = ap_const_logic_0;
    }
}

void sandbox_Block_proc::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if (!ap_sig_bdd_115.read()) {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            } else {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            }
            break;
        case 2 : 
            if (!esl_seteq<1,1,1>(exitcond3_i_fu_177_p2.read(), ap_const_lv1_0)) {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            } else {
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_2;
            }
            break;
        case 4 : 
            if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && !((ap_sig_bdd_79.read() || 
  (esl_seteq<1,1,1>(exitcond4_i_reg_251.read(), ap_const_lv1_0) && 
   esl_seteq<1,1,1>(ap_const_logic_0, ap_sig_ioackin_video_out_TREADY.read()))) && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) && !esl_seteq<1,1,1>(exitcond4_i_fu_189_p2.read(), ap_const_lv1_0))) {
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_2;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && !((ap_sig_bdd_79.read() || 
  (esl_seteq<1,1,1>(exitcond4_i_reg_251.read(), ap_const_lv1_0) && 
   esl_seteq<1,1,1>(ap_const_logic_0, ap_sig_ioackin_video_out_TREADY.read()))) && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) && !esl_seteq<1,1,1>(exitcond4_i_fu_189_p2.read(), ap_const_lv1_0))) {
                ap_NS_fsm = ap_ST_st5_fsm_3;
            } else {
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_2;
            }
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_st2_fsm_1;
            break;
        default : 
            ap_NS_fsm = "XXXX";
            break;
    }
}

}

