// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.4
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#include "sandbox.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const int sandbox::C_DATA_WIDTH = "100000";
const int sandbox::C_WSTRB_WIDTH = "100";
const int sandbox::C_ADDR_WIDTH = "100000";
const sc_logic sandbox::ap_const_logic_1 = sc_dt::Log_1;
const sc_lv<16> sandbox::ap_const_lv16_0 = "0000000000000000";
const sc_lv<2> sandbox::ap_const_lv2_0 = "00";
const sc_lv<1> sandbox::ap_const_lv1_0 = "0";
const bool sandbox::ap_true = true;
const sc_logic sandbox::ap_const_logic_0 = sc_dt::Log_0;

sandbox::sandbox(sc_module_name name) : sc_module(name), mVcdFile(0) {
    sandbox_CONTROL_BUS_s_axi_U = new sandbox_CONTROL_BUS_s_axi<C_S_AXI_CONTROL_BUS_ADDR_WIDTH,C_S_AXI_CONTROL_BUS_DATA_WIDTH>("sandbox_CONTROL_BUS_s_axi_U");
    sandbox_CONTROL_BUS_s_axi_U->AWVALID(s_axi_CONTROL_BUS_AWVALID);
    sandbox_CONTROL_BUS_s_axi_U->AWREADY(s_axi_CONTROL_BUS_AWREADY);
    sandbox_CONTROL_BUS_s_axi_U->AWADDR(s_axi_CONTROL_BUS_AWADDR);
    sandbox_CONTROL_BUS_s_axi_U->WVALID(s_axi_CONTROL_BUS_WVALID);
    sandbox_CONTROL_BUS_s_axi_U->WREADY(s_axi_CONTROL_BUS_WREADY);
    sandbox_CONTROL_BUS_s_axi_U->WDATA(s_axi_CONTROL_BUS_WDATA);
    sandbox_CONTROL_BUS_s_axi_U->WSTRB(s_axi_CONTROL_BUS_WSTRB);
    sandbox_CONTROL_BUS_s_axi_U->ARVALID(s_axi_CONTROL_BUS_ARVALID);
    sandbox_CONTROL_BUS_s_axi_U->ARREADY(s_axi_CONTROL_BUS_ARREADY);
    sandbox_CONTROL_BUS_s_axi_U->ARADDR(s_axi_CONTROL_BUS_ARADDR);
    sandbox_CONTROL_BUS_s_axi_U->RVALID(s_axi_CONTROL_BUS_RVALID);
    sandbox_CONTROL_BUS_s_axi_U->RREADY(s_axi_CONTROL_BUS_RREADY);
    sandbox_CONTROL_BUS_s_axi_U->RDATA(s_axi_CONTROL_BUS_RDATA);
    sandbox_CONTROL_BUS_s_axi_U->RRESP(s_axi_CONTROL_BUS_RRESP);
    sandbox_CONTROL_BUS_s_axi_U->BVALID(s_axi_CONTROL_BUS_BVALID);
    sandbox_CONTROL_BUS_s_axi_U->BREADY(s_axi_CONTROL_BUS_BREADY);
    sandbox_CONTROL_BUS_s_axi_U->BRESP(s_axi_CONTROL_BUS_BRESP);
    sandbox_CONTROL_BUS_s_axi_U->ACLK(ap_clk);
    sandbox_CONTROL_BUS_s_axi_U->ARESET(ap_rst_n_inv);
    sandbox_CONTROL_BUS_s_axi_U->ACLK_EN(sandbox_CONTROL_BUS_s_axi_U_ap_dummy_ce);
    sandbox_CONTROL_BUS_s_axi_U->rows(rows);
    sandbox_CONTROL_BUS_s_axi_U->cols(cols);
    sandbox_CONTROL_BUS_s_axi_U->ap_start(ap_start);
    sandbox_CONTROL_BUS_s_axi_U->interrupt(interrupt);
    sandbox_CONTROL_BUS_s_axi_U->ap_ready(ap_ready);
    sandbox_CONTROL_BUS_s_axi_U->ap_done(ap_done);
    sandbox_CONTROL_BUS_s_axi_U->ap_idle(ap_idle);
    sandbox_AXIvideo2Mat_16_640_480_16_U0 = new sandbox_AXIvideo2Mat_16_640_480_16_s("sandbox_AXIvideo2Mat_16_640_480_16_U0");
    sandbox_AXIvideo2Mat_16_640_480_16_U0->ap_clk(ap_clk);
    sandbox_AXIvideo2Mat_16_640_480_16_U0->ap_rst(ap_rst_n_inv);
    sandbox_AXIvideo2Mat_16_640_480_16_U0->ap_start(sandbox_AXIvideo2Mat_16_640_480_16_U0_ap_start);
    sandbox_AXIvideo2Mat_16_640_480_16_U0->ap_done(sandbox_AXIvideo2Mat_16_640_480_16_U0_ap_done);
    sandbox_AXIvideo2Mat_16_640_480_16_U0->ap_continue(sandbox_AXIvideo2Mat_16_640_480_16_U0_ap_continue);
    sandbox_AXIvideo2Mat_16_640_480_16_U0->ap_idle(sandbox_AXIvideo2Mat_16_640_480_16_U0_ap_idle);
    sandbox_AXIvideo2Mat_16_640_480_16_U0->ap_ready(sandbox_AXIvideo2Mat_16_640_480_16_U0_ap_ready);
    sandbox_AXIvideo2Mat_16_640_480_16_U0->AXI_video_strm_V_data_V_2(sandbox_AXIvideo2Mat_16_640_480_16_U0_AXI_video_strm_V_data_V_2);
    sandbox_AXIvideo2Mat_16_640_480_16_U0->AXI_video_strm_V_data_V_2_ap_vld(sandbox_AXIvideo2Mat_16_640_480_16_U0_AXI_video_strm_V_data_V_2_ap_vld);
    sandbox_AXIvideo2Mat_16_640_480_16_U0->video_in_TDATA(sandbox_AXIvideo2Mat_16_640_480_16_U0_video_in_TDATA);
    sandbox_AXIvideo2Mat_16_640_480_16_U0->video_in_TVALID(sandbox_AXIvideo2Mat_16_640_480_16_U0_video_in_TVALID);
    sandbox_AXIvideo2Mat_16_640_480_16_U0->video_in_TREADY(sandbox_AXIvideo2Mat_16_640_480_16_U0_video_in_TREADY);
    sandbox_AXIvideo2Mat_16_640_480_16_U0->video_in_TKEEP(sandbox_AXIvideo2Mat_16_640_480_16_U0_video_in_TKEEP);
    sandbox_AXIvideo2Mat_16_640_480_16_U0->video_in_TSTRB(sandbox_AXIvideo2Mat_16_640_480_16_U0_video_in_TSTRB);
    sandbox_AXIvideo2Mat_16_640_480_16_U0->video_in_TUSER(sandbox_AXIvideo2Mat_16_640_480_16_U0_video_in_TUSER);
    sandbox_AXIvideo2Mat_16_640_480_16_U0->video_in_TLAST(sandbox_AXIvideo2Mat_16_640_480_16_U0_video_in_TLAST);
    sandbox_AXIvideo2Mat_16_640_480_16_U0->video_in_TID(sandbox_AXIvideo2Mat_16_640_480_16_U0_video_in_TID);
    sandbox_AXIvideo2Mat_16_640_480_16_U0->video_in_TDEST(sandbox_AXIvideo2Mat_16_640_480_16_U0_video_in_TDEST);
    sandbox_AXIvideo2Mat_16_640_480_16_U0->img_data_stream_0_V_din(sandbox_AXIvideo2Mat_16_640_480_16_U0_img_data_stream_0_V_din);
    sandbox_AXIvideo2Mat_16_640_480_16_U0->img_data_stream_0_V_full_n(sandbox_AXIvideo2Mat_16_640_480_16_U0_img_data_stream_0_V_full_n);
    sandbox_AXIvideo2Mat_16_640_480_16_U0->img_data_stream_0_V_write(sandbox_AXIvideo2Mat_16_640_480_16_U0_img_data_stream_0_V_write);
    sandbox_AXIvideo2Mat_16_640_480_16_U0->img_data_stream_1_V_din(sandbox_AXIvideo2Mat_16_640_480_16_U0_img_data_stream_1_V_din);
    sandbox_AXIvideo2Mat_16_640_480_16_U0->img_data_stream_1_V_full_n(sandbox_AXIvideo2Mat_16_640_480_16_U0_img_data_stream_1_V_full_n);
    sandbox_AXIvideo2Mat_16_640_480_16_U0->img_data_stream_1_V_write(sandbox_AXIvideo2Mat_16_640_480_16_U0_img_data_stream_1_V_write);
    sandbox_AXIvideo2Mat_16_640_480_16_U0->img_data_stream_0_V_ap_vld(sandbox_AXIvideo2Mat_16_640_480_16_U0_img_data_stream_0_V_ap_vld);
    sandbox_AXIvideo2Mat_16_640_480_16_U0->img_data_stream_1_V_ap_vld(sandbox_AXIvideo2Mat_16_640_480_16_U0_img_data_stream_1_V_ap_vld);
    sandbox_Block_proc_U0 = new sandbox_Block_proc("sandbox_Block_proc_U0");
    sandbox_Block_proc_U0->ap_clk(ap_clk);
    sandbox_Block_proc_U0->ap_rst(ap_rst_n_inv);
    sandbox_Block_proc_U0->ap_start(sandbox_Block_proc_U0_ap_start);
    sandbox_Block_proc_U0->ap_done(sandbox_Block_proc_U0_ap_done);
    sandbox_Block_proc_U0->ap_continue(sandbox_Block_proc_U0_ap_continue);
    sandbox_Block_proc_U0->ap_idle(sandbox_Block_proc_U0_ap_idle);
    sandbox_Block_proc_U0->ap_ready(sandbox_Block_proc_U0_ap_ready);
    sandbox_Block_proc_U0->result(sandbox_Block_proc_U0_result);
    sandbox_Block_proc_U0->video_out_TDATA(sandbox_Block_proc_U0_video_out_TDATA);
    sandbox_Block_proc_U0->video_out_TVALID(sandbox_Block_proc_U0_video_out_TVALID);
    sandbox_Block_proc_U0->video_out_TREADY(sandbox_Block_proc_U0_video_out_TREADY);
    sandbox_Block_proc_U0->video_out_TKEEP(sandbox_Block_proc_U0_video_out_TKEEP);
    sandbox_Block_proc_U0->video_out_TSTRB(sandbox_Block_proc_U0_video_out_TSTRB);
    sandbox_Block_proc_U0->video_out_TUSER(sandbox_Block_proc_U0_video_out_TUSER);
    sandbox_Block_proc_U0->video_out_TLAST(sandbox_Block_proc_U0_video_out_TLAST);
    sandbox_Block_proc_U0->video_out_TID(sandbox_Block_proc_U0_video_out_TID);
    sandbox_Block_proc_U0->video_out_TDEST(sandbox_Block_proc_U0_video_out_TDEST);
    result_channel_U = new FIFO_sandbox_result_channel("result_channel_U");
    result_channel_U->clk(ap_clk);
    result_channel_U->reset(ap_rst_n_inv);
    result_channel_U->if_read_ce(result_channel_U_ap_dummy_ce);
    result_channel_U->if_write_ce(result_channel_U_ap_dummy_ce);
    result_channel_U->if_din(result_channel_din);
    result_channel_U->if_full_n(result_channel_full_n);
    result_channel_U->if_write(result_channel_write);
    result_channel_U->if_dout(result_channel_dout);
    result_channel_U->if_empty_n(result_channel_empty_n);
    result_channel_U->if_read(result_channel_read);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_chn_write_sandbox_AXIvideo2Mat_16_640_480_16_U0_result_channel);
    sensitive << ( sandbox_AXIvideo2Mat_16_640_480_16_U0_ap_done );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_sig_hs_done );

    SC_METHOD(thread_ap_idle);
    sensitive << ( sandbox_AXIvideo2Mat_16_640_480_16_U0_ap_idle );
    sensitive << ( sandbox_Block_proc_U0_ap_idle );
    sensitive << ( result_channel_empty_n );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_sig_top_allready );

    SC_METHOD(thread_ap_rst_n_inv);
    sensitive << ( ap_rst_n );

    SC_METHOD(thread_ap_sig_hs_continue);

    SC_METHOD(thread_ap_sig_hs_done);
    sensitive << ( sandbox_Block_proc_U0_ap_done );

    SC_METHOD(thread_ap_sig_top_allready);
    sensitive << ( sandbox_AXIvideo2Mat_16_640_480_16_U0_ap_ready );

    SC_METHOD(thread_result_channel_U_ap_dummy_ce);

    SC_METHOD(thread_result_channel_din);
    sensitive << ( sandbox_AXIvideo2Mat_16_640_480_16_U0_AXI_video_strm_V_data_V_2 );

    SC_METHOD(thread_result_channel_read);
    sensitive << ( sandbox_Block_proc_U0_ap_ready );

    SC_METHOD(thread_result_channel_write);
    sensitive << ( ap_chn_write_sandbox_AXIvideo2Mat_16_640_480_16_U0_result_channel );

    SC_METHOD(thread_sandbox_AXIvideo2Mat_16_640_480_16_U0_ap_continue);
    sensitive << ( result_channel_full_n );

    SC_METHOD(thread_sandbox_AXIvideo2Mat_16_640_480_16_U0_ap_start);
    sensitive << ( ap_start );

    SC_METHOD(thread_sandbox_AXIvideo2Mat_16_640_480_16_U0_img_data_stream_0_V_full_n);

    SC_METHOD(thread_sandbox_AXIvideo2Mat_16_640_480_16_U0_img_data_stream_1_V_full_n);

    SC_METHOD(thread_sandbox_AXIvideo2Mat_16_640_480_16_U0_video_in_TDATA);
    sensitive << ( video_in_TDATA );

    SC_METHOD(thread_sandbox_AXIvideo2Mat_16_640_480_16_U0_video_in_TDEST);
    sensitive << ( video_in_TDEST );

    SC_METHOD(thread_sandbox_AXIvideo2Mat_16_640_480_16_U0_video_in_TID);
    sensitive << ( video_in_TID );

    SC_METHOD(thread_sandbox_AXIvideo2Mat_16_640_480_16_U0_video_in_TKEEP);
    sensitive << ( video_in_TKEEP );

    SC_METHOD(thread_sandbox_AXIvideo2Mat_16_640_480_16_U0_video_in_TLAST);
    sensitive << ( video_in_TLAST );

    SC_METHOD(thread_sandbox_AXIvideo2Mat_16_640_480_16_U0_video_in_TSTRB);
    sensitive << ( video_in_TSTRB );

    SC_METHOD(thread_sandbox_AXIvideo2Mat_16_640_480_16_U0_video_in_TUSER);
    sensitive << ( video_in_TUSER );

    SC_METHOD(thread_sandbox_AXIvideo2Mat_16_640_480_16_U0_video_in_TVALID);
    sensitive << ( video_in_TVALID );

    SC_METHOD(thread_sandbox_Block_proc_U0_ap_continue);
    sensitive << ( ap_sig_hs_continue );

    SC_METHOD(thread_sandbox_Block_proc_U0_ap_start);
    sensitive << ( result_channel_empty_n );

    SC_METHOD(thread_sandbox_Block_proc_U0_result);
    sensitive << ( result_channel_dout );

    SC_METHOD(thread_sandbox_Block_proc_U0_video_out_TREADY);
    sensitive << ( video_out_TREADY );

    SC_METHOD(thread_sandbox_CONTROL_BUS_s_axi_U_ap_dummy_ce);

    SC_METHOD(thread_video_in_TREADY);
    sensitive << ( sandbox_AXIvideo2Mat_16_640_480_16_U0_video_in_TREADY );

    SC_METHOD(thread_video_out_TDATA);
    sensitive << ( sandbox_Block_proc_U0_video_out_TDATA );

    SC_METHOD(thread_video_out_TDEST);
    sensitive << ( sandbox_Block_proc_U0_video_out_TDEST );

    SC_METHOD(thread_video_out_TID);
    sensitive << ( sandbox_Block_proc_U0_video_out_TID );

    SC_METHOD(thread_video_out_TKEEP);
    sensitive << ( sandbox_Block_proc_U0_video_out_TKEEP );

    SC_METHOD(thread_video_out_TLAST);
    sensitive << ( sandbox_Block_proc_U0_video_out_TLAST );

    SC_METHOD(thread_video_out_TSTRB);
    sensitive << ( sandbox_Block_proc_U0_video_out_TSTRB );

    SC_METHOD(thread_video_out_TUSER);
    sensitive << ( sandbox_Block_proc_U0_video_out_TUSER );

    SC_METHOD(thread_video_out_TVALID);
    sensitive << ( sandbox_Block_proc_U0_video_out_TVALID );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    ap_reg_procdone_sandbox_AXIvideo2Mat_16_640_480_16_U0 = SC_LOGIC_0;
    ap_reg_procdone_sandbox_Block_proc_U0 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "sandbox_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, s_axi_CONTROL_BUS_AWVALID, "(port)s_axi_CONTROL_BUS_AWVALID");
    sc_trace(mVcdFile, s_axi_CONTROL_BUS_AWREADY, "(port)s_axi_CONTROL_BUS_AWREADY");
    sc_trace(mVcdFile, s_axi_CONTROL_BUS_AWADDR, "(port)s_axi_CONTROL_BUS_AWADDR");
    sc_trace(mVcdFile, s_axi_CONTROL_BUS_WVALID, "(port)s_axi_CONTROL_BUS_WVALID");
    sc_trace(mVcdFile, s_axi_CONTROL_BUS_WREADY, "(port)s_axi_CONTROL_BUS_WREADY");
    sc_trace(mVcdFile, s_axi_CONTROL_BUS_WDATA, "(port)s_axi_CONTROL_BUS_WDATA");
    sc_trace(mVcdFile, s_axi_CONTROL_BUS_WSTRB, "(port)s_axi_CONTROL_BUS_WSTRB");
    sc_trace(mVcdFile, s_axi_CONTROL_BUS_ARVALID, "(port)s_axi_CONTROL_BUS_ARVALID");
    sc_trace(mVcdFile, s_axi_CONTROL_BUS_ARREADY, "(port)s_axi_CONTROL_BUS_ARREADY");
    sc_trace(mVcdFile, s_axi_CONTROL_BUS_ARADDR, "(port)s_axi_CONTROL_BUS_ARADDR");
    sc_trace(mVcdFile, s_axi_CONTROL_BUS_RVALID, "(port)s_axi_CONTROL_BUS_RVALID");
    sc_trace(mVcdFile, s_axi_CONTROL_BUS_RREADY, "(port)s_axi_CONTROL_BUS_RREADY");
    sc_trace(mVcdFile, s_axi_CONTROL_BUS_RDATA, "(port)s_axi_CONTROL_BUS_RDATA");
    sc_trace(mVcdFile, s_axi_CONTROL_BUS_RRESP, "(port)s_axi_CONTROL_BUS_RRESP");
    sc_trace(mVcdFile, s_axi_CONTROL_BUS_BVALID, "(port)s_axi_CONTROL_BUS_BVALID");
    sc_trace(mVcdFile, s_axi_CONTROL_BUS_BREADY, "(port)s_axi_CONTROL_BUS_BREADY");
    sc_trace(mVcdFile, s_axi_CONTROL_BUS_BRESP, "(port)s_axi_CONTROL_BUS_BRESP");
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst_n, "(port)ap_rst_n");
    sc_trace(mVcdFile, interrupt, "(port)interrupt");
    sc_trace(mVcdFile, video_in_TDATA, "(port)video_in_TDATA");
    sc_trace(mVcdFile, video_in_TKEEP, "(port)video_in_TKEEP");
    sc_trace(mVcdFile, video_in_TSTRB, "(port)video_in_TSTRB");
    sc_trace(mVcdFile, video_in_TUSER, "(port)video_in_TUSER");
    sc_trace(mVcdFile, video_in_TLAST, "(port)video_in_TLAST");
    sc_trace(mVcdFile, video_in_TID, "(port)video_in_TID");
    sc_trace(mVcdFile, video_in_TDEST, "(port)video_in_TDEST");
    sc_trace(mVcdFile, video_out_TDATA, "(port)video_out_TDATA");
    sc_trace(mVcdFile, video_out_TKEEP, "(port)video_out_TKEEP");
    sc_trace(mVcdFile, video_out_TSTRB, "(port)video_out_TSTRB");
    sc_trace(mVcdFile, video_out_TUSER, "(port)video_out_TUSER");
    sc_trace(mVcdFile, video_out_TLAST, "(port)video_out_TLAST");
    sc_trace(mVcdFile, video_out_TID, "(port)video_out_TID");
    sc_trace(mVcdFile, video_out_TDEST, "(port)video_out_TDEST");
    sc_trace(mVcdFile, video_in_TVALID, "(port)video_in_TVALID");
    sc_trace(mVcdFile, video_in_TREADY, "(port)video_in_TREADY");
    sc_trace(mVcdFile, video_out_TVALID, "(port)video_out_TVALID");
    sc_trace(mVcdFile, video_out_TREADY, "(port)video_out_TREADY");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_rst_n_inv, "ap_rst_n_inv");
    sc_trace(mVcdFile, sandbox_CONTROL_BUS_s_axi_U_ap_dummy_ce, "sandbox_CONTROL_BUS_s_axi_U_ap_dummy_ce");
    sc_trace(mVcdFile, rows, "rows");
    sc_trace(mVcdFile, cols, "cols");
    sc_trace(mVcdFile, ap_start, "ap_start");
    sc_trace(mVcdFile, ap_ready, "ap_ready");
    sc_trace(mVcdFile, ap_done, "ap_done");
    sc_trace(mVcdFile, ap_idle, "ap_idle");
    sc_trace(mVcdFile, sandbox_AXIvideo2Mat_16_640_480_16_U0_ap_start, "sandbox_AXIvideo2Mat_16_640_480_16_U0_ap_start");
    sc_trace(mVcdFile, sandbox_AXIvideo2Mat_16_640_480_16_U0_ap_done, "sandbox_AXIvideo2Mat_16_640_480_16_U0_ap_done");
    sc_trace(mVcdFile, sandbox_AXIvideo2Mat_16_640_480_16_U0_ap_continue, "sandbox_AXIvideo2Mat_16_640_480_16_U0_ap_continue");
    sc_trace(mVcdFile, sandbox_AXIvideo2Mat_16_640_480_16_U0_ap_idle, "sandbox_AXIvideo2Mat_16_640_480_16_U0_ap_idle");
    sc_trace(mVcdFile, sandbox_AXIvideo2Mat_16_640_480_16_U0_ap_ready, "sandbox_AXIvideo2Mat_16_640_480_16_U0_ap_ready");
    sc_trace(mVcdFile, sandbox_AXIvideo2Mat_16_640_480_16_U0_AXI_video_strm_V_data_V_2, "sandbox_AXIvideo2Mat_16_640_480_16_U0_AXI_video_strm_V_data_V_2");
    sc_trace(mVcdFile, sandbox_AXIvideo2Mat_16_640_480_16_U0_AXI_video_strm_V_data_V_2_ap_vld, "sandbox_AXIvideo2Mat_16_640_480_16_U0_AXI_video_strm_V_data_V_2_ap_vld");
    sc_trace(mVcdFile, sandbox_AXIvideo2Mat_16_640_480_16_U0_video_in_TDATA, "sandbox_AXIvideo2Mat_16_640_480_16_U0_video_in_TDATA");
    sc_trace(mVcdFile, sandbox_AXIvideo2Mat_16_640_480_16_U0_video_in_TVALID, "sandbox_AXIvideo2Mat_16_640_480_16_U0_video_in_TVALID");
    sc_trace(mVcdFile, sandbox_AXIvideo2Mat_16_640_480_16_U0_video_in_TREADY, "sandbox_AXIvideo2Mat_16_640_480_16_U0_video_in_TREADY");
    sc_trace(mVcdFile, sandbox_AXIvideo2Mat_16_640_480_16_U0_video_in_TKEEP, "sandbox_AXIvideo2Mat_16_640_480_16_U0_video_in_TKEEP");
    sc_trace(mVcdFile, sandbox_AXIvideo2Mat_16_640_480_16_U0_video_in_TSTRB, "sandbox_AXIvideo2Mat_16_640_480_16_U0_video_in_TSTRB");
    sc_trace(mVcdFile, sandbox_AXIvideo2Mat_16_640_480_16_U0_video_in_TUSER, "sandbox_AXIvideo2Mat_16_640_480_16_U0_video_in_TUSER");
    sc_trace(mVcdFile, sandbox_AXIvideo2Mat_16_640_480_16_U0_video_in_TLAST, "sandbox_AXIvideo2Mat_16_640_480_16_U0_video_in_TLAST");
    sc_trace(mVcdFile, sandbox_AXIvideo2Mat_16_640_480_16_U0_video_in_TID, "sandbox_AXIvideo2Mat_16_640_480_16_U0_video_in_TID");
    sc_trace(mVcdFile, sandbox_AXIvideo2Mat_16_640_480_16_U0_video_in_TDEST, "sandbox_AXIvideo2Mat_16_640_480_16_U0_video_in_TDEST");
    sc_trace(mVcdFile, sandbox_AXIvideo2Mat_16_640_480_16_U0_img_data_stream_0_V_din, "sandbox_AXIvideo2Mat_16_640_480_16_U0_img_data_stream_0_V_din");
    sc_trace(mVcdFile, sandbox_AXIvideo2Mat_16_640_480_16_U0_img_data_stream_0_V_full_n, "sandbox_AXIvideo2Mat_16_640_480_16_U0_img_data_stream_0_V_full_n");
    sc_trace(mVcdFile, sandbox_AXIvideo2Mat_16_640_480_16_U0_img_data_stream_0_V_write, "sandbox_AXIvideo2Mat_16_640_480_16_U0_img_data_stream_0_V_write");
    sc_trace(mVcdFile, sandbox_AXIvideo2Mat_16_640_480_16_U0_img_data_stream_1_V_din, "sandbox_AXIvideo2Mat_16_640_480_16_U0_img_data_stream_1_V_din");
    sc_trace(mVcdFile, sandbox_AXIvideo2Mat_16_640_480_16_U0_img_data_stream_1_V_full_n, "sandbox_AXIvideo2Mat_16_640_480_16_U0_img_data_stream_1_V_full_n");
    sc_trace(mVcdFile, sandbox_AXIvideo2Mat_16_640_480_16_U0_img_data_stream_1_V_write, "sandbox_AXIvideo2Mat_16_640_480_16_U0_img_data_stream_1_V_write");
    sc_trace(mVcdFile, sandbox_AXIvideo2Mat_16_640_480_16_U0_img_data_stream_0_V_ap_vld, "sandbox_AXIvideo2Mat_16_640_480_16_U0_img_data_stream_0_V_ap_vld");
    sc_trace(mVcdFile, sandbox_AXIvideo2Mat_16_640_480_16_U0_img_data_stream_1_V_ap_vld, "sandbox_AXIvideo2Mat_16_640_480_16_U0_img_data_stream_1_V_ap_vld");
    sc_trace(mVcdFile, ap_chn_write_sandbox_AXIvideo2Mat_16_640_480_16_U0_result_channel, "ap_chn_write_sandbox_AXIvideo2Mat_16_640_480_16_U0_result_channel");
    sc_trace(mVcdFile, result_channel_full_n, "result_channel_full_n");
    sc_trace(mVcdFile, sandbox_Block_proc_U0_ap_start, "sandbox_Block_proc_U0_ap_start");
    sc_trace(mVcdFile, sandbox_Block_proc_U0_ap_done, "sandbox_Block_proc_U0_ap_done");
    sc_trace(mVcdFile, sandbox_Block_proc_U0_ap_continue, "sandbox_Block_proc_U0_ap_continue");
    sc_trace(mVcdFile, sandbox_Block_proc_U0_ap_idle, "sandbox_Block_proc_U0_ap_idle");
    sc_trace(mVcdFile, sandbox_Block_proc_U0_ap_ready, "sandbox_Block_proc_U0_ap_ready");
    sc_trace(mVcdFile, sandbox_Block_proc_U0_result, "sandbox_Block_proc_U0_result");
    sc_trace(mVcdFile, sandbox_Block_proc_U0_video_out_TDATA, "sandbox_Block_proc_U0_video_out_TDATA");
    sc_trace(mVcdFile, sandbox_Block_proc_U0_video_out_TVALID, "sandbox_Block_proc_U0_video_out_TVALID");
    sc_trace(mVcdFile, sandbox_Block_proc_U0_video_out_TREADY, "sandbox_Block_proc_U0_video_out_TREADY");
    sc_trace(mVcdFile, sandbox_Block_proc_U0_video_out_TKEEP, "sandbox_Block_proc_U0_video_out_TKEEP");
    sc_trace(mVcdFile, sandbox_Block_proc_U0_video_out_TSTRB, "sandbox_Block_proc_U0_video_out_TSTRB");
    sc_trace(mVcdFile, sandbox_Block_proc_U0_video_out_TUSER, "sandbox_Block_proc_U0_video_out_TUSER");
    sc_trace(mVcdFile, sandbox_Block_proc_U0_video_out_TLAST, "sandbox_Block_proc_U0_video_out_TLAST");
    sc_trace(mVcdFile, sandbox_Block_proc_U0_video_out_TID, "sandbox_Block_proc_U0_video_out_TID");
    sc_trace(mVcdFile, sandbox_Block_proc_U0_video_out_TDEST, "sandbox_Block_proc_U0_video_out_TDEST");
    sc_trace(mVcdFile, ap_sig_hs_continue, "ap_sig_hs_continue");
    sc_trace(mVcdFile, result_channel_U_ap_dummy_ce, "result_channel_U_ap_dummy_ce");
    sc_trace(mVcdFile, result_channel_din, "result_channel_din");
    sc_trace(mVcdFile, result_channel_write, "result_channel_write");
    sc_trace(mVcdFile, result_channel_dout, "result_channel_dout");
    sc_trace(mVcdFile, result_channel_empty_n, "result_channel_empty_n");
    sc_trace(mVcdFile, result_channel_read, "result_channel_read");
    sc_trace(mVcdFile, ap_reg_procdone_sandbox_AXIvideo2Mat_16_640_480_16_U0, "ap_reg_procdone_sandbox_AXIvideo2Mat_16_640_480_16_U0");
    sc_trace(mVcdFile, ap_sig_hs_done, "ap_sig_hs_done");
    sc_trace(mVcdFile, ap_reg_procdone_sandbox_Block_proc_U0, "ap_reg_procdone_sandbox_Block_proc_U0");
    sc_trace(mVcdFile, ap_CS, "ap_CS");
    sc_trace(mVcdFile, ap_sig_top_allready, "ap_sig_top_allready");
#endif

    }
    mHdltvinHandle.open("sandbox.hdltvin.dat");
    mHdltvoutHandle.open("sandbox.hdltvout.dat");
}

sandbox::~sandbox() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete sandbox_CONTROL_BUS_s_axi_U;
    delete sandbox_AXIvideo2Mat_16_640_480_16_U0;
    delete sandbox_Block_proc_U0;
    delete result_channel_U;
}

void sandbox::thread_ap_clk_no_reset_() {
    ap_CS = ap_const_logic_0;
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_reg_procdone_sandbox_AXIvideo2Mat_16_640_480_16_U0 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_hs_done.read())) {
            ap_reg_procdone_sandbox_AXIvideo2Mat_16_640_480_16_U0 = ap_const_logic_0;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, sandbox_AXIvideo2Mat_16_640_480_16_U0_ap_done.read())) {
            ap_reg_procdone_sandbox_AXIvideo2Mat_16_640_480_16_U0 = ap_const_logic_1;
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_reg_procdone_sandbox_Block_proc_U0 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_hs_done.read())) {
            ap_reg_procdone_sandbox_Block_proc_U0 = ap_const_logic_0;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, sandbox_Block_proc_U0_ap_done.read())) {
            ap_reg_procdone_sandbox_Block_proc_U0 = ap_const_logic_1;
        }
    }
}

void sandbox::thread_ap_chn_write_sandbox_AXIvideo2Mat_16_640_480_16_U0_result_channel() {
    ap_chn_write_sandbox_AXIvideo2Mat_16_640_480_16_U0_result_channel = sandbox_AXIvideo2Mat_16_640_480_16_U0_ap_done.read();
}

void sandbox::thread_ap_done() {
    ap_done = ap_sig_hs_done.read();
}

void sandbox::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, sandbox_AXIvideo2Mat_16_640_480_16_U0_ap_idle.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, sandbox_Block_proc_U0_ap_idle.read()) && 
         esl_seteq<1,1,1>(result_channel_empty_n.read(), ap_const_logic_0))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void sandbox::thread_ap_ready() {
    ap_ready = ap_sig_top_allready.read();
}

void sandbox::thread_ap_rst_n_inv() {
    ap_rst_n_inv =  (sc_logic) (~ap_rst_n.read());
}

void sandbox::thread_ap_sig_hs_continue() {
    ap_sig_hs_continue = ap_const_logic_1;
}

void sandbox::thread_ap_sig_hs_done() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, sandbox_Block_proc_U0_ap_done.read())) {
        ap_sig_hs_done = ap_const_logic_1;
    } else {
        ap_sig_hs_done = ap_const_logic_0;
    }
}

void sandbox::thread_ap_sig_top_allready() {
    ap_sig_top_allready = sandbox_AXIvideo2Mat_16_640_480_16_U0_ap_ready.read();
}

void sandbox::thread_result_channel_U_ap_dummy_ce() {
    result_channel_U_ap_dummy_ce = ap_const_logic_1;
}

void sandbox::thread_result_channel_din() {
    result_channel_din = sandbox_AXIvideo2Mat_16_640_480_16_U0_AXI_video_strm_V_data_V_2.read();
}

void sandbox::thread_result_channel_read() {
    result_channel_read = sandbox_Block_proc_U0_ap_ready.read();
}

void sandbox::thread_result_channel_write() {
    result_channel_write = ap_chn_write_sandbox_AXIvideo2Mat_16_640_480_16_U0_result_channel.read();
}

void sandbox::thread_sandbox_AXIvideo2Mat_16_640_480_16_U0_ap_continue() {
    sandbox_AXIvideo2Mat_16_640_480_16_U0_ap_continue = result_channel_full_n.read();
}

void sandbox::thread_sandbox_AXIvideo2Mat_16_640_480_16_U0_ap_start() {
    sandbox_AXIvideo2Mat_16_640_480_16_U0_ap_start = ap_start.read();
}

void sandbox::thread_sandbox_AXIvideo2Mat_16_640_480_16_U0_img_data_stream_0_V_full_n() {
    sandbox_AXIvideo2Mat_16_640_480_16_U0_img_data_stream_0_V_full_n = ap_const_logic_1;
}

void sandbox::thread_sandbox_AXIvideo2Mat_16_640_480_16_U0_img_data_stream_1_V_full_n() {
    sandbox_AXIvideo2Mat_16_640_480_16_U0_img_data_stream_1_V_full_n = ap_const_logic_1;
}

void sandbox::thread_sandbox_AXIvideo2Mat_16_640_480_16_U0_video_in_TDATA() {
    sandbox_AXIvideo2Mat_16_640_480_16_U0_video_in_TDATA = video_in_TDATA.read();
}

void sandbox::thread_sandbox_AXIvideo2Mat_16_640_480_16_U0_video_in_TDEST() {
    sandbox_AXIvideo2Mat_16_640_480_16_U0_video_in_TDEST = video_in_TDEST.read();
}

void sandbox::thread_sandbox_AXIvideo2Mat_16_640_480_16_U0_video_in_TID() {
    sandbox_AXIvideo2Mat_16_640_480_16_U0_video_in_TID = video_in_TID.read();
}

void sandbox::thread_sandbox_AXIvideo2Mat_16_640_480_16_U0_video_in_TKEEP() {
    sandbox_AXIvideo2Mat_16_640_480_16_U0_video_in_TKEEP = video_in_TKEEP.read();
}

void sandbox::thread_sandbox_AXIvideo2Mat_16_640_480_16_U0_video_in_TLAST() {
    sandbox_AXIvideo2Mat_16_640_480_16_U0_video_in_TLAST = video_in_TLAST.read();
}

void sandbox::thread_sandbox_AXIvideo2Mat_16_640_480_16_U0_video_in_TSTRB() {
    sandbox_AXIvideo2Mat_16_640_480_16_U0_video_in_TSTRB = video_in_TSTRB.read();
}

void sandbox::thread_sandbox_AXIvideo2Mat_16_640_480_16_U0_video_in_TUSER() {
    sandbox_AXIvideo2Mat_16_640_480_16_U0_video_in_TUSER = video_in_TUSER.read();
}

void sandbox::thread_sandbox_AXIvideo2Mat_16_640_480_16_U0_video_in_TVALID() {
    sandbox_AXIvideo2Mat_16_640_480_16_U0_video_in_TVALID = video_in_TVALID.read();
}

void sandbox::thread_sandbox_Block_proc_U0_ap_continue() {
    sandbox_Block_proc_U0_ap_continue = ap_sig_hs_continue.read();
}

void sandbox::thread_sandbox_Block_proc_U0_ap_start() {
    sandbox_Block_proc_U0_ap_start = result_channel_empty_n.read();
}

void sandbox::thread_sandbox_Block_proc_U0_result() {
    sandbox_Block_proc_U0_result = result_channel_dout.read();
}

void sandbox::thread_sandbox_Block_proc_U0_video_out_TREADY() {
    sandbox_Block_proc_U0_video_out_TREADY = video_out_TREADY.read();
}

void sandbox::thread_sandbox_CONTROL_BUS_s_axi_U_ap_dummy_ce() {
    sandbox_CONTROL_BUS_s_axi_U_ap_dummy_ce = ap_const_logic_1;
}

void sandbox::thread_video_in_TREADY() {
    video_in_TREADY = sandbox_AXIvideo2Mat_16_640_480_16_U0_video_in_TREADY.read();
}

void sandbox::thread_video_out_TDATA() {
    video_out_TDATA = sandbox_Block_proc_U0_video_out_TDATA.read();
}

void sandbox::thread_video_out_TDEST() {
    video_out_TDEST = sandbox_Block_proc_U0_video_out_TDEST.read();
}

void sandbox::thread_video_out_TID() {
    video_out_TID = sandbox_Block_proc_U0_video_out_TID.read();
}

void sandbox::thread_video_out_TKEEP() {
    video_out_TKEEP = sandbox_Block_proc_U0_video_out_TKEEP.read();
}

void sandbox::thread_video_out_TLAST() {
    video_out_TLAST = sandbox_Block_proc_U0_video_out_TLAST.read();
}

void sandbox::thread_video_out_TSTRB() {
    video_out_TSTRB = sandbox_Block_proc_U0_video_out_TSTRB.read();
}

void sandbox::thread_video_out_TUSER() {
    video_out_TUSER = sandbox_Block_proc_U0_video_out_TUSER.read();
}

void sandbox::thread_video_out_TVALID() {
    video_out_TVALID = sandbox_Block_proc_U0_video_out_TVALID.read();
}

void sandbox::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"s_axi_CONTROL_BUS_AWVALID\" :  \"" << s_axi_CONTROL_BUS_AWVALID.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"s_axi_CONTROL_BUS_AWREADY\" :  \"" << s_axi_CONTROL_BUS_AWREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_CONTROL_BUS_AWADDR\" :  \"" << s_axi_CONTROL_BUS_AWADDR.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_CONTROL_BUS_WVALID\" :  \"" << s_axi_CONTROL_BUS_WVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_CONTROL_BUS_WREADY\" :  \"" << s_axi_CONTROL_BUS_WREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_CONTROL_BUS_WDATA\" :  \"" << s_axi_CONTROL_BUS_WDATA.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_CONTROL_BUS_WSTRB\" :  \"" << s_axi_CONTROL_BUS_WSTRB.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_CONTROL_BUS_ARVALID\" :  \"" << s_axi_CONTROL_BUS_ARVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_CONTROL_BUS_ARREADY\" :  \"" << s_axi_CONTROL_BUS_ARREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_CONTROL_BUS_ARADDR\" :  \"" << s_axi_CONTROL_BUS_ARADDR.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_CONTROL_BUS_RVALID\" :  \"" << s_axi_CONTROL_BUS_RVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_CONTROL_BUS_RREADY\" :  \"" << s_axi_CONTROL_BUS_RREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_CONTROL_BUS_RDATA\" :  \"" << s_axi_CONTROL_BUS_RDATA.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_CONTROL_BUS_RRESP\" :  \"" << s_axi_CONTROL_BUS_RRESP.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_CONTROL_BUS_BVALID\" :  \"" << s_axi_CONTROL_BUS_BVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_CONTROL_BUS_BREADY\" :  \"" << s_axi_CONTROL_BUS_BREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_CONTROL_BUS_BRESP\" :  \"" << s_axi_CONTROL_BUS_BRESP.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_rst_n\" :  \"" << ap_rst_n.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"interrupt\" :  \"" << interrupt.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"video_in_TDATA\" :  \"" << video_in_TDATA.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"video_in_TKEEP\" :  \"" << video_in_TKEEP.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"video_in_TSTRB\" :  \"" << video_in_TSTRB.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"video_in_TUSER\" :  \"" << video_in_TUSER.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"video_in_TLAST\" :  \"" << video_in_TLAST.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"video_in_TID\" :  \"" << video_in_TID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"video_in_TDEST\" :  \"" << video_in_TDEST.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"video_out_TDATA\" :  \"" << video_out_TDATA.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"video_out_TKEEP\" :  \"" << video_out_TKEEP.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"video_out_TSTRB\" :  \"" << video_out_TSTRB.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"video_out_TUSER\" :  \"" << video_out_TUSER.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"video_out_TLAST\" :  \"" << video_out_TLAST.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"video_out_TID\" :  \"" << video_out_TID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"video_out_TDEST\" :  \"" << video_out_TDEST.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"video_in_TVALID\" :  \"" << video_in_TVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"video_in_TREADY\" :  \"" << video_in_TREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"video_out_TVALID\" :  \"" << video_out_TVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"video_out_TREADY\" :  \"" << video_out_TREADY.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

