// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.4
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#include "sandbox_AXIvideo2Mat.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic sandbox_AXIvideo2Mat::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic sandbox_AXIvideo2Mat::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<7> sandbox_AXIvideo2Mat::ap_ST_st1_fsm_0 = "1";
const sc_lv<7> sandbox_AXIvideo2Mat::ap_ST_st2_fsm_1 = "10";
const sc_lv<7> sandbox_AXIvideo2Mat::ap_ST_st3_fsm_2 = "100";
const sc_lv<7> sandbox_AXIvideo2Mat::ap_ST_st4_fsm_3 = "1000";
const sc_lv<7> sandbox_AXIvideo2Mat::ap_ST_pp1_stg0_fsm_4 = "10000";
const sc_lv<7> sandbox_AXIvideo2Mat::ap_ST_st7_fsm_5 = "100000";
const sc_lv<7> sandbox_AXIvideo2Mat::ap_ST_st8_fsm_6 = "1000000";
const sc_lv<32> sandbox_AXIvideo2Mat::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> sandbox_AXIvideo2Mat::ap_const_lv1_1 = "1";
const sc_lv<32> sandbox_AXIvideo2Mat::ap_const_lv32_1 = "1";
const sc_lv<32> sandbox_AXIvideo2Mat::ap_const_lv32_3 = "11";
const sc_lv<32> sandbox_AXIvideo2Mat::ap_const_lv32_4 = "100";
const sc_lv<1> sandbox_AXIvideo2Mat::ap_const_lv1_0 = "0";
const sc_lv<32> sandbox_AXIvideo2Mat::ap_const_lv32_5 = "101";
const sc_lv<32> sandbox_AXIvideo2Mat::ap_const_lv32_6 = "110";
const sc_lv<32> sandbox_AXIvideo2Mat::ap_const_lv32_2 = "10";
const sc_lv<11> sandbox_AXIvideo2Mat::ap_const_lv11_0 = "00000000000";
const sc_lv<11> sandbox_AXIvideo2Mat::ap_const_lv11_780 = "11110000000";
const sc_lv<11> sandbox_AXIvideo2Mat::ap_const_lv11_1 = "1";
const sc_lv<11> sandbox_AXIvideo2Mat::ap_const_lv11_438 = "10000111000";
const sc_lv<11> sandbox_AXIvideo2Mat::ap_const_lv11_437 = "10000110111";
const sc_lv<32> sandbox_AXIvideo2Mat::ap_const_lv32_1F = "11111";
const sc_lv<32> sandbox_AXIvideo2Mat::ap_const_lv32_8 = "1000";
const sc_lv<32> sandbox_AXIvideo2Mat::ap_const_lv32_F = "1111";
const sc_lv<32> sandbox_AXIvideo2Mat::ap_const_lv32_10 = "10000";
const sc_lv<32> sandbox_AXIvideo2Mat::ap_const_lv32_17 = "10111";
const bool sandbox_AXIvideo2Mat::ap_true = true;

sandbox_AXIvideo2Mat::sandbox_AXIvideo2Mat(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_AXI_video_strm_V_data_V_2);
    sensitive << ( exitcond1_fu_364_p2 );
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( res_reg_193 );

    SC_METHOD(thread_AXI_video_strm_V_data_V_2_ap_vld);
    sensitive << ( exitcond1_fu_364_p2 );
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_done_reg );
    sensitive << ( exitcond1_fu_364_p2 );
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( exitcond1_fu_364_p2 );
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );

    SC_METHOD(thread_ap_reg_phiprechg_axi_last_V_2_reg_262pp1_it0);

    SC_METHOD(thread_ap_reg_phiprechg_eol_2_reg_286pp1_it0);

    SC_METHOD(thread_ap_reg_phiprechg_p_Val2_s_reg_274pp1_it0);

    SC_METHOD(thread_ap_sig_bdd_104);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_111);
    sensitive << ( exitcond2_fu_376_p2 );
    sensitive << ( brmerge_fu_391_p2 );

    SC_METHOD(thread_ap_sig_bdd_112);
    sensitive << ( video_in_TVALID );
    sensitive << ( exitcond2_fu_376_p2 );
    sensitive << ( brmerge_fu_391_p2 );

    SC_METHOD(thread_ap_sig_bdd_124);
    sensitive << ( ap_sig_cseq_ST_pp1_stg0_fsm_4 );
    sensitive << ( ap_sig_bdd_112 );
    sensitive << ( ap_reg_ppiten_pp1_it0 );

    SC_METHOD(thread_ap_sig_bdd_141);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_146);
    sensitive << ( video_in_TVALID );
    sensitive << ( eol_3_reg_333 );

    SC_METHOD(thread_ap_sig_bdd_166);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_173);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_200);
    sensitive << ( exitcond2_fu_376_p2 );
    sensitive << ( brmerge_fu_391_p2 );

    SC_METHOD(thread_ap_sig_bdd_216);
    sensitive << ( exitcond2_fu_376_p2 );
    sensitive << ( ap_sig_cseq_ST_pp1_stg0_fsm_4 );
    sensitive << ( ap_reg_ppiten_pp1_it0 );

    SC_METHOD(thread_ap_sig_bdd_26);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_335);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );

    SC_METHOD(thread_ap_sig_bdd_79);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_93);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_cseq_ST_pp1_stg0_fsm_4);
    sensitive << ( ap_sig_bdd_104 );

    SC_METHOD(thread_ap_sig_cseq_ST_st1_fsm_0);
    sensitive << ( ap_sig_bdd_26 );

    SC_METHOD(thread_ap_sig_cseq_ST_st2_fsm_1);
    sensitive << ( ap_sig_bdd_79 );

    SC_METHOD(thread_ap_sig_cseq_ST_st3_fsm_2);
    sensitive << ( ap_sig_bdd_173 );

    SC_METHOD(thread_ap_sig_cseq_ST_st4_fsm_3);
    sensitive << ( ap_sig_bdd_93 );

    SC_METHOD(thread_ap_sig_cseq_ST_st7_fsm_5);
    sensitive << ( ap_sig_bdd_141 );

    SC_METHOD(thread_ap_sig_cseq_ST_st8_fsm_6);
    sensitive << ( ap_sig_bdd_166 );

    SC_METHOD(thread_axi_data_V_1_phi_fu_220_p4);
    sensitive << ( axi_data_V_1_reg_217 );
    sensitive << ( p_Val2_s_reg_274 );
    sensitive << ( exitcond2_reg_516 );
    sensitive << ( ap_sig_cseq_ST_pp1_stg0_fsm_4 );
    sensitive << ( ap_reg_ppiten_pp1_it1 );

    SC_METHOD(thread_axi_last_V_1_mux_fu_403_p2);
    sensitive << ( eol_1_phi_fu_209_p4 );
    sensitive << ( not_sof_2_fu_397_p2 );

    SC_METHOD(thread_brmerge_fu_391_p2);
    sensitive << ( eol_phi_fu_254_p4 );
    sensitive << ( sof_1_fu_112 );

    SC_METHOD(thread_eol_1_phi_fu_209_p4);
    sensitive << ( eol_1_reg_206 );
    sensitive << ( axi_last_V_2_reg_262 );
    sensitive << ( exitcond2_reg_516 );
    sensitive << ( ap_sig_cseq_ST_pp1_stg0_fsm_4 );
    sensitive << ( ap_reg_ppiten_pp1_it1 );

    SC_METHOD(thread_eol_2_phi_fu_290_p4);
    sensitive << ( video_in_TLAST );
    sensitive << ( brmerge_fu_391_p2 );
    sensitive << ( ap_reg_phiprechg_eol_2_reg_286pp1_it0 );
    sensitive << ( axi_last_V_1_mux_fu_403_p2 );
    sensitive << ( ap_sig_bdd_216 );

    SC_METHOD(thread_eol_phi_fu_254_p4);
    sensitive << ( eol_reg_250 );
    sensitive << ( eol_2_reg_286 );
    sensitive << ( exitcond2_reg_516 );
    sensitive << ( ap_sig_cseq_ST_pp1_stg0_fsm_4 );
    sensitive << ( ap_reg_ppiten_pp1_it1 );

    SC_METHOD(thread_exitcond1_fu_364_p2);
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( p_s_reg_182 );

    SC_METHOD(thread_exitcond2_fu_376_p2);
    sensitive << ( p_1_reg_228 );
    sensitive << ( ap_sig_cseq_ST_pp1_stg0_fsm_4 );
    sensitive << ( ap_sig_bdd_112 );
    sensitive << ( ap_reg_ppiten_pp1_it0 );

    SC_METHOD(thread_i_V_fu_370_p2);
    sensitive << ( p_s_reg_182 );

    SC_METHOD(thread_img_data_stream_0_V_ap_vld);
    sensitive << ( exitcond2_reg_516 );
    sensitive << ( ap_sig_cseq_ST_pp1_stg0_fsm_4 );
    sensitive << ( ap_sig_bdd_112 );
    sensitive << ( ap_reg_ppiten_pp1_it0 );
    sensitive << ( ap_reg_ppiten_pp1_it1 );

    SC_METHOD(thread_img_data_stream_0_V_din);
    sensitive << ( exitcond2_reg_516 );
    sensitive << ( ap_sig_cseq_ST_pp1_stg0_fsm_4 );
    sensitive << ( ap_sig_bdd_112 );
    sensitive << ( ap_reg_ppiten_pp1_it0 );
    sensitive << ( ap_reg_ppiten_pp1_it1 );
    sensitive << ( tmp_6_reg_534 );

    SC_METHOD(thread_img_data_stream_0_V_write);

    SC_METHOD(thread_img_data_stream_1_V_ap_vld);
    sensitive << ( exitcond2_reg_516 );
    sensitive << ( ap_sig_cseq_ST_pp1_stg0_fsm_4 );
    sensitive << ( ap_sig_bdd_112 );
    sensitive << ( ap_reg_ppiten_pp1_it0 );
    sensitive << ( ap_reg_ppiten_pp1_it1 );

    SC_METHOD(thread_img_data_stream_1_V_din);
    sensitive << ( exitcond2_reg_516 );
    sensitive << ( ap_sig_cseq_ST_pp1_stg0_fsm_4 );
    sensitive << ( ap_sig_bdd_112 );
    sensitive << ( ap_reg_ppiten_pp1_it0 );
    sensitive << ( ap_reg_ppiten_pp1_it1 );
    sensitive << ( tmp_7_reg_539 );

    SC_METHOD(thread_img_data_stream_1_V_write);

    SC_METHOD(thread_img_data_stream_2_V_ap_vld);
    sensitive << ( exitcond2_reg_516 );
    sensitive << ( ap_sig_cseq_ST_pp1_stg0_fsm_4 );
    sensitive << ( ap_sig_bdd_112 );
    sensitive << ( ap_reg_ppiten_pp1_it0 );
    sensitive << ( ap_reg_ppiten_pp1_it1 );

    SC_METHOD(thread_img_data_stream_2_V_din);
    sensitive << ( exitcond2_reg_516 );
    sensitive << ( ap_sig_cseq_ST_pp1_stg0_fsm_4 );
    sensitive << ( ap_sig_bdd_112 );
    sensitive << ( ap_reg_ppiten_pp1_it0 );
    sensitive << ( ap_reg_ppiten_pp1_it1 );
    sensitive << ( tmp_9_reg_544 );

    SC_METHOD(thread_img_data_stream_2_V_write);

    SC_METHOD(thread_j_V_fu_382_p2);
    sensitive << ( p_1_reg_228 );

    SC_METHOD(thread_not_sof_2_fu_397_p2);
    sensitive << ( sof_1_fu_112 );

    SC_METHOD(thread_not_tmp_6_fu_410_p2);
    sensitive << ( p_1_reg_228 );
    sensitive << ( exitcond2_fu_376_p2 );
    sensitive << ( ap_sig_cseq_ST_pp1_stg0_fsm_4 );
    sensitive << ( ap_sig_bdd_112 );
    sensitive << ( ap_reg_ppiten_pp1_it0 );

    SC_METHOD(thread_p_Val2_s_phi_fu_278_p4);
    sensitive << ( video_in_TDATA );
    sensitive << ( brmerge_fu_391_p2 );
    sensitive << ( axi_data_V_1_phi_fu_220_p4 );
    sensitive << ( ap_reg_phiprechg_p_Val2_s_reg_274pp1_it0 );
    sensitive << ( ap_sig_bdd_216 );

    SC_METHOD(thread_res_1_phi_fu_242_p4);
    sensitive << ( res_1_reg_239 );
    sensitive << ( exitcond2_reg_516 );
    sensitive << ( ap_sig_cseq_ST_pp1_stg0_fsm_4 );
    sensitive << ( ap_reg_ppiten_pp1_it1 );
    sensitive << ( res_2_reg_529 );

    SC_METHOD(thread_res_1_s_fu_436_p3);
    sensitive << ( tmp_5_fu_426_p4 );
    sensitive << ( tmp_8_fu_420_p2 );

    SC_METHOD(thread_res_2_fu_444_p3);
    sensitive << ( res_1_phi_fu_242_p4 );
    sensitive << ( eol_2_phi_fu_290_p4 );
    sensitive << ( res_1_s_fu_436_p3 );

    SC_METHOD(thread_res_4_fu_481_p2);
    sensitive << ( res_3_reg_321 );

    SC_METHOD(thread_tmp_4_fu_416_p1);
    sensitive << ( res_1_phi_fu_242_p4 );

    SC_METHOD(thread_tmp_5_fu_426_p4);
    sensitive << ( res_1_phi_fu_242_p4 );

    SC_METHOD(thread_tmp_6_fu_452_p1);
    sensitive << ( p_Val2_s_phi_fu_278_p4 );

    SC_METHOD(thread_tmp_8_fu_420_p2);
    sensitive << ( tmp_4_fu_416_p1 );
    sensitive << ( not_tmp_6_fu_410_p2 );

    SC_METHOD(thread_tmp_user_V_fu_355_p1);
    sensitive << ( video_in_TUSER );

    SC_METHOD(thread_video_in_TREADY);
    sensitive << ( video_in_TVALID );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( exitcond2_fu_376_p2 );
    sensitive << ( ap_sig_cseq_ST_pp1_stg0_fsm_4 );
    sensitive << ( brmerge_fu_391_p2 );
    sensitive << ( ap_sig_bdd_112 );
    sensitive << ( ap_reg_ppiten_pp1_it0 );
    sensitive << ( ap_sig_cseq_ST_st7_fsm_5 );
    sensitive << ( ap_sig_bdd_146 );
    sensitive << ( eol_3_reg_333 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_CS_fsm );
    sensitive << ( video_in_TVALID );
    sensitive << ( exitcond1_fu_364_p2 );
    sensitive << ( exitcond2_fu_376_p2 );
    sensitive << ( ap_sig_bdd_112 );
    sensitive << ( ap_reg_ppiten_pp1_it0 );
    sensitive << ( ap_sig_bdd_146 );
    sensitive << ( eol_3_reg_333 );
    sensitive << ( tmp_user_V_fu_355_p1 );
    sensitive << ( ap_sig_bdd_335 );

    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "0000001";
    ap_reg_ppiten_pp1_it0 = SC_LOGIC_0;
    ap_reg_ppiten_pp1_it1 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "sandbox_AXIvideo2Mat_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, AXI_video_strm_V_data_V_2, "(port)AXI_video_strm_V_data_V_2");
    sc_trace(mVcdFile, AXI_video_strm_V_data_V_2_ap_vld, "(port)AXI_video_strm_V_data_V_2_ap_vld");
    sc_trace(mVcdFile, video_in_TDATA, "(port)video_in_TDATA");
    sc_trace(mVcdFile, video_in_TVALID, "(port)video_in_TVALID");
    sc_trace(mVcdFile, video_in_TREADY, "(port)video_in_TREADY");
    sc_trace(mVcdFile, video_in_TKEEP, "(port)video_in_TKEEP");
    sc_trace(mVcdFile, video_in_TSTRB, "(port)video_in_TSTRB");
    sc_trace(mVcdFile, video_in_TUSER, "(port)video_in_TUSER");
    sc_trace(mVcdFile, video_in_TLAST, "(port)video_in_TLAST");
    sc_trace(mVcdFile, video_in_TID, "(port)video_in_TID");
    sc_trace(mVcdFile, video_in_TDEST, "(port)video_in_TDEST");
    sc_trace(mVcdFile, img_data_stream_0_V_din, "(port)img_data_stream_0_V_din");
    sc_trace(mVcdFile, img_data_stream_0_V_full_n, "(port)img_data_stream_0_V_full_n");
    sc_trace(mVcdFile, img_data_stream_0_V_write, "(port)img_data_stream_0_V_write");
    sc_trace(mVcdFile, img_data_stream_1_V_din, "(port)img_data_stream_1_V_din");
    sc_trace(mVcdFile, img_data_stream_1_V_full_n, "(port)img_data_stream_1_V_full_n");
    sc_trace(mVcdFile, img_data_stream_1_V_write, "(port)img_data_stream_1_V_write");
    sc_trace(mVcdFile, img_data_stream_2_V_din, "(port)img_data_stream_2_V_din");
    sc_trace(mVcdFile, img_data_stream_2_V_full_n, "(port)img_data_stream_2_V_full_n");
    sc_trace(mVcdFile, img_data_stream_2_V_write, "(port)img_data_stream_2_V_write");
    sc_trace(mVcdFile, img_data_stream_0_V_ap_vld, "(port)img_data_stream_0_V_ap_vld");
    sc_trace(mVcdFile, img_data_stream_1_V_ap_vld, "(port)img_data_stream_1_V_ap_vld");
    sc_trace(mVcdFile, img_data_stream_2_V_ap_vld, "(port)img_data_stream_2_V_ap_vld");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st1_fsm_0, "ap_sig_cseq_ST_st1_fsm_0");
    sc_trace(mVcdFile, ap_sig_bdd_26, "ap_sig_bdd_26");
    sc_trace(mVcdFile, eol_1_reg_206, "eol_1_reg_206");
    sc_trace(mVcdFile, axi_data_V_1_reg_217, "axi_data_V_1_reg_217");
    sc_trace(mVcdFile, p_1_reg_228, "p_1_reg_228");
    sc_trace(mVcdFile, res_1_reg_239, "res_1_reg_239");
    sc_trace(mVcdFile, eol_reg_250, "eol_reg_250");
    sc_trace(mVcdFile, axi_last_V_2_reg_262, "axi_last_V_2_reg_262");
    sc_trace(mVcdFile, p_Val2_s_reg_274, "p_Val2_s_reg_274");
    sc_trace(mVcdFile, eol_2_reg_286, "eol_2_reg_286");
    sc_trace(mVcdFile, tmp_data_V_reg_487, "tmp_data_V_reg_487");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st2_fsm_1, "ap_sig_cseq_ST_st2_fsm_1");
    sc_trace(mVcdFile, ap_sig_bdd_79, "ap_sig_bdd_79");
    sc_trace(mVcdFile, tmp_last_V_reg_495, "tmp_last_V_reg_495");
    sc_trace(mVcdFile, exitcond1_fu_364_p2, "exitcond1_fu_364_p2");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st4_fsm_3, "ap_sig_cseq_ST_st4_fsm_3");
    sc_trace(mVcdFile, ap_sig_bdd_93, "ap_sig_bdd_93");
    sc_trace(mVcdFile, i_V_fu_370_p2, "i_V_fu_370_p2");
    sc_trace(mVcdFile, i_V_reg_511, "i_V_reg_511");
    sc_trace(mVcdFile, exitcond2_fu_376_p2, "exitcond2_fu_376_p2");
    sc_trace(mVcdFile, exitcond2_reg_516, "exitcond2_reg_516");
    sc_trace(mVcdFile, ap_sig_cseq_ST_pp1_stg0_fsm_4, "ap_sig_cseq_ST_pp1_stg0_fsm_4");
    sc_trace(mVcdFile, ap_sig_bdd_104, "ap_sig_bdd_104");
    sc_trace(mVcdFile, brmerge_fu_391_p2, "brmerge_fu_391_p2");
    sc_trace(mVcdFile, ap_sig_bdd_112, "ap_sig_bdd_112");
    sc_trace(mVcdFile, ap_reg_ppiten_pp1_it0, "ap_reg_ppiten_pp1_it0");
    sc_trace(mVcdFile, ap_reg_ppiten_pp1_it1, "ap_reg_ppiten_pp1_it1");
    sc_trace(mVcdFile, j_V_fu_382_p2, "j_V_fu_382_p2");
    sc_trace(mVcdFile, res_2_fu_444_p3, "res_2_fu_444_p3");
    sc_trace(mVcdFile, res_2_reg_529, "res_2_reg_529");
    sc_trace(mVcdFile, tmp_6_fu_452_p1, "tmp_6_fu_452_p1");
    sc_trace(mVcdFile, tmp_6_reg_534, "tmp_6_reg_534");
    sc_trace(mVcdFile, tmp_7_reg_539, "tmp_7_reg_539");
    sc_trace(mVcdFile, tmp_9_reg_544, "tmp_9_reg_544");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st7_fsm_5, "ap_sig_cseq_ST_st7_fsm_5");
    sc_trace(mVcdFile, ap_sig_bdd_141, "ap_sig_bdd_141");
    sc_trace(mVcdFile, ap_sig_bdd_146, "ap_sig_bdd_146");
    sc_trace(mVcdFile, res_4_fu_481_p2, "res_4_fu_481_p2");
    sc_trace(mVcdFile, axi_last_V_3_reg_297, "axi_last_V_3_reg_297");
    sc_trace(mVcdFile, axi_last_V1_reg_162, "axi_last_V1_reg_162");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st8_fsm_6, "ap_sig_cseq_ST_st8_fsm_6");
    sc_trace(mVcdFile, ap_sig_bdd_166, "ap_sig_bdd_166");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st3_fsm_2, "ap_sig_cseq_ST_st3_fsm_2");
    sc_trace(mVcdFile, ap_sig_bdd_173, "ap_sig_bdd_173");
    sc_trace(mVcdFile, axi_data_V_3_reg_309, "axi_data_V_3_reg_309");
    sc_trace(mVcdFile, axi_data_V1_reg_172, "axi_data_V1_reg_172");
    sc_trace(mVcdFile, p_s_reg_182, "p_s_reg_182");
    sc_trace(mVcdFile, res_3_reg_321, "res_3_reg_321");
    sc_trace(mVcdFile, res_reg_193, "res_reg_193");
    sc_trace(mVcdFile, eol_1_phi_fu_209_p4, "eol_1_phi_fu_209_p4");
    sc_trace(mVcdFile, axi_data_V_1_phi_fu_220_p4, "axi_data_V_1_phi_fu_220_p4");
    sc_trace(mVcdFile, res_1_phi_fu_242_p4, "res_1_phi_fu_242_p4");
    sc_trace(mVcdFile, eol_phi_fu_254_p4, "eol_phi_fu_254_p4");
    sc_trace(mVcdFile, ap_reg_phiprechg_axi_last_V_2_reg_262pp1_it0, "ap_reg_phiprechg_axi_last_V_2_reg_262pp1_it0");
    sc_trace(mVcdFile, ap_reg_phiprechg_p_Val2_s_reg_274pp1_it0, "ap_reg_phiprechg_p_Val2_s_reg_274pp1_it0");
    sc_trace(mVcdFile, p_Val2_s_phi_fu_278_p4, "p_Val2_s_phi_fu_278_p4");
    sc_trace(mVcdFile, ap_reg_phiprechg_eol_2_reg_286pp1_it0, "ap_reg_phiprechg_eol_2_reg_286pp1_it0");
    sc_trace(mVcdFile, eol_2_phi_fu_290_p4, "eol_2_phi_fu_290_p4");
    sc_trace(mVcdFile, axi_last_V_1_mux_fu_403_p2, "axi_last_V_1_mux_fu_403_p2");
    sc_trace(mVcdFile, eol_3_reg_333, "eol_3_reg_333");
    sc_trace(mVcdFile, sof_1_fu_112, "sof_1_fu_112");
    sc_trace(mVcdFile, not_sof_2_fu_397_p2, "not_sof_2_fu_397_p2");
    sc_trace(mVcdFile, tmp_4_fu_416_p1, "tmp_4_fu_416_p1");
    sc_trace(mVcdFile, not_tmp_6_fu_410_p2, "not_tmp_6_fu_410_p2");
    sc_trace(mVcdFile, tmp_5_fu_426_p4, "tmp_5_fu_426_p4");
    sc_trace(mVcdFile, tmp_8_fu_420_p2, "tmp_8_fu_420_p2");
    sc_trace(mVcdFile, res_1_s_fu_436_p3, "res_1_s_fu_436_p3");
    sc_trace(mVcdFile, tmp_user_V_fu_355_p1, "tmp_user_V_fu_355_p1");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_sig_bdd_335, "ap_sig_bdd_335");
    sc_trace(mVcdFile, ap_sig_bdd_111, "ap_sig_bdd_111");
    sc_trace(mVcdFile, ap_sig_bdd_200, "ap_sig_bdd_200");
    sc_trace(mVcdFile, ap_sig_bdd_124, "ap_sig_bdd_124");
    sc_trace(mVcdFile, ap_sig_bdd_216, "ap_sig_bdd_216");
#endif

    }
}

sandbox_AXIvideo2Mat::~sandbox_AXIvideo2Mat() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void sandbox_AXIvideo2Mat::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_st1_fsm_0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) && 
                    !esl_seteq<1,1,1>(exitcond1_fu_364_p2.read(), ap_const_lv1_0))) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp1_it0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp1_stg0_fsm_4.read()) && 
             !(ap_sig_bdd_112.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read())) && 
             !esl_seteq<1,1,1>(exitcond2_fu_376_p2.read(), ap_const_lv1_0))) {
            ap_reg_ppiten_pp1_it0 = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) && 
                    esl_seteq<1,1,1>(exitcond1_fu_364_p2.read(), ap_const_lv1_0))) {
            ap_reg_ppiten_pp1_it0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp1_it1 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp1_stg0_fsm_4.read()) && 
             esl_seteq<1,1,1>(exitcond2_fu_376_p2.read(), ap_const_lv1_0) && 
             !(ap_sig_bdd_112.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read())))) {
            ap_reg_ppiten_pp1_it1 = ap_const_logic_1;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) && 
                     esl_seteq<1,1,1>(exitcond1_fu_364_p2.read(), ap_const_lv1_0)) || 
                    (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp1_stg0_fsm_4.read()) && 
                     !(ap_sig_bdd_112.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read())) && 
                     !esl_seteq<1,1,1>(exitcond2_fu_376_p2.read(), ap_const_lv1_0)))) {
            ap_reg_ppiten_pp1_it1 = ap_const_logic_0;
        }
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read())) {
        axi_data_V1_reg_172 = tmp_data_V_reg_487.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_6.read())) {
        axi_data_V1_reg_172 = axi_data_V_3_reg_309.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp1_stg0_fsm_4.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it1.read()) && 
         !(ap_sig_bdd_112.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read())) && 
         esl_seteq<1,1,1>(exitcond2_reg_516.read(), ap_const_lv1_0))) {
        axi_data_V_1_reg_217 = p_Val2_s_reg_274.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) && 
                esl_seteq<1,1,1>(exitcond1_fu_364_p2.read(), ap_const_lv1_0))) {
        axi_data_V_1_reg_217 = axi_data_V1_reg_172.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp1_stg0_fsm_4.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read()) && 
         !(ap_sig_bdd_112.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read())) && 
         !esl_seteq<1,1,1>(exitcond2_fu_376_p2.read(), ap_const_lv1_0))) {
        axi_data_V_3_reg_309 = axi_data_V_1_phi_fu_220_p4.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_5.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, eol_3_reg_333.read()) && 
                !ap_sig_bdd_146.read())) {
        axi_data_V_3_reg_309 = video_in_TDATA.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read())) {
        axi_last_V1_reg_162 = tmp_last_V_reg_495.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_6.read())) {
        axi_last_V1_reg_162 = axi_last_V_3_reg_297.read();
    }
    if (ap_sig_bdd_124.read()) {
        if (ap_sig_bdd_200.read()) {
            axi_last_V_2_reg_262 = eol_1_phi_fu_209_p4.read();
        } else if (ap_sig_bdd_111.read()) {
            axi_last_V_2_reg_262 = video_in_TLAST.read();
        } else if (esl_seteq<1,1,1>(ap_true, ap_true)) {
            axi_last_V_2_reg_262 = ap_reg_phiprechg_axi_last_V_2_reg_262pp1_it0.read();
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp1_stg0_fsm_4.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read()) && 
         !(ap_sig_bdd_112.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read())) && 
         !esl_seteq<1,1,1>(exitcond2_fu_376_p2.read(), ap_const_lv1_0))) {
        axi_last_V_3_reg_297 = eol_1_phi_fu_209_p4.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_5.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, eol_3_reg_333.read()) && 
                !ap_sig_bdd_146.read())) {
        axi_last_V_3_reg_297 = video_in_TLAST.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp1_stg0_fsm_4.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it1.read()) && 
         !(ap_sig_bdd_112.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read())) && 
         esl_seteq<1,1,1>(exitcond2_reg_516.read(), ap_const_lv1_0))) {
        eol_1_reg_206 = axi_last_V_2_reg_262.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) && 
                esl_seteq<1,1,1>(exitcond1_fu_364_p2.read(), ap_const_lv1_0))) {
        eol_1_reg_206 = axi_last_V1_reg_162.read();
    }
    if (ap_sig_bdd_124.read()) {
        if (ap_sig_bdd_200.read()) {
            eol_2_reg_286 = axi_last_V_1_mux_fu_403_p2.read();
        } else if (ap_sig_bdd_111.read()) {
            eol_2_reg_286 = video_in_TLAST.read();
        } else if (esl_seteq<1,1,1>(ap_true, ap_true)) {
            eol_2_reg_286 = ap_reg_phiprechg_eol_2_reg_286pp1_it0.read();
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp1_stg0_fsm_4.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read()) && 
         !(ap_sig_bdd_112.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read())) && 
         !esl_seteq<1,1,1>(exitcond2_fu_376_p2.read(), ap_const_lv1_0))) {
        eol_3_reg_333 = eol_phi_fu_254_p4.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_5.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, eol_3_reg_333.read()) && 
                !ap_sig_bdd_146.read())) {
        eol_3_reg_333 = video_in_TLAST.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp1_stg0_fsm_4.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it1.read()) && 
         !(ap_sig_bdd_112.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read())) && 
         esl_seteq<1,1,1>(exitcond2_reg_516.read(), ap_const_lv1_0))) {
        eol_reg_250 = eol_2_reg_286.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) && 
                esl_seteq<1,1,1>(exitcond1_fu_364_p2.read(), ap_const_lv1_0))) {
        eol_reg_250 = ap_const_lv1_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp1_stg0_fsm_4.read()) && 
         esl_seteq<1,1,1>(exitcond2_fu_376_p2.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read()) && 
         !(ap_sig_bdd_112.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read())))) {
        p_1_reg_228 = j_V_fu_382_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) && 
                esl_seteq<1,1,1>(exitcond1_fu_364_p2.read(), ap_const_lv1_0))) {
        p_1_reg_228 = ap_const_lv11_0;
    }
    if (ap_sig_bdd_124.read()) {
        if (ap_sig_bdd_200.read()) {
            p_Val2_s_reg_274 = axi_data_V_1_phi_fu_220_p4.read();
        } else if (ap_sig_bdd_111.read()) {
            p_Val2_s_reg_274 = video_in_TDATA.read();
        } else if (esl_seteq<1,1,1>(ap_true, ap_true)) {
            p_Val2_s_reg_274 = ap_reg_phiprechg_p_Val2_s_reg_274pp1_it0.read();
        }
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read())) {
        p_s_reg_182 = ap_const_lv11_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_6.read())) {
        p_s_reg_182 = i_V_reg_511.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp1_stg0_fsm_4.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it1.read()) && 
         !(ap_sig_bdd_112.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read())) && 
         esl_seteq<1,1,1>(exitcond2_reg_516.read(), ap_const_lv1_0))) {
        res_1_reg_239 = res_2_reg_529.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) && 
                esl_seteq<1,1,1>(exitcond1_fu_364_p2.read(), ap_const_lv1_0))) {
        res_1_reg_239 = res_reg_193.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp1_stg0_fsm_4.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read()) && 
         !(ap_sig_bdd_112.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read())) && 
         !esl_seteq<1,1,1>(exitcond2_fu_376_p2.read(), ap_const_lv1_0))) {
        res_3_reg_321 = res_1_phi_fu_242_p4.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_5.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, eol_3_reg_333.read()) && 
                !ap_sig_bdd_146.read())) {
        res_3_reg_321 = res_4_fu_481_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read())) {
        res_reg_193 = ap_const_lv32_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_6.read())) {
        res_reg_193 = res_3_reg_321.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp1_stg0_fsm_4.read()) && 
         esl_seteq<1,1,1>(exitcond2_fu_376_p2.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read()) && 
         !(ap_sig_bdd_112.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read())))) {
        sof_1_fu_112 = ap_const_lv1_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read())) {
        sof_1_fu_112 = ap_const_lv1_1;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp1_stg0_fsm_4.read()) && !(ap_sig_bdd_112.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read())))) {
        exitcond2_reg_516 = exitcond2_fu_376_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read())) {
        i_V_reg_511 = i_V_fu_370_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp1_stg0_fsm_4.read()) && esl_seteq<1,1,1>(exitcond2_fu_376_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read()) && !(ap_sig_bdd_112.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read())))) {
        res_2_reg_529 = res_2_fu_444_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp1_stg0_fsm_4.read()) && esl_seteq<1,1,1>(exitcond2_fu_376_p2.read(), ap_const_lv1_0) && !(ap_sig_bdd_112.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read())))) {
        tmp_6_reg_534 = tmp_6_fu_452_p1.read();
        tmp_7_reg_539 = p_Val2_s_phi_fu_278_p4.read().range(15, 8);
        tmp_9_reg_544 = p_Val2_s_phi_fu_278_p4.read().range(23, 16);
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && !esl_seteq<1,1,1>(video_in_TVALID.read(), ap_const_logic_0))) {
        tmp_data_V_reg_487 = video_in_TDATA.read();
        tmp_last_V_reg_495 = video_in_TLAST.read();
    }
}

void sandbox_AXIvideo2Mat::thread_AXI_video_strm_V_data_V_2() {
    AXI_video_strm_V_data_V_2 = res_reg_193.read();
}

void sandbox_AXIvideo2Mat::thread_AXI_video_strm_V_data_V_2_ap_vld() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) && 
         !esl_seteq<1,1,1>(exitcond1_fu_364_p2.read(), ap_const_lv1_0))) {
        AXI_video_strm_V_data_V_2_ap_vld = ap_const_logic_1;
    } else {
        AXI_video_strm_V_data_V_2_ap_vld = ap_const_logic_0;
    }
}

void sandbox_AXIvideo2Mat::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_done_reg.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) && 
          !esl_seteq<1,1,1>(exitcond1_fu_364_p2.read(), ap_const_lv1_0)))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void sandbox_AXIvideo2Mat::thread_ap_idle() {
    if ((!esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void sandbox_AXIvideo2Mat::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) && 
         !esl_seteq<1,1,1>(exitcond1_fu_364_p2.read(), ap_const_lv1_0))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void sandbox_AXIvideo2Mat::thread_ap_reg_phiprechg_axi_last_V_2_reg_262pp1_it0() {
    ap_reg_phiprechg_axi_last_V_2_reg_262pp1_it0 =  (sc_lv<1>) ("X");
}

void sandbox_AXIvideo2Mat::thread_ap_reg_phiprechg_eol_2_reg_286pp1_it0() {
    ap_reg_phiprechg_eol_2_reg_286pp1_it0 =  (sc_lv<1>) ("X");
}

void sandbox_AXIvideo2Mat::thread_ap_reg_phiprechg_p_Val2_s_reg_274pp1_it0() {
    ap_reg_phiprechg_p_Val2_s_reg_274pp1_it0 =  (sc_lv<24>) ("XXXXXXXXXXXXXXXXXXXXXXXX");
}

void sandbox_AXIvideo2Mat::thread_ap_sig_bdd_104() {
    ap_sig_bdd_104 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(4, 4));
}

void sandbox_AXIvideo2Mat::thread_ap_sig_bdd_111() {
    ap_sig_bdd_111 = (esl_seteq<1,1,1>(exitcond2_fu_376_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_lv1_0, brmerge_fu_391_p2.read()));
}

void sandbox_AXIvideo2Mat::thread_ap_sig_bdd_112() {
    ap_sig_bdd_112 = (esl_seteq<1,1,1>(video_in_TVALID.read(), ap_const_logic_0) && esl_seteq<1,1,1>(exitcond2_fu_376_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_lv1_0, brmerge_fu_391_p2.read()));
}

void sandbox_AXIvideo2Mat::thread_ap_sig_bdd_124() {
    ap_sig_bdd_124 = (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp1_stg0_fsm_4.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read()) && !(ap_sig_bdd_112.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read())));
}

void sandbox_AXIvideo2Mat::thread_ap_sig_bdd_141() {
    ap_sig_bdd_141 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(5, 5));
}

void sandbox_AXIvideo2Mat::thread_ap_sig_bdd_146() {
    ap_sig_bdd_146 = (esl_seteq<1,1,1>(video_in_TVALID.read(), ap_const_logic_0) && esl_seteq<1,1,1>(ap_const_lv1_0, eol_3_reg_333.read()));
}

void sandbox_AXIvideo2Mat::thread_ap_sig_bdd_166() {
    ap_sig_bdd_166 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(6, 6));
}

void sandbox_AXIvideo2Mat::thread_ap_sig_bdd_173() {
    ap_sig_bdd_173 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(2, 2));
}

void sandbox_AXIvideo2Mat::thread_ap_sig_bdd_200() {
    ap_sig_bdd_200 = (esl_seteq<1,1,1>(exitcond2_fu_376_p2.read(), ap_const_lv1_0) && !esl_seteq<1,1,1>(ap_const_lv1_0, brmerge_fu_391_p2.read()));
}

void sandbox_AXIvideo2Mat::thread_ap_sig_bdd_216() {
    ap_sig_bdd_216 = (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp1_stg0_fsm_4.read()) && esl_seteq<1,1,1>(exitcond2_fu_376_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read()));
}

void sandbox_AXIvideo2Mat::thread_ap_sig_bdd_26() {
    ap_sig_bdd_26 = esl_seteq<1,1,1>(ap_CS_fsm.read().range(0, 0), ap_const_lv1_1);
}

void sandbox_AXIvideo2Mat::thread_ap_sig_bdd_335() {
    ap_sig_bdd_335 = (esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1));
}

void sandbox_AXIvideo2Mat::thread_ap_sig_bdd_79() {
    ap_sig_bdd_79 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(1, 1));
}

void sandbox_AXIvideo2Mat::thread_ap_sig_bdd_93() {
    ap_sig_bdd_93 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(3, 3));
}

void sandbox_AXIvideo2Mat::thread_ap_sig_cseq_ST_pp1_stg0_fsm_4() {
    if (ap_sig_bdd_104.read()) {
        ap_sig_cseq_ST_pp1_stg0_fsm_4 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_pp1_stg0_fsm_4 = ap_const_logic_0;
    }
}

void sandbox_AXIvideo2Mat::thread_ap_sig_cseq_ST_st1_fsm_0() {
    if (ap_sig_bdd_26.read()) {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    }
}

void sandbox_AXIvideo2Mat::thread_ap_sig_cseq_ST_st2_fsm_1() {
    if (ap_sig_bdd_79.read()) {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_0;
    }
}

void sandbox_AXIvideo2Mat::thread_ap_sig_cseq_ST_st3_fsm_2() {
    if (ap_sig_bdd_173.read()) {
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_0;
    }
}

void sandbox_AXIvideo2Mat::thread_ap_sig_cseq_ST_st4_fsm_3() {
    if (ap_sig_bdd_93.read()) {
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_0;
    }
}

void sandbox_AXIvideo2Mat::thread_ap_sig_cseq_ST_st7_fsm_5() {
    if (ap_sig_bdd_141.read()) {
        ap_sig_cseq_ST_st7_fsm_5 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st7_fsm_5 = ap_const_logic_0;
    }
}

void sandbox_AXIvideo2Mat::thread_ap_sig_cseq_ST_st8_fsm_6() {
    if (ap_sig_bdd_166.read()) {
        ap_sig_cseq_ST_st8_fsm_6 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st8_fsm_6 = ap_const_logic_0;
    }
}

void sandbox_AXIvideo2Mat::thread_axi_data_V_1_phi_fu_220_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp1_stg0_fsm_4.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it1.read()) && 
         esl_seteq<1,1,1>(exitcond2_reg_516.read(), ap_const_lv1_0))) {
        axi_data_V_1_phi_fu_220_p4 = p_Val2_s_reg_274.read();
    } else {
        axi_data_V_1_phi_fu_220_p4 = axi_data_V_1_reg_217.read();
    }
}

void sandbox_AXIvideo2Mat::thread_axi_last_V_1_mux_fu_403_p2() {
    axi_last_V_1_mux_fu_403_p2 = (eol_1_phi_fu_209_p4.read() | not_sof_2_fu_397_p2.read());
}

void sandbox_AXIvideo2Mat::thread_brmerge_fu_391_p2() {
    brmerge_fu_391_p2 = (sof_1_fu_112.read() | eol_phi_fu_254_p4.read());
}

void sandbox_AXIvideo2Mat::thread_eol_1_phi_fu_209_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp1_stg0_fsm_4.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it1.read()) && 
         esl_seteq<1,1,1>(exitcond2_reg_516.read(), ap_const_lv1_0))) {
        eol_1_phi_fu_209_p4 = axi_last_V_2_reg_262.read();
    } else {
        eol_1_phi_fu_209_p4 = eol_1_reg_206.read();
    }
}

void sandbox_AXIvideo2Mat::thread_eol_2_phi_fu_290_p4() {
    if (ap_sig_bdd_216.read()) {
        if (!esl_seteq<1,1,1>(ap_const_lv1_0, brmerge_fu_391_p2.read())) {
            eol_2_phi_fu_290_p4 = axi_last_V_1_mux_fu_403_p2.read();
        } else if (esl_seteq<1,1,1>(ap_const_lv1_0, brmerge_fu_391_p2.read())) {
            eol_2_phi_fu_290_p4 = video_in_TLAST.read();
        } else {
            eol_2_phi_fu_290_p4 = ap_reg_phiprechg_eol_2_reg_286pp1_it0.read();
        }
    } else {
        eol_2_phi_fu_290_p4 = ap_reg_phiprechg_eol_2_reg_286pp1_it0.read();
    }
}

void sandbox_AXIvideo2Mat::thread_eol_phi_fu_254_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp1_stg0_fsm_4.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it1.read()) && 
         esl_seteq<1,1,1>(exitcond2_reg_516.read(), ap_const_lv1_0))) {
        eol_phi_fu_254_p4 = eol_2_reg_286.read();
    } else {
        eol_phi_fu_254_p4 = eol_reg_250.read();
    }
}

void sandbox_AXIvideo2Mat::thread_exitcond1_fu_364_p2() {
    exitcond1_fu_364_p2 = (!p_s_reg_182.read().is_01() || !ap_const_lv11_780.is_01())? sc_lv<1>(): sc_lv<1>(p_s_reg_182.read() == ap_const_lv11_780);
}

void sandbox_AXIvideo2Mat::thread_exitcond2_fu_376_p2() {
    exitcond2_fu_376_p2 = (!p_1_reg_228.read().is_01() || !ap_const_lv11_438.is_01())? sc_lv<1>(): sc_lv<1>(p_1_reg_228.read() == ap_const_lv11_438);
}

void sandbox_AXIvideo2Mat::thread_i_V_fu_370_p2() {
    i_V_fu_370_p2 = (!p_s_reg_182.read().is_01() || !ap_const_lv11_1.is_01())? sc_lv<11>(): (sc_biguint<11>(p_s_reg_182.read()) + sc_biguint<11>(ap_const_lv11_1));
}

void sandbox_AXIvideo2Mat::thread_img_data_stream_0_V_ap_vld() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp1_stg0_fsm_4.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it1.read()) && 
         !(ap_sig_bdd_112.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read())) && 
         esl_seteq<1,1,1>(exitcond2_reg_516.read(), ap_const_lv1_0))) {
        img_data_stream_0_V_ap_vld = ap_const_logic_1;
    } else {
        img_data_stream_0_V_ap_vld = ap_const_logic_0;
    }
}

void sandbox_AXIvideo2Mat::thread_img_data_stream_0_V_din() {
    img_data_stream_0_V_din = tmp_6_reg_534.read();
}

void sandbox_AXIvideo2Mat::thread_img_data_stream_0_V_write() {
    img_data_stream_0_V_write = ap_const_logic_0;
}

void sandbox_AXIvideo2Mat::thread_img_data_stream_1_V_ap_vld() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp1_stg0_fsm_4.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it1.read()) && 
         !(ap_sig_bdd_112.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read())) && 
         esl_seteq<1,1,1>(exitcond2_reg_516.read(), ap_const_lv1_0))) {
        img_data_stream_1_V_ap_vld = ap_const_logic_1;
    } else {
        img_data_stream_1_V_ap_vld = ap_const_logic_0;
    }
}

void sandbox_AXIvideo2Mat::thread_img_data_stream_1_V_din() {
    img_data_stream_1_V_din = tmp_7_reg_539.read();
}

void sandbox_AXIvideo2Mat::thread_img_data_stream_1_V_write() {
    img_data_stream_1_V_write = ap_const_logic_0;
}

void sandbox_AXIvideo2Mat::thread_img_data_stream_2_V_ap_vld() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp1_stg0_fsm_4.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it1.read()) && 
         !(ap_sig_bdd_112.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read())) && 
         esl_seteq<1,1,1>(exitcond2_reg_516.read(), ap_const_lv1_0))) {
        img_data_stream_2_V_ap_vld = ap_const_logic_1;
    } else {
        img_data_stream_2_V_ap_vld = ap_const_logic_0;
    }
}

void sandbox_AXIvideo2Mat::thread_img_data_stream_2_V_din() {
    img_data_stream_2_V_din = tmp_9_reg_544.read();
}

void sandbox_AXIvideo2Mat::thread_img_data_stream_2_V_write() {
    img_data_stream_2_V_write = ap_const_logic_0;
}

void sandbox_AXIvideo2Mat::thread_j_V_fu_382_p2() {
    j_V_fu_382_p2 = (!p_1_reg_228.read().is_01() || !ap_const_lv11_1.is_01())? sc_lv<11>(): (sc_biguint<11>(p_1_reg_228.read()) + sc_biguint<11>(ap_const_lv11_1));
}

void sandbox_AXIvideo2Mat::thread_not_sof_2_fu_397_p2() {
    not_sof_2_fu_397_p2 = (sof_1_fu_112.read() ^ ap_const_lv1_1);
}

void sandbox_AXIvideo2Mat::thread_not_tmp_6_fu_410_p2() {
    not_tmp_6_fu_410_p2 = (!p_1_reg_228.read().is_01() || !ap_const_lv11_437.is_01())? sc_lv<1>(): sc_lv<1>(p_1_reg_228.read() != ap_const_lv11_437);
}

void sandbox_AXIvideo2Mat::thread_p_Val2_s_phi_fu_278_p4() {
    if (ap_sig_bdd_216.read()) {
        if (!esl_seteq<1,1,1>(ap_const_lv1_0, brmerge_fu_391_p2.read())) {
            p_Val2_s_phi_fu_278_p4 = axi_data_V_1_phi_fu_220_p4.read();
        } else if (esl_seteq<1,1,1>(ap_const_lv1_0, brmerge_fu_391_p2.read())) {
            p_Val2_s_phi_fu_278_p4 = video_in_TDATA.read();
        } else {
            p_Val2_s_phi_fu_278_p4 = ap_reg_phiprechg_p_Val2_s_reg_274pp1_it0.read();
        }
    } else {
        p_Val2_s_phi_fu_278_p4 = ap_reg_phiprechg_p_Val2_s_reg_274pp1_it0.read();
    }
}

void sandbox_AXIvideo2Mat::thread_res_1_phi_fu_242_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp1_stg0_fsm_4.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it1.read()) && 
         esl_seteq<1,1,1>(exitcond2_reg_516.read(), ap_const_lv1_0))) {
        res_1_phi_fu_242_p4 = res_2_reg_529.read();
    } else {
        res_1_phi_fu_242_p4 = res_1_reg_239.read();
    }
}

void sandbox_AXIvideo2Mat::thread_res_1_s_fu_436_p3() {
    res_1_s_fu_436_p3 = esl_concat<31,1>(tmp_5_fu_426_p4.read(), tmp_8_fu_420_p2.read());
}

void sandbox_AXIvideo2Mat::thread_res_2_fu_444_p3() {
    res_2_fu_444_p3 = (!eol_2_phi_fu_290_p4.read()[0].is_01())? sc_lv<32>(): ((eol_2_phi_fu_290_p4.read()[0].to_bool())? res_1_s_fu_436_p3.read(): res_1_phi_fu_242_p4.read());
}

void sandbox_AXIvideo2Mat::thread_res_4_fu_481_p2() {
    res_4_fu_481_p2 = (res_3_reg_321.read() | ap_const_lv32_2);
}

void sandbox_AXIvideo2Mat::thread_tmp_4_fu_416_p1() {
    tmp_4_fu_416_p1 = res_1_phi_fu_242_p4.read().range(1-1, 0);
}

void sandbox_AXIvideo2Mat::thread_tmp_5_fu_426_p4() {
    tmp_5_fu_426_p4 = res_1_phi_fu_242_p4.read().range(31, 1);
}

void sandbox_AXIvideo2Mat::thread_tmp_6_fu_452_p1() {
    tmp_6_fu_452_p1 = p_Val2_s_phi_fu_278_p4.read().range(8-1, 0);
}

void sandbox_AXIvideo2Mat::thread_tmp_8_fu_420_p2() {
    tmp_8_fu_420_p2 = (tmp_4_fu_416_p1.read() | not_tmp_6_fu_410_p2.read());
}

void sandbox_AXIvideo2Mat::thread_tmp_user_V_fu_355_p1() {
    tmp_user_V_fu_355_p1 = video_in_TUSER.read();
}

void sandbox_AXIvideo2Mat::thread_video_in_TREADY() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
          !esl_seteq<1,1,1>(video_in_TVALID.read(), ap_const_logic_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_5.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, eol_3_reg_333.read()) && 
          !ap_sig_bdd_146.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp1_stg0_fsm_4.read()) && 
          esl_seteq<1,1,1>(exitcond2_fu_376_p2.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, brmerge_fu_391_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read()) && 
          !(ap_sig_bdd_112.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read()))))) {
        video_in_TREADY = ap_const_logic_1;
    } else {
        video_in_TREADY = ap_const_logic_0;
    }
}

void sandbox_AXIvideo2Mat::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if (!ap_sig_bdd_335.read()) {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            } else {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            }
            break;
        case 2 : 
            if ((!esl_seteq<1,1,1>(video_in_TVALID.read(), ap_const_logic_0) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_user_V_fu_355_p1.read()))) {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            } else if ((!esl_seteq<1,1,1>(video_in_TVALID.read(), ap_const_logic_0) && !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_user_V_fu_355_p1.read()))) {
                ap_NS_fsm = ap_ST_st3_fsm_2;
            } else {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_st4_fsm_3;
            break;
        case 8 : 
            if (!esl_seteq<1,1,1>(exitcond1_fu_364_p2.read(), ap_const_lv1_0)) {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            } else {
                ap_NS_fsm = ap_ST_pp1_stg0_fsm_4;
            }
            break;
        case 16 : 
            if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read()) && !(ap_sig_bdd_112.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read())) && !esl_seteq<1,1,1>(exitcond2_fu_376_p2.read(), ap_const_lv1_0))) {
                ap_NS_fsm = ap_ST_pp1_stg0_fsm_4;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read()) && !(ap_sig_bdd_112.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read())) && !esl_seteq<1,1,1>(exitcond2_fu_376_p2.read(), ap_const_lv1_0))) {
                ap_NS_fsm = ap_ST_st7_fsm_5;
            } else {
                ap_NS_fsm = ap_ST_pp1_stg0_fsm_4;
            }
            break;
        case 32 : 
            if ((esl_seteq<1,1,1>(ap_const_lv1_0, eol_3_reg_333.read()) && !ap_sig_bdd_146.read())) {
                ap_NS_fsm = ap_ST_st7_fsm_5;
            } else if ((!ap_sig_bdd_146.read() && !esl_seteq<1,1,1>(ap_const_lv1_0, eol_3_reg_333.read()))) {
                ap_NS_fsm = ap_ST_st8_fsm_6;
            } else {
                ap_NS_fsm = ap_ST_st7_fsm_5;
            }
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_st4_fsm_3;
            break;
        default : 
            ap_NS_fsm = "XXXXXXX";
            break;
    }
}

}

