// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.4
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xsandbox.h"

extern XSandbox_Config XSandbox_ConfigTable[];

XSandbox_Config *XSandbox_LookupConfig(u16 DeviceId) {
	XSandbox_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XSANDBOX_NUM_INSTANCES; Index++) {
		if (XSandbox_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XSandbox_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XSandbox_Initialize(XSandbox *InstancePtr, u16 DeviceId) {
	XSandbox_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XSandbox_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XSandbox_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

