// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.4
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xsandbox.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XSandbox_CfgInitialize(XSandbox *InstancePtr, XSandbox_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Control_bus_BaseAddress = ConfigPtr->Control_bus_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XSandbox_Start(XSandbox *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSandbox_ReadReg(InstancePtr->Control_bus_BaseAddress, XSANDBOX_CONTROL_BUS_ADDR_AP_CTRL) & 0x80;
    XSandbox_WriteReg(InstancePtr->Control_bus_BaseAddress, XSANDBOX_CONTROL_BUS_ADDR_AP_CTRL, Data | 0x01);
}

u32 XSandbox_IsDone(XSandbox *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSandbox_ReadReg(InstancePtr->Control_bus_BaseAddress, XSANDBOX_CONTROL_BUS_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XSandbox_IsIdle(XSandbox *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSandbox_ReadReg(InstancePtr->Control_bus_BaseAddress, XSANDBOX_CONTROL_BUS_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XSandbox_IsReady(XSandbox *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSandbox_ReadReg(InstancePtr->Control_bus_BaseAddress, XSANDBOX_CONTROL_BUS_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XSandbox_EnableAutoRestart(XSandbox *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSandbox_WriteReg(InstancePtr->Control_bus_BaseAddress, XSANDBOX_CONTROL_BUS_ADDR_AP_CTRL, 0x80);
}

void XSandbox_DisableAutoRestart(XSandbox *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSandbox_WriteReg(InstancePtr->Control_bus_BaseAddress, XSANDBOX_CONTROL_BUS_ADDR_AP_CTRL, 0);
}

void XSandbox_Set_rows(XSandbox *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSandbox_WriteReg(InstancePtr->Control_bus_BaseAddress, XSANDBOX_CONTROL_BUS_ADDR_ROWS_DATA, Data);
}

u32 XSandbox_Get_rows(XSandbox *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSandbox_ReadReg(InstancePtr->Control_bus_BaseAddress, XSANDBOX_CONTROL_BUS_ADDR_ROWS_DATA);
    return Data;
}

void XSandbox_Set_cols(XSandbox *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSandbox_WriteReg(InstancePtr->Control_bus_BaseAddress, XSANDBOX_CONTROL_BUS_ADDR_COLS_DATA, Data);
}

u32 XSandbox_Get_cols(XSandbox *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSandbox_ReadReg(InstancePtr->Control_bus_BaseAddress, XSANDBOX_CONTROL_BUS_ADDR_COLS_DATA);
    return Data;
}

void XSandbox_InterruptGlobalEnable(XSandbox *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSandbox_WriteReg(InstancePtr->Control_bus_BaseAddress, XSANDBOX_CONTROL_BUS_ADDR_GIE, 1);
}

void XSandbox_InterruptGlobalDisable(XSandbox *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSandbox_WriteReg(InstancePtr->Control_bus_BaseAddress, XSANDBOX_CONTROL_BUS_ADDR_GIE, 0);
}

void XSandbox_InterruptEnable(XSandbox *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XSandbox_ReadReg(InstancePtr->Control_bus_BaseAddress, XSANDBOX_CONTROL_BUS_ADDR_IER);
    XSandbox_WriteReg(InstancePtr->Control_bus_BaseAddress, XSANDBOX_CONTROL_BUS_ADDR_IER, Register | Mask);
}

void XSandbox_InterruptDisable(XSandbox *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XSandbox_ReadReg(InstancePtr->Control_bus_BaseAddress, XSANDBOX_CONTROL_BUS_ADDR_IER);
    XSandbox_WriteReg(InstancePtr->Control_bus_BaseAddress, XSANDBOX_CONTROL_BUS_ADDR_IER, Register & (~Mask));
}

void XSandbox_InterruptClear(XSandbox *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSandbox_WriteReg(InstancePtr->Control_bus_BaseAddress, XSANDBOX_CONTROL_BUS_ADDR_ISR, Mask);
}

u32 XSandbox_InterruptGetEnabled(XSandbox *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XSandbox_ReadReg(InstancePtr->Control_bus_BaseAddress, XSANDBOX_CONTROL_BUS_ADDR_IER);
}

u32 XSandbox_InterruptGetStatus(XSandbox *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XSandbox_ReadReg(InstancePtr->Control_bus_BaseAddress, XSANDBOX_CONTROL_BUS_ADDR_ISR);
}

