// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.4
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#ifndef XSANDBOX_H
#define XSANDBOX_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xsandbox_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Control_bus_BaseAddress;
} XSandbox_Config;
#endif

typedef struct {
    u32 Control_bus_BaseAddress;
    u32 IsReady;
} XSandbox;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XSandbox_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XSandbox_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XSandbox_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XSandbox_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XSandbox_Initialize(XSandbox *InstancePtr, u16 DeviceId);
XSandbox_Config* XSandbox_LookupConfig(u16 DeviceId);
int XSandbox_CfgInitialize(XSandbox *InstancePtr, XSandbox_Config *ConfigPtr);
#else
int XSandbox_Initialize(XSandbox *InstancePtr, const char* InstanceName);
int XSandbox_Release(XSandbox *InstancePtr);
#endif

void XSandbox_Start(XSandbox *InstancePtr);
u32 XSandbox_IsDone(XSandbox *InstancePtr);
u32 XSandbox_IsIdle(XSandbox *InstancePtr);
u32 XSandbox_IsReady(XSandbox *InstancePtr);
void XSandbox_EnableAutoRestart(XSandbox *InstancePtr);
void XSandbox_DisableAutoRestart(XSandbox *InstancePtr);

void XSandbox_Set_rows(XSandbox *InstancePtr, u32 Data);
u32 XSandbox_Get_rows(XSandbox *InstancePtr);
void XSandbox_Set_cols(XSandbox *InstancePtr, u32 Data);
u32 XSandbox_Get_cols(XSandbox *InstancePtr);

void XSandbox_InterruptGlobalEnable(XSandbox *InstancePtr);
void XSandbox_InterruptGlobalDisable(XSandbox *InstancePtr);
void XSandbox_InterruptEnable(XSandbox *InstancePtr, u32 Mask);
void XSandbox_InterruptDisable(XSandbox *InstancePtr, u32 Mask);
void XSandbox_InterruptClear(XSandbox *InstancePtr, u32 Mask);
u32 XSandbox_InterruptGetEnabled(XSandbox *InstancePtr);
u32 XSandbox_InterruptGetStatus(XSandbox *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
