#
# Vivado (TM) v2014.4 (64-bit)
#
# build.tcl: Tcl script for re-creating project 'project_2'
#
# Generated by Vivado on Wed Jan 06 13:10:23 EST 2016
# IP Build 1070531 on Tue Nov 18 01:10:18 MST 2014
#
# This file contains the Vivado Tcl commands for re-creating the project to the state*
# when this script was generated. In order to re-create the project, please source this
# file in the Vivado Tcl Shell.
#
# * Note that the runs in the created project will be configured the same way as the
#   original project, however they will not be launched automatically. To regenerate the
#   run results please launch the synthesis/implementation runs as needed.
#
#*****************************************************************************************
# NOTE: In order to use this script for source control purposes, please make sure that the
#       following files are added to the source control system:-
#
# 1. This project restoration tcl script (build.tcl) that was generated.
#
# 2. The following source(s) files that were local or imported into the original project.
#    (Please see the '$orig_proj_dir' and '$origin_dir' variable setting below at the start of the script)
#
#    "/home/jdanner3/VIP/zedboard-baseline/fpga/project_2/project_2.srcs/sources_1/bd/base_zynq_design/base_zynq_design.bd"
#    "/home/jdanner3/VIP/zedboard-baseline/fpga/project_2/project_2.srcs/sources_1/imports/sources_1/bd/base_zynq_design/hdl/base_zynq_design_wrapper.vhd"
#    "/home/jdanner3/VIP/zedboard-baseline/fpga/project_2/project_2.srcs/sources_1/imports/vip_student/project_2/project_2.srcs/sources_1/new/switches.v"
#    "/home/jdanner3/VIP/zedboard-baseline/fpga/project_2/project_2.srcs/sources_1/imports/sources_1/new/led_control.vhd"
#    "/home/jdanner3/VIP/zedboard-baseline/fpga/project_2/project_2.srcs/sources_1/imports/vip_student/Desktop/fpga-baseline-projects/zedboard/fpga/ip_repo/axi4_stream_user_processing_core_1.0/drivers/axi4_stream_user_processing_core_v1_0/src/axi4_stream_user_processing_core.h"
#    "/home/jdanner3/VIP/zedboard-baseline/fpga/project_2/project_2.srcs/sources_1/imports/vip_student/Desktop/fpga-baseline-projects/zedboard/fpga/ip_repo/axi4_stream_user_processing_core_1.0/example_designs/bfm_design/axi4_stream_user_processing_core_v1_0_tb.v"
#    "/home/jdanner3/VIP/zedboard-baseline/fpga/project_2/project_2.srcs/sources_1/imports/vip_student/Desktop/fpga-baseline-projects/zedboard/fpga/ip_repo/axi4_stream_user_processing_core_1.0/hdl/lib/fifo_cascade_axi_to_classic.v"
#    "/home/jdanner3/VIP/zedboard-baseline/fpga/project_2/project_2.srcs/sources_1/imports/vip_student/Desktop/fpga-baseline-projects/zedboard/fpga/ip_repo/axi4_stream_user_processing_core_1.0/hdl/lib/fifo_cascade_classic_to_axi.v"
#    "/home/jdanner3/VIP/zedboard-baseline/fpga/project_2/project_2.srcs/sources_1/imports/vip_student/Desktop/fpga-baseline-projects/zedboard/fpga/ip_repo/axi4_stream_user_processing_core_1.0/hdl/lib/fifo_long.v"
#    "/home/jdanner3/VIP/zedboard-baseline/fpga/project_2/project_2.srcs/sources_1/imports/vip_student/Desktop/fpga-baseline-projects/zedboard/fpga/ip_repo/axi4_stream_user_processing_core_1.0/hdl/lib/fifo_short.v"
#    "/home/jdanner3/VIP/zedboard-baseline/fpga/project_2/project_2.srcs/sources_1/imports/vip_student/Desktop/fpga-baseline-projects/zedboard/fpga/ip_repo/axi4_stream_user_processing_core_1.0/hdl/lib/ram_2port.v"
#    "/home/jdanner3/VIP/zedboard-baseline/fpga/project_2/project_2.srcs/sources_1/imports/vip_student/Desktop/fpga-baseline-projects/zedboard/fpga/ip_repo/axi4_stream_user_processing_core_1.0/hdl/lib/axi_fifo_short.v"
#    "/home/jdanner3/VIP/zedboard-baseline/fpga/project_2/project_2.srcs/sources_1/imports/vip_student/Desktop/fpga-baseline-projects/zedboard/fpga/ip_repo/axi4_stream_user_processing_core_1.0/hdl/custom_processing_core.v"
#    "/home/jdanner3/VIP/zedboard-baseline/fpga/project_2/project_2.srcs/sources_1/imports/vip_student/Desktop/fpga-baseline-projects/zedboard/fpga/ip_repo/axi4_stream_user_processing_core_1.0/hdl/axi4_stream_user_processing_core_v1_0_S_AXIS.v"
#    "/home/jdanner3/VIP/zedboard-baseline/fpga/project_2/project_2.srcs/sources_1/imports/vip_student/Desktop/fpga-baseline-projects/zedboard/fpga/ip_repo/axi4_stream_user_processing_core_1.0/hdl/axi4_stream_user_processing_core_v1_0.v"
#    "/home/jdanner3/VIP/zedboard-baseline/fpga/project_2/project_2.srcs/sources_1/imports/vip_student/Desktop/fpga-baseline-projects/zedboard/fpga/ip_repo/axi4_stream_user_processing_core_1.0/hdl/axi4_stream_user_processing_core_v1_0_M_AXIS.v"
#    "/home/jdanner3/VIP/zedboard-baseline/fpga/project_2/project_2.srcs/sources_1/imports/vip_student/Desktop/fpga-baseline-projects/zedboard/fpga/ip_repo/axi4_stream_user_processing_core_1.0/hdl/axi4_stream_user_processing_core_v1_0_S_AXI.v"
#    "/home/jdanner3/VIP/zedboard-baseline/fpga/project_2/project_2.srcs/constrs_1/imports/new/project_1.xdc"
#    "/home/jdanner3/VIP/zedboard-baseline/fpga/project_2/project_2.srcs/constrs_1/imports/hw-description/axi4_stream_user_processing_core.tcl"
#    "/home/jdanner3/VIP/zedboard-baseline/fpga/project_2/project_2.srcs/sim_1/imports/axi4_stream_user_processing_core_1.0/drivers/axi4_stream_user_processing_core_v1_0/src/axi4_stream_user_processing_core.h"
#    "/home/jdanner3/VIP/zedboard-baseline/fpga/project_2/project_2.srcs/sim_1/imports/axi4_stream_user_processing_core_1.0/drivers/axi4_stream_user_processing_core_v1_0/data/axi4_stream_user_processing_core.tcl"
#    "/home/jdanner3/VIP/zedboard-baseline/fpga/project_2/project_2.srcs/sim_1/imports/axi4_stream_user_processing_core_1.0/example_designs/debug_hw_design/design.tcl"
#    "/home/jdanner3/VIP/zedboard-baseline/fpga/project_2/project_2.srcs/sim_1/imports/axi4_stream_user_processing_core_1.0/example_designs/debug_hw_design/axi4_stream_user_processing_core_v1_0_hw_test.tcl"
#    "/home/jdanner3/VIP/zedboard-baseline/fpga/project_2/project_2.srcs/sim_1/imports/axi4_stream_user_processing_core_1.0/example_designs/bfm_design/axi4_stream_user_processing_core_v1_0_tb.v"
#    "/home/jdanner3/VIP/zedboard-baseline/fpga/project_2/project_2.srcs/sim_1/imports/axi4_stream_user_processing_core_1.0/example_designs/bfm_design/design.tcl"
#    "/home/jdanner3/VIP/zedboard-baseline/fpga/project_2/project_2.srcs/sim_1/imports/axi4_stream_user_processing_core_1.0/hdl/lib/fifo_cascade_axi_to_classic.v"
#    "/home/jdanner3/VIP/zedboard-baseline/fpga/project_2/project_2.srcs/sim_1/imports/axi4_stream_user_processing_core_1.0/hdl/lib/fifo_cascade_classic_to_axi.v"
#    "/home/jdanner3/VIP/zedboard-baseline/fpga/project_2/project_2.srcs/sim_1/imports/axi4_stream_user_processing_core_1.0/hdl/lib/fifo_long.v"
#    "/home/jdanner3/VIP/zedboard-baseline/fpga/project_2/project_2.srcs/sim_1/imports/axi4_stream_user_processing_core_1.0/hdl/lib/fifo_short.v"
#    "/home/jdanner3/VIP/zedboard-baseline/fpga/project_2/project_2.srcs/sim_1/imports/axi4_stream_user_processing_core_1.0/hdl/lib/ram_2port.v"
#    "/home/jdanner3/VIP/zedboard-baseline/fpga/project_2/project_2.srcs/sim_1/imports/axi4_stream_user_processing_core_1.0/hdl/lib/axi_fifo_short.v"
#    "/home/jdanner3/VIP/zedboard-baseline/fpga/project_2/project_2.srcs/sim_1/imports/axi4_stream_user_processing_core_1.0/hdl/custom_processing_core.v"
#    "/home/jdanner3/VIP/zedboard-baseline/fpga/project_2/project_2.srcs/sim_1/imports/axi4_stream_user_processing_core_1.0/hdl/axi4_stream_user_processing_core_v1_0_S_AXIS.v"
#    "/home/jdanner3/VIP/zedboard-baseline/fpga/project_2/project_2.srcs/sim_1/imports/axi4_stream_user_processing_core_1.0/hdl/axi4_stream_user_processing_core_v1_0.v"
#    "/home/jdanner3/VIP/zedboard-baseline/fpga/project_2/project_2.srcs/sim_1/imports/axi4_stream_user_processing_core_1.0/hdl/axi4_stream_user_processing_core_v1_0_M_AXIS.v"
#    "/home/jdanner3/VIP/zedboard-baseline/fpga/project_2/project_2.srcs/sim_1/imports/axi4_stream_user_processing_core_1.0/hdl/axi4_stream_user_processing_core_v1_0_S_AXI.v"
#    "/home/jdanner3/VIP/zedboard-baseline/fpga/project_2/project_2.srcs/sim_1/imports/axi4_stream_user_processing_core_1.0/bd/bd.tcl"
#    "/home/jdanner3/VIP/zedboard-baseline/fpga/project_2/project_2.srcs/sim_1/imports/axi4_stream_user_processing_core_1.0/xgui/axi4_stream_user_processing_core_v1_0.tcl"
#
# 3. The following remote source files that were added to the original project:-
#
#    "/home/jdanner3/VIP/zedboard-baseline/fpga/project_2/archive_project_summary.txt"
#
#*****************************************************************************************

# Set the reference directory for source file relative paths (by default the value is script directory path)
#set origin_dir "." @jdanner3
set origin_dir [file dirname [info script]]

# Set the directory path for the original project from where this script was exported
#set orig_proj_dir "[file normalize "$origin_dir/project_2"]" @jdanner3
set orig_proj_dir "[file normalize "$origin_dir/project"]"

# Create project 
#create_project project_2 ./project_2 @jdanner3
create_project zedboard_baseline $origin_dir/project

# Set the directory path for the new project
set proj_dir [get_property directory [current_project]]

# Set project properties
#set obj [get_projects project_2] @jdanner3
set obj [get_projects zedboard_baseline]
set_property "board_part" "em.avnet.com:zed:part0:1.2" $obj
set_property "default_lib" "xil_defaultlib" $obj
set_property "simulator_language" "Mixed" $obj
set_property "target_language" "VHDL" $obj

# Create 'sources_1' fileset (if not found)
if {[string equal [get_filesets -quiet sources_1] ""]} {
  create_fileset -srcset sources_1
}

# Set IP repository paths
set obj [get_filesets sources_1]
#set_property "ip_repo_paths" "[file normalize "$origin_dir/project_2/project_2.ipdefs/ip_repo"]" $obj @jdanner3
#set_property "ip_repo_paths" "[file normalize "$origin_dir/ip_repo/axi4_srteam_user_processing_core_1.0"]" $obj @jdanner3
set_property "ip_repo_paths" "[file normalize "$origin_dir/ip_repo"]" $obj

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# @jdanner3
set_property "top" "zedboard_baseline_wrapper" $obj

# @jdanner3
#set files [list \
# "[file normalize "$origin_dir/project_2/archive_project_summary.txt"]"\
#]
#add_files -norecurse -fileset $obj $files
#
## Import local files from the original project
#set files [list \
# "[file normalize "$origin_dir/project_2/project_2.srcs/sources_1/bd/base_zynq_design/base_zynq_design.bd"]"\
# "[file normalize "$origin_dir/project_2/project_2.srcs/sources_1/imports/sources_1/bd/base_zynq_design/hdl/base_zynq_design_wrapper.vhd"]"\
# "[file normalize "$origin_dir/project_2/project_2.srcs/sources_1/imports/vip_student/project_2/project_2.srcs/sources_1/new/switches.v"]"\
# "[file normalize "$origin_dir/project_2/project_2.srcs/sources_1/imports/sources_1/new/led_control.vhd"]"\
# "[file normalize "$origin_dir/project_2/project_2.srcs/sources_1/imports/vip_student/Desktop/fpga-baseline-projects/zedboard/fpga/ip_repo/axi4_stream_user_processing_core_1.0/drivers/axi4_stream_user_processing_core_v1_0/src/axi4_stream_user_processing_core.h"]"\
# "[file normalize "$origin_dir/project_2/project_2.srcs/sources_1/imports/vip_student/Desktop/fpga-baseline-projects/zedboard/fpga/ip_repo/axi4_stream_user_processing_core_1.0/example_designs/bfm_design/axi4_stream_user_processing_core_v1_0_tb.v"]"\
# "[file normalize "$origin_dir/project_2/project_2.srcs/sources_1/imports/vip_student/Desktop/fpga-baseline-projects/zedboard/fpga/ip_repo/axi4_stream_user_processing_core_1.0/hdl/lib/fifo_cascade_axi_to_classic.v"]"\
# "[file normalize "$origin_dir/project_2/project_2.srcs/sources_1/imports/vip_student/Desktop/fpga-baseline-projects/zedboard/fpga/ip_repo/axi4_stream_user_processing_core_1.0/hdl/lib/fifo_cascade_classic_to_axi.v"]"\
# "[file normalize "$origin_dir/project_2/project_2.srcs/sources_1/imports/vip_student/Desktop/fpga-baseline-projects/zedboard/fpga/ip_repo/axi4_stream_user_processing_core_1.0/hdl/lib/fifo_long.v"]"\
# "[file normalize "$origin_dir/project_2/project_2.srcs/sources_1/imports/vip_student/Desktop/fpga-baseline-projects/zedboard/fpga/ip_repo/axi4_stream_user_processing_core_1.0/hdl/lib/fifo_short.v"]"\
# "[file normalize "$origin_dir/project_2/project_2.srcs/sources_1/imports/vip_student/Desktop/fpga-baseline-projects/zedboard/fpga/ip_repo/axi4_stream_user_processing_core_1.0/hdl/lib/ram_2port.v"]"\
# "[file normalize "$origin_dir/project_2/project_2.srcs/sources_1/imports/vip_student/Desktop/fpga-baseline-projects/zedboard/fpga/ip_repo/axi4_stream_user_processing_core_1.0/hdl/lib/axi_fifo_short.v"]"\
# "[file normalize "$origin_dir/project_2/project_2.srcs/sources_1/imports/vip_student/Desktop/fpga-baseline-projects/zedboard/fpga/ip_repo/axi4_stream_user_processing_core_1.0/hdl/custom_processing_core.v"]"\
# "[file normalize "$origin_dir/project_2/project_2.srcs/sources_1/imports/vip_student/Desktop/fpga-baseline-projects/zedboard/fpga/ip_repo/axi4_stream_user_processing_core_1.0/hdl/axi4_stream_user_processing_core_v1_0_S_AXIS.v"]"\
# "[file normalize "$origin_dir/project_2/project_2.srcs/sources_1/imports/vip_student/Desktop/fpga-baseline-projects/zedboard/fpga/ip_repo/axi4_stream_user_processing_core_1.0/hdl/axi4_stream_user_processing_core_v1_0.v"]"\
# "[file normalize "$origin_dir/project_2/project_2.srcs/sources_1/imports/vip_student/Desktop/fpga-baseline-projects/zedboard/fpga/ip_repo/axi4_stream_user_processing_core_1.0/hdl/axi4_stream_user_processing_core_v1_0_M_AXIS.v"]"\
# "[file normalize "$origin_dir/project_2/project_2.srcs/sources_1/imports/vip_student/Desktop/fpga-baseline-projects/zedboard/fpga/ip_repo/axi4_stream_user_processing_core_1.0/hdl/axi4_stream_user_processing_core_v1_0_S_AXI.v"]"\
#]
#set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
#set file "base_zynq_design/base_zynq_design.bd"
#set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
#if { ![get_property "is_locked" $file_obj] } {
#  set_property "generate_synth_checkpoint" "0" $file_obj
#}
#
#set file "hdl/base_zynq_design_wrapper.vhd"
#set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
#set_property "file_type" "VHDL" $file_obj
#
#set file "new/led_control.vhd"
#set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
#set_property "file_type" "VHDL" $file_obj
#
#set file "src/axi4_stream_user_processing_core.h"
#set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
#set_property "file_type" "Verilog Header" $file_obj
#
#set file "lib/fifo_cascade_axi_to_classic.v"
#set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
#set_property "used_in_implementation" "0" $file_obj
#set_property "used_in_simulation" "0" $file_obj
#
#set file "lib/fifo_cascade_classic_to_axi.v"
#set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
#set_property "used_in_implementation" "0" $file_obj
#set_property "used_in_simulation" "0" $file_obj
#
#set file "lib/fifo_long.v"
#set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
#set_property "used_in_implementation" "0" $file_obj
#set_property "used_in_simulation" "0" $file_obj
#
#set file "lib/fifo_short.v"
#set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
#set_property "used_in_implementation" "0" $file_obj
#set_property "used_in_simulation" "0" $file_obj
#
#set file "lib/ram_2port.v"
#set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
#set_property "used_in_implementation" "0" $file_obj
#set_property "used_in_simulation" "0" $file_obj
#
#set file "lib/axi_fifo_short.v"
#set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
#set_property "used_in_implementation" "0" $file_obj
#set_property "used_in_simulation" "0" $file_obj
#
#set file "hdl/custom_processing_core.v"
#set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
#set_property "used_in_implementation" "0" $file_obj
#set_property "used_in_simulation" "0" $file_obj
#
#set file "hdl/axi4_stream_user_processing_core_v1_0_S_AXIS.v"
#set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
#set_property "used_in_implementation" "0" $file_obj
#set_property "used_in_simulation" "0" $file_obj
#
#set file "hdl/axi4_stream_user_processing_core_v1_0.v"
#set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
#set_property "used_in_implementation" "0" $file_obj
#set_property "used_in_simulation" "0" $file_obj
#
#set file "hdl/axi4_stream_user_processing_core_v1_0_M_AXIS.v"
#set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
#set_property "used_in_implementation" "0" $file_obj
#set_property "used_in_simulation" "0" $file_obj
#
#set file "hdl/axi4_stream_user_processing_core_v1_0_S_AXI.v"
#set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
#set_property "used_in_implementation" "0" $file_obj
#set_property "used_in_simulation" "0" $file_obj
#
#
## Set 'sources_1' fileset properties
#set obj [get_filesets sources_1]
#set_property "top" "base_zynq_design_wrapper" $obj

# Create 'constrs_1' fileset (if not found)
if {[string equal [get_filesets -quiet constrs_1] ""]} {
  create_fileset -constrset constrs_1
}

# Set 'constrs_1' fileset object
set obj [get_filesets constrs_1]

# Add/Import constrs file and set constrs file properties
#set file "[file normalize "$origin_dir/project_2/project_2.srcs/constrs_1/imports/new/project_1.xdc"]"
#
set file "[file normalize "$origin_dir/src/bd/ZED_Master.xdc"]"
#set file_imported [import_files -fileset constrs_1 $file] @jdanner3
set file_added [add_files -norecurse -fileset $obj $file]
set file "$origin_dir/src/bd/ZED_Master.xdc"
# @jdanner3
set file [file normalize $file]

set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property "file_type" "XDC" $file_obj

# Add/Import constrs file and set constrs file properties
# @jdanner3
#set file "[file normalize "$origin_dir/project_2/project_2.srcs/constrs_1/imports/hw-description/axi4_stream_user_processing_core.tcl"]"
#set file_imported [import_files -fileset constrs_1 $file]
#set file "hw-description/axi4_stream_user_processing_core.tcl"
#set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
#set_property "file_type" "TCL" $file_obj

# Set 'constrs_1' fileset properties
set obj [get_filesets constrs_1]
#set_property "target_constrs_file" "$proj_dir/project_2.srcs/constrs_1/imports/new/project_1.xdc" $obj @jdanner3

# Create 'sim_1' fileset (if not found)
if {[string equal [get_filesets -quiet sim_1] ""]} {
  create_fileset -simset sim_1
}

# Set 'sim_1' fileset object
set obj [get_filesets sim_1]
# Import local files from the original project
#set files [list \
# @jdanner3
# "[file normalize "$origin_dir/project_2/project_2.srcs/sim_1/imports/axi4_stream_user_processing_core_1.0/drivers/axi4_stream_user_processing_core_v1_0/src/axi4_stream_user_processing_core.h"]"\
# "[file normalize "$origin_dir/project_2/project_2.srcs/sim_1/imports/axi4_stream_user_processing_core_1.0/drivers/axi4_stream_user_processing_core_v1_0/data/axi4_stream_user_processing_core.tcl"]"\
# "[file normalize "$origin_dir/project_2/project_2.srcs/sim_1/imports/axi4_stream_user_processing_core_1.0/example_designs/debug_hw_design/design.tcl"]"\
# "[file normalize "$origin_dir/project_2/project_2.srcs/sim_1/imports/axi4_stream_user_processing_core_1.0/example_designs/debug_hw_design/axi4_stream_user_processing_core_v1_0_hw_test.tcl"]"\
# "[file normalize "$origin_dir/project_2/project_2.srcs/sim_1/imports/axi4_stream_user_processing_core_1.0/example_designs/bfm_design/axi4_stream_user_processing_core_v1_0_tb.v"]"\
# "[file normalize "$origin_dir/project_2/project_2.srcs/sim_1/imports/axi4_stream_user_processing_core_1.0/example_designs/bfm_design/design.tcl"]"\
# "[file normalize "$origin_dir/project_2/project_2.srcs/sim_1/imports/axi4_stream_user_processing_core_1.0/hdl/lib/fifo_cascade_axi_to_classic.v"]"\
# "[file normalize "$origin_dir/project_2/project_2.srcs/sim_1/imports/axi4_stream_user_processing_core_1.0/hdl/lib/fifo_cascade_classic_to_axi.v"]"\
# "[file normalize "$origin_dir/project_2/project_2.srcs/sim_1/imports/axi4_stream_user_processing_core_1.0/hdl/lib/fifo_long.v"]"\
# "[file normalize "$origin_dir/project_2/project_2.srcs/sim_1/imports/axi4_stream_user_processing_core_1.0/hdl/lib/fifo_short.v"]"\
# "[file normalize "$origin_dir/project_2/project_2.srcs/sim_1/imports/axi4_stream_user_processing_core_1.0/hdl/lib/ram_2port.v"]"\
# "[file normalize "$origin_dir/project_2/project_2.srcs/sim_1/imports/axi4_stream_user_processing_core_1.0/hdl/lib/axi_fifo_short.v"]"\
# "[file normalize "$origin_dir/project_2/project_2.srcs/sim_1/imports/axi4_stream_user_processing_core_1.0/hdl/custom_processing_core.v"]"\
# "[file normalize "$origin_dir/project_2/project_2.srcs/sim_1/imports/axi4_stream_user_processing_core_1.0/hdl/axi4_stream_user_processing_core_v1_0_S_AXIS.v"]"\
# "[file normalize "$origin_dir/project_2/project_2.srcs/sim_1/imports/axi4_stream_user_processing_core_1.0/hdl/axi4_stream_user_processing_core_v1_0.v"]"\
# "[file normalize "$origin_dir/project_2/project_2.srcs/sim_1/imports/axi4_stream_user_processing_core_1.0/hdl/axi4_stream_user_processing_core_v1_0_M_AXIS.v"]"\
# "[file normalize "$origin_dir/project_2/project_2.srcs/sim_1/imports/axi4_stream_user_processing_core_1.0/hdl/axi4_stream_user_processing_core_v1_0_S_AXI.v"]"\
# "[file normalize "$origin_dir/project_2/project_2.srcs/sim_1/imports/axi4_stream_user_processing_core_1.0/bd/bd.tcl"]"\
# "[file normalize "$origin_dir/project_2/project_2.srcs/sim_1/imports/axi4_stream_user_processing_core_1.0/xgui/axi4_stream_user_processing_core_v1_0.tcl"]"\
#]
#set imported_files [import_files -fileset sim_1 $files]

# Set 'sim_1' fileset file properties for remote files
# None

# Set 'sim_1' fileset file properties for local files
#set file "src/axi4_stream_user_processing_core.h"
#set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
#set_property "file_type" "Verilog Header" $file_obj
#
#set file "data/axi4_stream_user_processing_core.tcl"
#set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
#set_property "file_type" "TCL" $file_obj
#
#set file "debug_hw_design/design.tcl"
#set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
#set_property "file_type" "TCL" $file_obj
#
#set file "debug_hw_design/axi4_stream_user_processing_core_v1_0_hw_test.tcl"
#set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
#set_property "file_type" "TCL" $file_obj
#
#set file "bfm_design/design.tcl"
#set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
#set_property "file_type" "TCL" $file_obj
#
#set file "bd/bd.tcl"
#set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
#set_property "file_type" "TCL" $file_obj
#
#set file "xgui/axi4_stream_user_processing_core_v1_0.tcl"
#set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
#set_property "file_type" "TCL" $file_obj


# Set 'sim_1' fileset properties
set obj [get_filesets sim_1]
#set_property "top" "base_zynq_design_wrapper" $obj
set_property "top" "zedboard_baseline_wrapper" $obj

# Create 'synth_1' run (if not found)
if {[string equal [get_runs -quiet synth_1] ""]} {
  create_run -name synth_1 -part xc7z020clg484-1 -flow {Vivado Synthesis 2014} -strategy "Vivado Synthesis Defaults" -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs synth_1]
  set_property flow "Vivado Synthesis 2014" [get_runs synth_1]
}
set obj [get_runs synth_1]

# set the current synth run
current_run -synthesis [get_runs synth_1]

# Create 'impl_1' run (if not found)
if {[string equal [get_runs -quiet impl_1] ""]} {
  create_run -name impl_1 -part xc7z020clg484-1 -flow {Vivado Implementation 2014} -strategy "Vivado Implementation Defaults" -constrset constrs_1 -parent_run synth_1
} else {
  set_property strategy "Vivado Implementation Defaults" [get_runs impl_1]
  set_property flow "Vivado Implementation 2014" [get_runs impl_1]
}
set obj [get_runs impl_1]
# @jdanner3
set_property "part" "xc7z020clg484-1" $obj

# set the current impl run
current_run -implementation [get_runs impl_1]

# @jdanner3 VVV
# Update repo catalog
update_ip_catalog -rebuild

# Create Block Design
source $origin_dir/src/bd/zedboard_baseline.tcl
regenerate_bd_layout

# Generate Wrapper 
make_wrapper -files [get_files $design_name.bd] -top -import
validate_bd_design

# Generate output products
generate_target all [get_files $origin_dir/project/zedboard_baseline.srcs/sources_1/bd/zedboard_baseline/zedboard_baseline.bd]

# Run synthesis
launch_runs impl_1 -to_step write_bitstream
wait_on_run impl_1

# Export HW
file mkdir $origin_dir/zedboard_baseline/zedboard_baseline.sdk
file copy $origin_dir/zedboard_baseline/zedboard_baseline.runs/impl_1/zedboard_baseline_wrapper.sysdef $origin_dir/zedboard_baseline/zedboard_baseline.sdk/zedboard_baseline_wrapper.hdf

puts "INFO: Project created:zedboard_baseline"
