/*  strfifo.c - The simplest kernel module.
 */
#include <linux/kernel.h>
#include <linux/init.h>
#include <linux/module.h>
#include <linux/slab.h>
#include <linux/io.h>
#include <linux/interrupt.h>

#include <linux/of_address.h>
#include <linux/of_device.h>
#include <linux/of_platform.h>

/* Standard module information, edit as appropriate */
MODULE_LICENSE("GPL");
MODULE_AUTHOR
    ("Xilinx Inc.");
MODULE_DESCRIPTION
    ("strfifo - loadable module template generated by petalinux-create -t modules");

#define DRIVER_NAME "strfifo"
#define CLASS_NAME  "STRFIFO"

// RESET_FIFO_MASK is used for resetting the entire FIFO, RDFR and TDFR
// RDFR and TDFR cannot be reset by any other values
#define RESET_FIFO_MASK 0xA5

// The mask for Transmit Data Vacancy (16th - 0th bit)
#define TDFV_MASK 0xfff

// Register Addresses 
#define ISR 0x00 
#define IER 0x04 
#define TDFR 0x08 
#define TDFV 0x0C
#define TDFD 0x10
#define TLR 0x14
#define RDFR 0x18
#define RDFO 0x1C
#define RDFD 0x20
#define RLR 0x24 
#define SRR 0x28
#define TDR 0x2C
#define RDR 0x30
#define TIDR 0x34
#define TxUSER 0x38


// ISR bit mask
#define IRQ_RFPE_MASK (1<<19)
#define IRQ_RFPF_MASK (1<<20)
#define IRQ_TFPE_MASK (1<<21)
#define IRQ_TFPF_MASK (1<<22)
#define IRQ_RRC_MASK (1<<23)
#define IRQ_TRC_MASK (1<<24)
#define IRQ_TSE_MASK (1<<25)
#define IRQ_RC_MASK (1<<26)
#define IRQ_TC_MASK (1<<27)
#define IRQ_TPOE_MASK (1<<28)
#define IRQ_RPUE_MASK (1<<29)
#define IRQ_RPORE_MASK (1<<30)
#define IRQ_RPURE_MASK (1<<31)



/* Simple example of how to receive command line parameters to your module.
   Delete if you don't need them */
/*
unsigned myint = 0xdeadbeef;
char *mystr = "default";

module_param(myint, int, S_IRUGO);
module_param(mystr, charp, S_IRUGO);
*/

struct strfifo_local {
	
	unsigned long mem_start;
	unsigned long mem_end;


  	void __iomem *C_BASEADDR;
  	struct device *dev;
	//char *name;
	int irq;
	int32_t irq_mask;
	int32_t fifo_depth;
	int32_t tdest;
	uint32_t *txbuffer, *rxbuffer;
	struct completion comp;
	struct spinlock mlock;
	struct list_head list;
	//struct miscdevice misc;


};
// Initializing strfifo struct

static struct strfifo_local *strfifo;
static LIST_HEAD(strfifo_data_list);


/*INITIALIZATION FUNCTIONS*/

/*FIFO Reset. Usable from either end of the streaming fifo. Will reset entire core, including
external outputs s2mm_prmry_reset_out_n, mm2s_prmry_reset_out_n, and mm2s_cntrl_reset_out_n. Resets
when register SSR is written with FIFO_RESET_VALUE.*/

static void fifo_core_reset(void)
{
	writel(RESET_FIFO_MASK, strfifo->C_BASEADDR+SRR);
}



/******************/
/* File Operation */
/******************/

static struct file_operations fops = {
	.open = strfifo_open,
	.read = strfifo_read,
	.release = strfifo_release,
	.write = strfifo_write,
	//.unlocked_ioctl = strfifo_ioctl,
};

static int strfifo_open(struct inode *inodep, struct file *filep){
	
	filep->private_data = (struct device*)sdev;
	strfifo = sdev;
   	return 0;
}

static ssize_t strfifo_read(struct file *filep, char *buffer, size_t len, loff_t *offset){
	int retval;
	// return the data size in the buffer
	return retval;
}
static int strfifo_release(struct inode *inodep, struct file *filep){
	
	filep->private_data = NULL;
	printk(KERN_INFO "strfifo: close()\n");
	return 0;
}
/************************/
/* File Operation (End) */
/************************/


/* IRQ Functions*/

static void printIRQmask(int mask)
{
	//
};
static int get_irq_status(void)
{
	return readl(strfifo->C_BASEADDR+ISR);
}

static int get_ier_status(void)
{
	return readl(strfifo->C_BASEADDR+IER);
}

// Change IER values to enable/disable different interrupts
static void set_irq_status(uint32_t mask)
{
	writel(mask, strfifo->C_BASEADDR+IER);
}

static void reset_irq_reg(void)
{
	writel(0xffffffff, strfifo->C_BASEADDR+ISR);
}


// strfifo_irq was here in default.
static irqreturn_t strfifo_irq(int irq, void *lp)
{
	printk("strfifo interrupt\n");
	return IRQ_HANDLED;
}


/* TX FUNCTIONS */

static int get_tx_fifo_vacancy(void)
{
	// the return value tells us how many available writes there are
	// the register value changes every 2 writes
	// each write is 4 bytes long, or 1 word long
	return (int)(readl(strfifo->C_BASEADDR+TDFV)&TDFV_MASK);
}

static void set_txdest(uint32_t addr)
{
	writel(addr, strfifo->C_BASEADDR+TDR);
}

static void set_tx_fifo(uint32_t value)
{
	writel(value, strfifo->C_BASEADDR+TDFD);
}

static void set_tx_len(uint32_t nwords)
{
	writel(nwords*4, strfifo->C_BASEADDR+TLR); // Turn words into bytes
}

static int fill_tx_fifo(int *buffer, int xfer_len)
{
	// check whether TDFD has enough memory
	// if TDFD has enough memory, write to TDFD
	// if not, set total words remaining to TDFD memory size
	// write to TDFD

	// return the lengths of data actually written to TDFD
	int k, EnoughMem=1;
	int WordsLeft = xfer_len;
	int MemSize = get_tx_fifo_vacancy(); // in words

	if (MemSize < WordsLeft)
	{
		WordsLeft = MemSize;
		EnoughMem = 0;
	}
	for(k=0; k<WordsLeft; k++)
	{
		set_tx_fifo(buffer[k]);
	}
	
	// check whether data is filled in TDFD
	// because vacancy only changes every 2 words written, I'm doing a general check
	if (EnoughMem && (MemSize > get_tx_fifo_vacancy()))
	{
		return WordsLeft;
	} else if ((!EnoughMem) && (get_tx_fifo_vacancy()==0))
	{
		// if not enough memory is available, check whether TDFD is filled completely
		return WordsLeft;
	} else
	{
		return -1;
	}
		
	
	

		

/* Original Code */
/*
	int nR1, nR2, k = 0;
	// nR1 = number of available storage locations before filling
	nR1 = get_tx_fifo_vacancy();

	for(k = 0; k < xfer_len; k++)
		set_tx_fifo(buffer[k]); //write FPGA
	// nR2 = number of available storage locations after filling
	nR2 = get_tx_fifo_vacancy();

	


	if ((nR1-nR2) != xfer_len)
		return -1;
	else
		return 0;
*/
/* Original */
	/* Original Code
	if((nR2-nR1) != xfer_len)
		return -1;
	else 
		return 0x00; */

	
	// nR1 - nR2 = number of locations successfully written
				
}


static int strfifo_write_buffer(int *txbuffer, uint32_t tdest, 
		uint32_t xfer_len)
{
	int rc = 0;
	int len_xfered;
	unsigned long flags;

	reset_irq_reg();
	set_irq_status(IRQ_TC_MASK);
	len_xfered = fill_tx_fifo(txbuffer, xfer_len); // return value shows the actual transfer length, in words
	if(len_xfered < 0)
	{
		printk(KERN_ERR "fill tx fifo failed\n");
		rc = TX_FAILED;
		goto fail;
	}else{
		// print transfer length
		printk("fill tx fifo succeeded\n");
		printk("Desired Xfer Length: %d, Actual Xfer Length: %d\n",xfer_len, len_xfered );
	}
	
	set_txdest(tdest);
	// completion tutorial: https://www.kernel.org/doc/Documentation/scheduler/completion.txt
	init_completion(&strfifo->comp); //wait for next IRQ," done" set to 0	
	
	
	//set_tx_len(xfer_len);
	set_tx_len(len_xfered); // set the actual transmit length

	
	wait_for_completion(&strfifo->comp); 

	spin_lock_irqsave(&strfifo->mlock, flags);

	// check if IRQ_TC_COMPLETE is the only flag received
	if(strfifo->irq_mask == IRQ_TC_MASK)
		rc = XFER_SUCCESS;		
	else 
	{
		printk(KERN_ERR "strfifo xfer failed\n");
		printIRQmask(strfifo->irq_mask);
		status = TX_FAILED;
	}

	spin_unlock_irqrestore(&strfifo->mlock, flags);


/* Original Code 

	set_tx_tdest_address(tdest);
	set_tx_len(xfer_len);

	init_completion(&strfifo->comp); //wait for next IRQ
	spin_lock_irqsave(&strfifo->mlock, flags);

	// check if IRQ_TC_COMPLETE is the only flag received
	if(strfifo->irq_mask == IRQ_TC_MASK)
		rc = XFER_SUCCESS;		
	else 
	{
		printk(KERN_ERR "strfifo xfer failed\n");
		printIRQmask(strfifo->irq_mask);
		status = TX_FAILED;
	}

	spin_unlock_irqrestore(&strfifo->mlock, flags);
*/
	return rc;

fail:
	return rc;

};


/* RX FUNCTIONS */

static int get_rx_fifo_occupancy(void)
{
	
	return readl(strfifo->C_BASEADDR+RDFO);
}

/*
It is impossible to set rx_len according to data sheet

static void set_rx_len(uint32_t nwords)
{
	writel(nwords*4, strfifo->C_BASEADDR+RLR);
}
*/

static int get_rx_len(void)
{
	
	return readl(strfifo->C_BASEADDR+RLR);
}

/*
It is impossible to set rx_destination according to data sheet

static void set_rx_tdest_address(uint32_t addr)
{
	writel(addr, strfifo->C_BASEADDR+RDR);
}
*/
static int get_rxdest(void)
{
	// return the address where rx data is stored
	return readl(strfifo->C_BASEADDR+RDR);
}

static void reset_rx_fifo(void)
{
	writel(RESET_FIFO_MASK, strfifo->C_BASEADDR+RDFR);
}

static int get_rx_fifo(void)
{
	return readl(strfifo->C_BASEADDR+RDFD);
}

// for file operation
static void read_rx_fifo(int *rxbuffer, int len_)
{
	// we should check whether the received packet size matches the transmitted packet size
	int k = 0;
	for(k = 0; k < len_; k++)
		rxbuffer[k] = get_rx_fifo();	
}

static int strfifo_read_buffer(int *rxbuffer, uint32_t tdest, 
		uint32_t xfer_len)
{

	int rc_flag = ( get_irq_status() && ;
// read ISR an see if there's an RC interrupt
	if (IRQ_RC_MASK)  // see if there is Receive_Complete Interrupt. rc_flag should be 1

// reset ISR

// make sure there's no more RC interrupt, or make sure ISR is reset successfully

// read receive fifo occupancy (RDFO)
// If there's only one packet received, value will be returned

// read RLR. Receive Length. It should give the number of bytes of the corresponding receive data stored in the receive data FIFO.

// read RDR , Receive Destination Address

// read RDFO again, makesure that the received data hasn't changed.

// read data and store it into buffer

// read RDFO again, now the occupancy should be 0, since all the data has been read




}

// Default by Xilinx

static int strfifo_probe(struct platform_device *pdev)
{
	struct resource *r_irq; /* Interrupt resources */
	struct resource *r_mem; /* IO mem resources */
	struct device *dev = &pdev->dev;
	struct strfifo_local *lp = NULL;





/* Driver initialization moved from init */

	/* Initialize strfifo class and char driver*/

	printk(KERN_INFO "Initializing the strfifo..\n");
 
	   // Try to dynamically allocate a major number for the device -- more difficult but worth it
	   majorNumber = register_chrdev(0, DRIVER_NAME, &fops);
	   if (majorNumber<0){
	      printk(KERN_ALERT "strfifo failed to register a major number\n");
	      return majorNumber;
	   }
	   printk(KERN_INFO "strfifo: registered correctly with major number %d\n", majorNumber);
	 
	   // Register the device class
	   strfifoClass = class_create(THIS_MODULE, CLASS_NAME);
	   if (IS_ERR(strfifoClass)){                // Check for error and clean up if there is
	      unregister_chrdev(majorNumber, DRIVER_NAME);
	      printk(KERN_ALERT "Failed to register device class\n");
	      return PTR_ERR(strfifoClass);          // Correct way to return an error on a pointer
	   }
	   printk(KERN_INFO "strfifo: device class registered correctly\n");
	 
	   // Register the device driver
	   strfifo = device_create(strfifoClass, NULL, MKDEV(majorNumber, 0), NULL, DRIVER_NAME);
	   
	if (IS_ERR(strfifo)){               // Clean up if there is an error
		class_destroy(strfifoClass);           // Repeated code but the alternative is goto statements
	        unregister_chrdev(majorNumber, DRIVER_NAME);
	        printk(KERN_ALERT "Failed to create the device\n");
	        return PTR_ERR(strfifo);
	     }
	   printk(KERN_INFO "strfifo: device class created correctly\n"); // Made it! device was initialized
	   return 0;
/* Driver initialization moved from init (end) */	


	int rc = 0;
	
	dev_info(dev, "Device Tree Probing\n");

	/* Get iospace for the device */
	r_mem = platform_get_resource(pdev, IORESOURCE_MEM, 0);
	if (!r_mem) {
		dev_err(dev, "invalid address\n");
		return -ENODEV;
	}
	
	lp = (struct strfifo_local *) kmalloc(sizeof(struct strfifo_local), GFP_KERNEL);
	if (!lp) {
		dev_err(dev, "Cound not allocate strfifo device\n");
		return -ENOMEM;
	}
	
	dev_set_drvdata(dev, lp);
	
	lp->mem_start = r_mem->start;
	lp->mem_end = r_mem->end;

	if (!request_mem_region(lp->mem_start,
				lp->mem_end - lp->mem_start + 1,
				DRIVER_NAME)) {
		dev_err(dev, "Couldn't lock memory region at %p\n",
			(void *)lp->mem_start);
		rc = -EBUSY;
		goto error1;
	}

	lp->base_addr = ioremap(lp->mem_start, lp->mem_end - lp->mem_start + 1);
	if (!lp->base_addr) {
		dev_err(dev, "strfifo: Could not allocate iomem\n");
		rc = -EIO;
		goto error2;
	}

	/* Get IRQ for the device */
	r_irq = platform_get_resource(pdev, IORESOURCE_IRQ, 0);
	if (!r_irq) {
		dev_info(dev, "no IRQ found\n");
		dev_info(dev, "strfifo at 0x%08x mapped to 0x%08x\n",
			(unsigned int __force)lp->mem_start,
			(unsigned int __force)lp->base_addr);
		return 0;
	}
	lp->irq = r_irq->start;
	
	rc = request_irq(lp->irq, &strfifo_irq, 0, DRIVER_NAME, lp);
	if (rc) {
		dev_err(dev, "testmodule: Could not allocate interrupt %d.\n",
			lp->irq);
		goto error3;
	}

	dev_info(dev,"strfifo at 0x%08x mapped to 0x%08x, irq=%d\n",
		(unsigned int __force)lp->mem_start,
		(unsigned int __force)lp->base_addr,
		lp->irq);
	return 0;
error3:
	free_irq(lp->irq, lp);
error2:
	release_mem_region(lp->mem_start, lp->mem_end - lp->mem_start + 1);
error1:
	kfree(lp);
	dev_set_drvdata(dev, NULL);
	return rc;
}

static int strfifo_remove(struct platform_device *pdev)
{
	struct device *dev = &pdev->dev;
	struct strfifo_local *lp = dev_get_drvdata(dev);
	free_irq(lp->irq, lp);
	release_mem_region(lp->mem_start, lp->mem_end - lp->mem_start + 1);
	kfree(lp);
	dev_set_drvdata(dev, NULL);
	return 0;
}

#ifdef CONFIG_OF
static struct of_device_id strfifo_of_match[] = {
	{ .compatible = "vendor,strfifo", },
	{ /* end of list */ },
};
MODULE_DEVICE_TABLE(of, strfifo_of_match);
#else
# define strfifo_of_match
#endif


static struct platform_driver strfifo_driver = {
	.driver = {
		.name = strfifo,
		.owner = GaTech Emb Sys VIP,
		.of_match_table	= strfifo_of_match,
	},
	.probe		= strfifo_probe,
	.remove		= strfifo_remove,
};

static int __init strfifo_init(void)
{

	
	printk("<1>Hello module world.\n");
	printk("<1>Module parameters were (0x%08x) and \"%s\"\n", myint,
	       mystr);


	//
	// Default by Xilinx
	return platform_driver_register(&strfifo_driver); // Not sure if this is needed
}


static void __exit strfifo_exit(void)
{
	platform_driver_unregister(&strfifo_driver);
	printk(KERN_ALERT "Goodbye module world.\n");

	/*New*/
	device_destroy(strfifoClass, MKDEV(majorNumber, 0));     // remove the device
  	class_unregister(strfifoClass);                          // unregister the device class
  	class_destroy(strfifoClass);                             // remove the device class
   	unregister_chrdev(majorNumber, DRIVER_NAME);             // unregister the major number
   	printk(KERN_INFO "strfifo: Goodbye from the LKM!\n");
}

module_init(strfifo_init);
module_exit(strfifo_exit);
